SpECTRE: src/Parallel/Algorithm.hpp File Reference
Algorithm.hpp File Reference
#include <functional>
#include "DataStructures/DataBox.hpp"
#include "ErrorHandling/Error.hpp"
#include "Parallel/ArrayIndex.hpp"
#include "Parallel/ParallelComponentHelpers.hpp"
#include "Parallel/TypeTraits.hpp"
#include "Utilities/BoostHelpers.hpp"
#include "Utilities/ConstantExpressions.hpp"
#include "Utilities/Gsl.hpp"
#include "Utilities/NoSuchType.hpp"
#include "Utilities/Overloader.hpp"
#include "Utilities/PrettyType.hpp"
#include "Utilities/TMPL.hpp"
#include "Utilities/TaggedTuple.hpp"
#include "Utilities/TypeTraits.hpp"
Classes
class is_apply_callable< TT, TArgs >
class AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >
A distributed object (Charm++ Chare) that executes a series of Actions and is capable of sending and receiving data. Acts as an interface to Charm++.
Namespaces
Parallel
Contains functions that forward to Charm++ parallel functions.
Typedefs
using Parallel::type = std::integral_constant< bool, value >
template<typename TT , typename... TArgs>
using has_is_ready_t = typename has_is_ready< TT, TArgs... >::type
Functions
void Parallel::lock (const gsl::not_null< CmiNodeLock *> node_lock) noexcept
Lock a converse CmiNodeLock.
bool Parallel::try_lock (const gsl::not_null< CmiNodeLock *> node_lock) noexcept
Returns true if the lock was successfully acquired and false if the lock is already acquired by another processor.
void Parallel::unlock (const gsl::not_null< CmiNodeLock *> node_lock) noexcept
Unlock a converse CmiNodeLock.
template<typename Invokable , typename ThisVariant , typename... Variants, typename... Args, Requires< is_apply_callable< Invokable, std::add_lvalue_reference_t< ThisVariant >, Args &&... >::value > = nullptr>
void apply_visitor_helper (boost::variant< Variants... > &box, const gsl::not_null< int *> iter, const gsl::not_null< bool *> already_visited, Args &&... args)
template<typename Invokable , typename ThisVariant , typename... Variants, typename... Args, Requires< not is_apply_callable< Invokable, std::add_lvalue_reference_t< ThisVariant >, Args &&... >::value > = nullptr>
void apply_visitor_helper (boost::variant< Variants... > &box, const gsl::not_null< int *> iter, const gsl::not_null< bool *> already_visited, Args &&...)
template<typename Invokable , typename... Variants, typename... Args>
void apply_visitor (boost::variant< Variants... > &box, Args &&... args)
Calls an Invokable's apply static member function with the current type in the boost::variant.
Variables
static constexpr bool Parallel::value = decltype(test_callable<TT, TArgs...>(0))::value
Typedef Documentation
has_is_ready_t
template<typename TT , typename... TArgs> using has_is_ready_t = typename has_is_ready<TT, TArgs...>::type
Function Documentation
apply_visitor()
template<typename Invokable , typename... Variants, typename... Args> void apply_visitor (boost::variant< Variants... > & box, Args &&... args)
Calls an Invokable's apply static member function with the current type in the boost::variant.
The primary use case for this is to allow executing a single Action at any point in the Algorithm. The current best-known use case for this is setting up initial data. However, the implementation is generic enough to handle a call at any time that is valid. Here valid is defined as the apply function only accesses members of the DataBox that are guaranteed to be present when it is invoked, and returns a DataBox of a type that does not break the Algorithm.
apply_visitor_helper() [1/2]
template<typename Invokable , typename ThisVariant , typename... Variants, typename... Args, Requires< is_apply_callable< Invokable, std::add_lvalue_reference_t< ThisVariant >, Args &&... >::value > = nullptr> void apply_visitor_helper (boost::variant< Variants... > & box, const gsl::not_null< int *> iter, const gsl::not_null< bool *> already_visited, Args &&... args)
References db::apply(), ERROR, make_overloader(), and Parallel::value.
apply_visitor_helper() [2/2]
template<typename Invokable , typename ThisVariant , typename... Variants, typename... Args, Requires< not is_apply_callable< Invokable, std::add_lvalue_reference_t< ThisVariant >, Args &&... >::value > = nullptr> void apply_visitor_helper (boost::variant< Variants... > & box, const gsl::not_null< int *> iter, const gsl::not_null< bool *> already_visited, Args && ...)
References ERROR, and pretty_type::get_name().