SpECTRE: src/Executables/Benchmark/Benchmark.cpp File Reference
Benchmark.cpp File Reference
#include <benchmark/benchmark.h>
#include <vector>
#include "DataStructures/DataBoxTag.hpp"
#include "DataStructures/DataVector.hpp"
#include "DataStructures/Index.hpp"
#include "DataStructures/Tensor/Tensor.hpp"
#include "DataStructures/Variables.hpp"
#include "Domain/CoordinateMaps/AffineMap.hpp"
#include "Domain/CoordinateMaps/CoordinateMap.hpp"
#include "Domain/CoordinateMaps/ProductMaps.hpp"
#include "Domain/Element.hpp"
#include "Domain/LogicalCoordinates.hpp"
#include "Numerical/LinearOperators/PartialDerivatives.hpp"
#include "Numerical/Spectral/LegendreGaussLobatto.hpp"
#include "PointwiseFunctions/MathFunctions/PowX.hpp"
Functions
void CkRegisterMainModule (void)
Function Documentation
CkRegisterMainModule()
void CkRegisterMainModule (void)
References CoordinateMap< SourceFrame, TargetFrame, Maps >::inv_jacobian(), logical_coordinates(), and Index< Dim >::product().