SpECTRE: src/Domain/Block.cpp File Reference
Block.cpp File Reference
#include "Domain/Block.hpp"
Functions
template<size_t VolumeDim, typename TargetFrame >
std::ostream & operator<< (std::ostream &os, const Block< VolumeDim, TargetFrame > &block)
template<size_t VolumeDim, typename TargetFrame >
bool operator== (const Block< VolumeDim, TargetFrame > &lhs, const Block< VolumeDim, TargetFrame > &rhs) noexcept
template<size_t VolumeDim, typename TargetFrame >
bool operator!= (const Block< VolumeDim, TargetFrame > &lhs, const Block< VolumeDim, TargetFrame > &rhs) noexcept
template std::ostream & operator<< (std::ostream &os, const Block< 1, Frame::Grid > &block)
template std::ostream & operator<< (std::ostream &os, const Block< 2, Frame::Grid > &block)
template std::ostream & operator<< (std::ostream &os, const Block< 3, Frame::Grid > &block)
template std::ostream & operator<< (std::ostream &os, const Block< 1, Frame::Inertial > &block)
template std::ostream & operator<< (std::ostream &os, const Block< 2, Frame::Inertial > &block)
template std::ostream & operator<< (std::ostream &os, const Block< 3, Frame::Inertial > &block)
template bool operator== (const Block< 1, Frame::Grid > &lhs, const Block< 1, Frame::Grid > &rhs) noexcept
template bool operator== (const Block< 2, Frame::Grid > &lhs, const Block< 2, Frame::Grid > &rhs) noexcept
template bool operator== (const Block< 3, Frame::Grid > &lhs, const Block< 3, Frame::Grid > &rhs) noexcept
template bool operator== (const Block< 1, Frame::Inertial > &lhs, const Block< 1, Frame::Inertial > &rhs) noexcept
template bool operator== (const Block< 2, Frame::Inertial > &lhs, const Block< 2, Frame::Inertial > &rhs) noexcept
template bool operator== (const Block< 3, Frame::Inertial > &lhs, const Block< 3, Frame::Inertial > &rhs) noexcept
template bool operator!= (const Block< 1, Frame::Grid > &lhs, const Block< 1, Frame::Grid > &rhs) noexcept
template bool operator!= (const Block< 2, Frame::Grid > &lhs, const Block< 2, Frame::Grid > &rhs) noexcept
template bool operator!= (const Block< 3, Frame::Grid > &lhs, const Block< 3, Frame::Grid > &rhs) noexcept
template bool operator!= (const Block< 1, Frame::Inertial > &lhs, const Block< 1, Frame::Inertial > &rhs) noexcept
template bool operator!= (const Block< 2, Frame::Inertial > &lhs, const Block< 2, Frame::Inertial > &rhs) noexcept
template bool operator!= (const Block< 3, Frame::Inertial > &lhs, const Block< 3, Frame::Inertial > &rhs) noexcept
Function Documentation
operator!=() [1/7]
template<size_t VolumeDim, typename TargetFrame > bool operator!= (const Block< VolumeDim, TargetFrame > & lhs, const Block< VolumeDim, TargetFrame > & rhs) noexcept
References operator!=(), operator<<(), and operator==().
Referenced by Block< VolumeDim, TargetFrame >::external_boundaries(), and operator!=().
operator!=() [2/7]
template bool operator!= (const Block< 1, Frame::Grid > & lhs, const Block< 1, Frame::Grid > & rhs) noexcept
operator!=() [3/7]
template bool operator!= (const Block< 2, Frame::Grid > & lhs, const Block< 2, Frame::Grid > & rhs) noexcept
operator!=() [4/7]
template bool operator!= (const Block< 3, Frame::Grid > & lhs, const Block< 3, Frame::Grid > & rhs) noexcept
operator!=() [5/7]
template bool operator!= (const Block< 1, Frame::Inertial > & lhs, const Block< 1, Frame::Inertial > & rhs) noexcept
operator!=() [6/7]
template bool operator!= (const Block< 2, Frame::Inertial > & lhs, const Block< 2, Frame::Inertial > & rhs) noexcept
operator!=() [7/7]
template bool operator!= (const Block< 3, Frame::Inertial > & lhs, const Block< 3, Frame::Inertial > & rhs) noexcept
operator<<() [1/7]
template<size_t VolumeDim, typename TargetFrame > std::ostream& operator<< (std::ostream & os, const Block< VolumeDim, TargetFrame > & block)
References Block< VolumeDim, TargetFrame >::external_boundaries(), Block< VolumeDim, TargetFrame >::id(), and Block< VolumeDim, TargetFrame >::neighbors().
Referenced by Block< VolumeDim, TargetFrame >::external_boundaries(), and operator!=().
operator<<() [2/7]
template std::ostream& operator<< (std::ostream & os, const Block< 1, Frame::Grid > & block)
operator<<() [3/7]
template std::ostream& operator<< (std::ostream & os, const Block< 2, Frame::Grid > & block)
operator<<() [4/7]
template std::ostream& operator<< (std::ostream & os, const Block< 3, Frame::Grid > & block)
operator<<() [5/7]
template std::ostream& operator<< (std::ostream & os, const Block< 1, Frame::Inertial > & block)
operator<<() [6/7]
template std::ostream& operator<< (std::ostream & os, const Block< 2, Frame::Inertial > & block)
operator<<() [7/7]
template std::ostream& operator<< (std::ostream & os, const Block< 3, Frame::Inertial > & block)
operator==() [1/7]
template<size_t VolumeDim, typename TargetFrame > bool operator== (const Block< VolumeDim, TargetFrame > & lhs, const Block< VolumeDim, TargetFrame > & rhs) noexcept
Referenced by Block< VolumeDim, TargetFrame >::external_boundaries(), and operator!=().
operator==() [2/7]
template bool operator== (const Block< 1, Frame::Grid > & lhs, const Block< 1, Frame::Grid > & rhs) noexcept
operator==() [3/7]
template bool operator== (const Block< 2, Frame::Grid > & lhs, const Block< 2, Frame::Grid > & rhs) noexcept
operator==() [4/7]
template bool operator== (const Block< 3, Frame::Grid > & lhs, const Block< 3, Frame::Grid > & rhs) noexcept
operator==() [5/7]
template bool operator== (const Block< 1, Frame::Inertial > & lhs, const Block< 1, Frame::Inertial > & rhs) noexcept
operator==() [6/7]
template bool operator== (const Block< 2, Frame::Inertial > & lhs, const Block< 2, Frame::Inertial > & rhs) noexcept
operator==() [7/7]
template bool operator== (const Block< 3, Frame::Inertial > & lhs, const Block< 3, Frame::Inertial > & rhs) noexcept