SpECTRE: DataVector Class Reference
DataVector Class Reference
Data Structures
A class for storing data on a mesh.
#include <DataVector.hpp>
Public Types
using value_type = double
using allocator_type = std::allocator< value_type >
using size_type = size_t
using difference_type = std::ptrdiff_t
using ElementType = double
Public Member Functions
DataVector (size_t size, double value=std::numeric_limits< double >::signaling_NaN())
Create with the given size and value.
DataVector (double *start, size_t size)
Create a non-owning DataVector that points to start
DataVector (std::initializer_list< double > list)
Create from an initializer list.
DataVector ()=default
Empty DataVector.
size_t size () const noexcept
Number of values stored.
bool is_owning () const noexcept
Returns true if the class owns the data.
void pup (PUP::er &p) noexcept
Serialization for Charm++.
void set_data_ref (gsl::not_null< DataVector *> rhs) noexcept
Set the DataVector to be a reference to another DataVector object.
void set_data_ref (double *start, size_t size) noexcept
Set the DataVector to be a reference to another DataVector object.
double & operator[] (const size_type i) noexcept
Access ith element.
const double & operator[] (const size_type i) const noexcept
Access ith element.
double * data () noexcept
Access to the pointer.
const double * data () const noexcept
Access to the pointer.
decltype(auto) begin () noexcept
Returns iterator to beginning of data.
decltype(auto) begin () const noexcept
Returns iterator to beginning of data.
decltype(auto) end () noexcept
Returns iterator to end of data.
decltype(auto) end () const noexcept
Returns iterator to end of data.
DataVector & operator= (const double &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
DataVector & operator+= (const DataVector &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
DataVector & operator+= (const blaze::Vector< VT, VF > &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
DataVector & operator+= (const double &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
DataVector & operator-= (const DataVector &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
DataVector & operator-= (const blaze::Vector< VT, VF > &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
DataVector & operator-= (const double &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
DataVector & operator*= (const DataVector &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
DataVector & operator*= (const blaze::Vector< VT, VF > &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
DataVector & operator*= (const double &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
DataVector & operator/= (const DataVector &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
DataVector & operator/= (const blaze::Vector< VT, VF > &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
DataVector & operator/= (const double &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator+ (const DataVector &lhs, const DataVector &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
decltype(auto) friend operator+ (const blaze::Vector< VT, VF > &lhs, const DataVector &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
decltype(auto) friend operator+ (const DataVector &lhs, const blaze::Vector< VT, VF > &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator+ (const DataVector &lhs, const double &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator+ (const double &lhs, const DataVector &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator- (const DataVector &lhs, const DataVector &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
decltype(auto) friend operator- (const blaze::Vector< VT, VF > &lhs, const DataVector &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
decltype(auto) friend operator- (const DataVector &lhs, const blaze::Vector< VT, VF > &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator- (const DataVector &lhs, const double &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator- (const double &lhs, const DataVector &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator- (const DataVector &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator* (const DataVector &lhs, const double &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator* (const double &lhs, const DataVector &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator* (const DataVector &lhs, const DataVector &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
decltype(auto) friend operator* (const blaze::Vector< VT, VF > &lhs, const DataVector &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
decltype(auto) friend operator* (const DataVector &lhs, const blaze::Vector< VT, VF > &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator/ (const double &lhs, const DataVector &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator/ (const DataVector &lhs, const double &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator/ (const DataVector &lhs, const DataVector &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
decltype(auto) friend operator/ (const blaze::Vector< VT, VF > &lhs, const DataVector &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
decltype(auto) friend operator/ (const DataVector &lhs, const blaze::Vector< VT, VF > &rhs) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend min (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend max (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend abs (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend sqrt (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend invsqrt (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend cbrt (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend invcbrt (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend pow (const DataVector &t, const double exponent) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend exp (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend exp2 (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend exp10 (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend log (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend log2 (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend log10 (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend sin (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend cos (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend tan (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend asin (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend acos (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend atan (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend atan2 (const DataVector &y, const DataVector &x) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend sinh (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend cosh (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend tanh (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend asinh (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend acosh (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend atanh (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend erf (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend erfc (const DataVector &t) noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
Detailed Description
A class for storing data on a mesh.
A Data holds an array of contiguous data and can be either owning (the array is deleted when the Data goes out of scope) or non-owning, meaning it just has a pointer to an array.
Member Typedef Documentation
allocator_type
using DataVector::allocator_type = std::allocator<value_type>
difference_type
using DataVector::difference_type = std::ptrdiff_t
ElementType
using DataVector::ElementType = double
size_type
using DataVector::size_type = size_t
value_type
using DataVector::value_type = double
Constructor & Destructor Documentation
DataVector() [1/4]
DataVector::DataVector (size_t size, double value = std::numeric_limits<double>::signaling_NaN()) explicit
Create with the given size and value.
Parameters
size number of values
value the value to initialize each element.
DataVector() [2/4]
DataVector::DataVector (double * start, size_t size)
Create a non-owning DataVector that points to start
References ASSERT, begin(), DataVector(), end(), is_owning(), operator=(), and size().
DataVector() [3/4]
DataVector::DataVector (std::initializer_list< double > list)
Create from an initializer list.
DataVector() [4/4]
DataVector::DataVector () default
Empty DataVector.
Referenced by DataVector(), and operator-=().
Member Function Documentation
abs()
decltype(auto) friend DataVector::abs (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
acos()
decltype(auto) friend DataVector::acos (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
acosh()
decltype(auto) friend DataVector::acosh (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
asin()
decltype(auto) friend DataVector::asin (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
asinh()
decltype(auto) friend DataVector::asinh (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
atan()
decltype(auto) friend DataVector::atan (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
atan2()
decltype(auto) friend DataVector::atan2 (const DataVector & y, const DataVector & x) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
atanh()
decltype(auto) friend DataVector::atanh (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
begin() [1/2]
decltype(auto) DataVector::begin () inline noexcept
Returns iterator to beginning of data.
References begin().
Referenced by begin(), DataVector(), and operator==().
begin() [2/2]
decltype(auto) DataVector::begin () const inline noexcept
Returns iterator to beginning of data.
References begin().
cbrt()
decltype(auto) friend DataVector::cbrt (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
cos()
decltype(auto) friend DataVector::cos (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
cosh()
decltype(auto) friend DataVector::cosh (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
data() [1/2]
double* DataVector::data () inline noexcept
Access to the pointer.
References data().
Referenced by data(), linearize(), h5::read_data(), and h5::write_data().
data() [2/2]
const double* DataVector::data () const inline noexcept
Access to the pointer.
References data().
end() [1/2]
decltype(auto) DataVector::end () inline noexcept
Returns iterator to end of data.
References end().
Referenced by DataVector(), end(), and operator==().
end() [2/2]
decltype(auto) DataVector::end () const inline noexcept
Returns iterator to end of data.
References end().
erf()
decltype(auto) friend DataVector::erf (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
erfc()
decltype(auto) friend DataVector::erfc (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References operator!=(), operator<<(), and operator==().
exp()
decltype(auto) friend DataVector::exp (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
exp10()
decltype(auto) friend DataVector::exp10 (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
exp2()
decltype(auto) friend DataVector::exp2 (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
invcbrt()
decltype(auto) friend DataVector::invcbrt (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
invsqrt()
decltype(auto) friend DataVector::invsqrt (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
is_owning()
bool DataVector::is_owning () const inline noexcept
Returns true if the class owns the data.
Referenced by DataVector().
log()
decltype(auto) friend DataVector::log (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
log10()
decltype(auto) friend DataVector::log10 (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
log2()
decltype(auto) friend DataVector::log2 (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
max()
decltype(auto) friend DataVector::max (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
min()
decltype(auto) friend DataVector::min (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator*() [1/5]
decltype(auto) friend DataVector::operator* (const DataVector & lhs, const double & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator*() [2/5]
decltype(auto) friend DataVector::operator* (const double & lhs, const DataVector & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator*() [3/5]
decltype(auto) friend DataVector::operator* (const DataVector & lhs, const DataVector & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator*() [4/5]
template<typename VT , bool VF> decltype(auto) friend DataVector::operator* (const blaze::Vector< VT, VF > & lhs, const DataVector & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator*() [5/5]
template<typename VT , bool VF> decltype(auto) friend DataVector::operator* (const DataVector & lhs, const blaze::Vector< VT, VF > & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator*=() [1/3]
DataVector& DataVector::operator*= (const DataVector & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator*=() [2/3]
template<typename VT , bool VF> DataVector& DataVector::operator*= (const blaze::Vector< VT, VF > & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator*=() [3/3]
DataVector& DataVector::operator*= (const double & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator+() [1/5]
decltype(auto) friend DataVector::operator+ (const DataVector & lhs, const DataVector & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator+() [2/5]
template<typename VT , bool VF> decltype(auto) friend DataVector::operator+ (const blaze::Vector< VT, VF > & lhs, const DataVector & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator+() [3/5]
template<typename VT , bool VF> decltype(auto) friend DataVector::operator+ (const DataVector & lhs, const blaze::Vector< VT, VF > & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator+() [4/5]
decltype(auto) friend DataVector::operator+ (const DataVector & lhs, const double & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator+() [5/5]
decltype(auto) friend DataVector::operator+ (const double & lhs, const DataVector & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator+=() [1/3]
DataVector& DataVector::operator+= (const DataVector & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator+=() [2/3]
template<typename VT , bool VF> DataVector& DataVector::operator+= (const blaze::Vector< VT, VF > & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator+=() [3/3]
DataVector& DataVector::operator+= (const double & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-() [1/6]
decltype(auto) friend DataVector::operator- (const DataVector & lhs, const DataVector & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-() [2/6]
template<typename VT , bool VF> decltype(auto) friend DataVector::operator- (const blaze::Vector< VT, VF > & lhs, const DataVector & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-() [3/6]
template<typename VT , bool VF> decltype(auto) friend DataVector::operator- (const DataVector & lhs, const blaze::Vector< VT, VF > & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-() [4/6]
decltype(auto) friend DataVector::operator- (const DataVector & lhs, const double & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-() [5/6]
decltype(auto) friend DataVector::operator- (const double & lhs, const DataVector & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-() [6/6]
decltype(auto) friend DataVector::operator- (const DataVector & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-=() [1/3]
DataVector& DataVector::operator-= (const DataVector & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-=() [2/3]
template<typename VT , bool VF> DataVector& DataVector::operator-= (const blaze::Vector< VT, VF > & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-=() [3/3]
DataVector& DataVector::operator-= (const double & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator/() [1/5]
decltype(auto) friend DataVector::operator/ (const double & lhs, const DataVector & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator/() [2/5]
decltype(auto) friend DataVector::operator/ (const DataVector & lhs, const double & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator/() [3/5]
decltype(auto) friend DataVector::operator/ (const DataVector & lhs, const DataVector & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator/() [4/5]
template<typename VT , bool VF> decltype(auto) friend DataVector::operator/ (const blaze::Vector< VT, VF > & lhs, const DataVector & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator/() [5/5]
template<typename VT , bool VF> decltype(auto) friend DataVector::operator/ (const DataVector & lhs, const blaze::Vector< VT, VF > & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator/=() [1/3]
DataVector& DataVector::operator/= (const DataVector & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator/=() [2/3]
template<typename VT , bool VF> DataVector& DataVector::operator/= (const blaze::Vector< VT, VF > & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator/=() [3/3]
DataVector& DataVector::operator/= (const double & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator=()
DataVector& DataVector::operator= (const double & rhs) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
Referenced by DataVector(), and operator-=().
operator[]() [1/2]
double& DataVector::operator[] (const size_type i) inline noexcept
Access ith element.
References ASSERT.
operator[]() [2/2]
const double& DataVector::operator[] (const size_type i) const inline noexcept
Access ith element.
References ASSERT.
pow()
decltype(auto) friend DataVector::pow (const DataVector & t, const double exponent) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References pow().
pup()
void DataVector::pup (PUP::er & p) noexcept
Serialization for Charm++.
set_data_ref() [1/2]
void DataVector::set_data_ref (gsl::not_null< DataVector *> rhs) inline noexcept
Set the DataVector to be a reference to another DataVector object.
set_data_ref() [2/2]
void DataVector::set_data_ref (double * start, size_t size) inline noexcept
Set the DataVector to be a reference to another DataVector object.
sin()
decltype(auto) friend DataVector::sin (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
sinh()
decltype(auto) friend DataVector::sinh (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
size()
size_t DataVector::size () const inline noexcept
Number of values stored.
Referenced by MakeWithValueImpls::MakeWithValueImpl< Variables< TagList >, DataVector >::apply(), MakeWithValueImpls::MakeWithValueImpl< Tensor< DataVector, Structure... >, DataVector >::apply(), MakeWithValueImpls::MakeWithValueImpl< R, T >::apply(), DataVector(), divide_by(), and operator==().
sqrt()
decltype(auto) friend DataVector::sqrt (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
tan()
decltype(auto) friend DataVector::tan (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
tanh()
decltype(auto) friend DataVector::tanh (const DataVector & t) inline noexcept
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
The documentation for this class was generated from the following files:
src/DataStructures/DataVector.hpp
src/DataStructures/DataVector.cpp