SpECTRE: Parallel::Main< Metavariables > Class Template Reference
Parallel::Main< Metavariables > Class Template Reference
Parallelization
The main function of a Charm++ executable.
#include <Main.hpp>
Public Types
using component_list = typename Metavariables::component_list
using const_global_cache_tags = typename ConstGlobalCache< Metavariables >::tag_list
Public Member Functions
Main (CkArgMsg *msg) noexcept
Main (CkMigrateMessage *)
void initialize () noexcept
Initialize the parallel_components.
void execute_next_phase () noexcept
Determine the next phase of the simulation and execute it.
Detailed Description
template<typename Metavariables>
class Parallel::Main< Metavariables >
The main function of a Charm++ executable.
Metavariables must define the following:
help [c string describing the program]
component_list [typelist of ParallelComponents]
phase [enum class listing phases of the executable]
determine_next_phase [function that determines the next phase of the executable] and may optionally define the following:
input_file [c string giving default input file name]
ignore_unrecognized_command_line_options [bool, defaults to false]
Each ParallelComponent in Metavariables::component_list must define the following functions:
const_global_cache_tag_list [typelist of tags of constant data]
options [typelist of option tags for data to be passed to initialize]
initialize
execute_next_global_actions
The phases in Metavariables::Phase must include Initialization (the initial phase) and Exit (the final phase)
Member Typedef Documentation
component_list
template<typename Metavariables > using Parallel::Main< Metavariables >::component_list = typename Metavariables::component_list
const_global_cache_tags
template<typename Metavariables > using Parallel::Main< Metavariables >::const_global_cache_tags = typename ConstGlobalCache<Metavariables>::tag_list
Constructor & Destructor Documentation
Main() [1/2]
template<typename Metavariables > Parallel::Main< Metavariables >::Main (CkArgMsg * msg) explicit noexcept
References ERROR, Parallel::exit(), tuples::get(), Options< OptionList >::help(), cpp17::is_same_v, make_overloader(), Options< OptionList >::parse(), Options< OptionList >::parse_file(), Informer::print_startup_info(), Parallel::printf(), and Parallel::value.
Main() [2/2]
template<typename Metavariables > Parallel::Main< Metavariables >::Main (CkMigrateMessage *) inline explicit
References Parallel::Main< Metavariables >::execute_next_phase(), and Parallel::Main< Metavariables >::initialize().
Member Function Documentation
execute_next_phase()
template<typename Metavariables > void Parallel::Main< Metavariables >::execute_next_phase () noexcept
Determine the next phase of the simulation and execute it.
References Parallel::exit(), and Informer::print_exit_info().
Referenced by Parallel::Main< Metavariables >::Main().
initialize()
template<typename Metavariables > void Parallel::Main< Metavariables >::initialize () noexcept
Initialize the parallel_components.
Referenced by Parallel::Main< Metavariables >::Main().
The documentation for this class was generated from the following file:
src/Parallel/Main.hpp