SpECTRE: CoordinateMap< SourceFrame, TargetFrame, Maps > Class Template Reference
CoordinateMap< SourceFrame, TargetFrame, Maps > Class Template Reference
Coordinate Maps
A coordinate map or composition of coordinate maps.
#include <CoordinateMap.hpp>
Public Types
using source_frame = SourceFrame
using target_frame = TargetFrame
using maps_list = tmpl::list< Maps... >
Public Member Functions
CoordinateMap ()=default
Used for Charm++ serialization.
CoordinateMap (const CoordinateMap &)=default
CoordinateMap & operator= (const CoordinateMap &)=default
CoordinateMap (CoordinateMap &&)=default
CoordinateMap & operator= (CoordinateMap &&)=default
~CoordinateMap () override=default
constexpr CoordinateMap (Maps... maps)
std::unique_ptr< CoordinateMapBase< SourceFrame, TargetFrame, dim > > get_clone () const override
WRAPPED_PUPable_decl_base_template (SINGLE_ARG(CoordinateMapBase< SourceFrame, TargetFrame, dim >), CoordinateMap)
CoordinateMap (CkMigrateMessage *)
void pup (PUP::er &p) override
template<typename T >
constexpr tnsr::I< T, CoordinateMap< SourceFrame, TargetFrame, Maps... >::dim, TargetFrame > call_impl (const tnsr::I< T, dim, SourceFrame > &source_point) const
template<typename T >
constexpr tnsr::I< T, CoordinateMap< SourceFrame, TargetFrame, Maps... >::dim, SourceFrame > inverse_impl (const tnsr::I< T, dim, TargetFrame > &target_point) const
template<typename T >
constexpr auto inv_jacobian_impl (const tnsr::I< T, dim, SourceFrame > &source_point) const -> Tensor< T, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< dim, UpLo::Up, SourceFrame >, SpatialIndex< dim, UpLo::Lo, TargetFrame >>>
template<typename T >
constexpr auto jacobian_impl (const tnsr::I< T, dim, SourceFrame > &source_point) const -> Tensor< T, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< dim, UpLo::Up, TargetFrame >, SpatialIndex< dim, UpLo::Lo, SourceFrame >>>
constexpr tnsr::I< double, dim, TargetFrame > operator() (const tnsr::I< double, dim, SourceFrame > &source_point) const override
Apply the Maps... to the point(s) source_point
constexpr tnsr::I< DataVector, dim, TargetFrame > operator() (const tnsr::I< DataVector, dim, SourceFrame > &source_point) const override
Apply the Maps... to the point(s) source_point
constexpr tnsr::I< double, dim, SourceFrame > inverse (const tnsr::I< double, dim, TargetFrame > &target_point) const override
Apply the inverse Maps... to the point(s) target_point
constexpr tnsr::I< DataVector, dim, SourceFrame > inverse (const tnsr::I< DataVector, dim, TargetFrame > &target_point) const override
Apply the inverse Maps... to the point(s) target_point
constexpr Tensor< double, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< dim, UpLo::Up, SourceFrame >, SpatialIndex< dim, UpLo::Lo, TargetFrame > > > inv_jacobian (const tnsr::I< double, dim, SourceFrame > &source_point) const override
Compute the inverse Jacobian of the Maps... at the point(s) source_point
constexpr Tensor< DataVector, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< dim, UpLo::Up, SourceFrame >, SpatialIndex< dim, UpLo::Lo, TargetFrame > > > inv_jacobian (const tnsr::I< DataVector, dim, SourceFrame > &source_point) const override
Compute the inverse Jacobian of the Maps... at the point(s) source_point
constexpr Tensor< double, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< dim, UpLo::Up, TargetFrame >, SpatialIndex< dim, UpLo::Lo, SourceFrame > > > jacobian (const tnsr::I< double, dim, SourceFrame > &source_point) const override
Compute the Jacobian of the Maps... at the point(s) source_point
constexpr Tensor< DataVector, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< dim, UpLo::Up, TargetFrame >, SpatialIndex< dim, UpLo::Lo, SourceFrame > > > jacobian (const tnsr::I< DataVector, dim, SourceFrame > &source_point) const override
Compute the Jacobian of the Maps... at the point(s) source_point
Public Member Functions inherited from CoordinateMapBase< SourceFrame, TargetFrame, CoordinateMaps::map_dim< Maps... > >
WRAPPED_PUPable_abstract (CoordinateMapBase)
CoordinateMapBase ()=default
CoordinateMapBase (const CoordinateMapBase &)=default
CoordinateMapBase (CoordinateMapBase &&)=default
CoordinateMapBase & operator= (const CoordinateMapBase &)=default
CoordinateMapBase & operator= (CoordinateMapBase &&)=default
~CoordinateMapBase () override=default
virtual tnsr::I< double, Dim, TargetFrame > operator() (const tnsr::I< double, Dim, SourceFrame > &source_point) const=0
Apply the Maps to the point(s) source_point
virtual tnsr::I< DataVector, Dim, TargetFrame > operator() (const tnsr::I< DataVector, Dim, SourceFrame > &source_point) const=0
Apply the Maps to the point(s) source_point
virtual tnsr::I< double, Dim, SourceFrame > inverse (const tnsr::I< double, Dim, TargetFrame > &target_point) const=0
Apply the inverse Maps to the point(s) target_point
virtual tnsr::I< DataVector, Dim, SourceFrame > inverse (const tnsr::I< DataVector, Dim, TargetFrame > &target_point) const=0
Apply the inverse Maps to the point(s) target_point
virtual Tensor< double, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< Dim, UpLo::Up, SourceFrame >, SpatialIndex< Dim, UpLo::Lo, TargetFrame > > > inv_jacobian (const tnsr::I< double, Dim, SourceFrame > &source_point) const=0
Compute the inverse Jacobian of the Maps at the point(s) source_point
virtual Tensor< DataVector, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< Dim, UpLo::Up, SourceFrame >, SpatialIndex< Dim, UpLo::Lo, TargetFrame > > > inv_jacobian (const tnsr::I< DataVector, Dim, SourceFrame > &source_point) const=0
Compute the inverse Jacobian of the Maps at the point(s) source_point
virtual Tensor< double, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< Dim, UpLo::Up, TargetFrame >, SpatialIndex< Dim, UpLo::Lo, SourceFrame > > > jacobian (const tnsr::I< double, Dim, SourceFrame > &source_point) const=0
Compute the Jacobian of the Maps at the point(s) source_point
virtual Tensor< DataVector, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< Dim, UpLo::Up, TargetFrame >, SpatialIndex< Dim, UpLo::Lo, SourceFrame > > > jacobian (const tnsr::I< DataVector, Dim, SourceFrame > &source_point) const=0
Compute the Jacobian of the Maps at the point(s) source_point
Static Public Attributes
static constexpr size_t dim = CoordinateMaps::map_dim<Maps...>
Friends
bool operator== (const CoordinateMap &lhs, const CoordinateMap &rhs) noexcept
Detailed Description
template<typename SourceFrame, typename TargetFrame, typename... Maps>
class CoordinateMap< SourceFrame, TargetFrame, Maps >
A coordinate map or composition of coordinate maps.
Maps coordinates from the SourceFrame to the TargetFrame using the coordinate maps Maps.... The individual maps are applied left to right from the source to the target Frame. The inverse map, as well as Jacobian and inverse Jacobian are also provided. The CoordinateMap class must be used even if just wrapping a single coordinate map. It is designed to be an extremely minimal interface to the underlying coordinate maps. For a list of all coordinate maps see the CoordinateMaps group or namespace.
Each coordinate map must contain a static constexpr size_t dim variable that is equal to the dimensionality of the map. The Coordinatemap class contains a member static constexpr size_t dim, a type alias source_frame, a type alias target_frame and typelist of theMaps...`.
Member Typedef Documentation
maps_list
template<typename SourceFrame, typename TargetFrame, typename... Maps> using CoordinateMap< SourceFrame, TargetFrame, Maps >::maps_list = tmpl::list<Maps...>
source_frame
template<typename SourceFrame, typename TargetFrame, typename... Maps> using CoordinateMap< SourceFrame, TargetFrame, Maps >::source_frame = SourceFrame
target_frame
template<typename SourceFrame, typename TargetFrame, typename... Maps> using CoordinateMap< SourceFrame, TargetFrame, Maps >::target_frame = TargetFrame
Constructor & Destructor Documentation
CoordinateMap() [1/5]
template<typename SourceFrame, typename TargetFrame, typename... Maps> CoordinateMap< SourceFrame, TargetFrame, Maps >::CoordinateMap () default
Used for Charm++ serialization.
CoordinateMap() [2/5]
template<typename SourceFrame, typename TargetFrame, typename... Maps> CoordinateMap< SourceFrame, TargetFrame, Maps >::CoordinateMap (const CoordinateMap< SourceFrame, TargetFrame, Maps > &) default
CoordinateMap() [3/5]
template<typename SourceFrame, typename TargetFrame, typename... Maps> CoordinateMap< SourceFrame, TargetFrame, Maps >::CoordinateMap (CoordinateMap< SourceFrame, TargetFrame, Maps > &&) default
~CoordinateMap()
template<typename SourceFrame, typename TargetFrame, typename... Maps> CoordinateMap< SourceFrame, TargetFrame, Maps >::~CoordinateMap () override default
CoordinateMap() [4/5]
template<typename SourceFrame , typename TargetFrame , typename... Maps> constexpr CoordinateMap< SourceFrame, TargetFrame, Maps >::CoordinateMap (Maps... maps) explicit
References CoordinateMap< SourceFrame, TargetFrame, Maps >::dim, and SPECTRE_ALWAYS_INLINE.
CoordinateMap() [5/5]
template<typename SourceFrame, typename TargetFrame, typename... Maps> CoordinateMap< SourceFrame, TargetFrame, Maps >::CoordinateMap (CkMigrateMessage *) inline explicit
Member Function Documentation
call_impl()
template<typename SourceFrame, typename TargetFrame, typename... Maps> template<typename T > constexpr tnsr::I< T, CoordinateMap<SourceFrame, TargetFrame, Maps...>::dim, TargetFrame> CoordinateMap< SourceFrame, TargetFrame, Maps >::call_impl (const tnsr::I< T, dim, SourceFrame > & source_point) const
References CoordinateMap< SourceFrame, TargetFrame, Maps >::dim, SPECTRE_ALWAYS_INLINE, and tuple_fold().
get_clone()
template<typename SourceFrame, typename TargetFrame, typename... Maps> std::unique_ptr<CoordinateMapBase<SourceFrame, TargetFrame, dim> > CoordinateMap< SourceFrame, TargetFrame, Maps >::get_clone () const inline override virtual
Implements CoordinateMapBase< SourceFrame, TargetFrame, CoordinateMaps::map_dim< Maps... > >.
inv_jacobian() [1/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> constexpr Tensor<double, tmpl::integral_list<std::int32_t, 2, 1>, index_list<SpatialIndex<dim, UpLo::Up, SourceFrame>, SpatialIndex<dim, UpLo::Lo, TargetFrame> > > CoordinateMap< SourceFrame, TargetFrame, Maps >::inv_jacobian (const tnsr::I< double, dim, SourceFrame > & source_point) const inline override
Compute the inverse Jacobian of the Maps... at the point(s) source_point
Referenced by CkRegisterMainModule().
inv_jacobian() [2/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> constexpr Tensor<DataVector, tmpl::integral_list<std::int32_t, 2, 1>, index_list<SpatialIndex<dim, UpLo::Up, SourceFrame>, SpatialIndex<dim, UpLo::Lo, TargetFrame> > > CoordinateMap< SourceFrame, TargetFrame, Maps >::inv_jacobian (const tnsr::I< DataVector, dim, SourceFrame > & source_point) const inline override
Compute the inverse Jacobian of the Maps... at the point(s) source_point
inv_jacobian_impl()
template<typename SourceFrame, typename TargetFrame, typename... Maps> template<typename T > constexpr auto CoordinateMap< SourceFrame, TargetFrame, Maps >::inv_jacobian_impl (const tnsr::I< T, dim, SourceFrame > & source_point) const -> Tensor<T, tmpl::integral_list<std::int32_t, 2, 1>, index_list<SpatialIndex<dim, UpLo::Up, SourceFrame>, SpatialIndex<dim, UpLo::Lo, TargetFrame>>>
References LIKELY, tuple_transform(), and Parallel::value.
inverse() [1/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> constexpr tnsr::I<double, dim, SourceFrame> CoordinateMap< SourceFrame, TargetFrame, Maps >::inverse (const tnsr::I< double, dim, TargetFrame > & target_point) const inline override
Apply the inverse Maps... to the point(s) target_point
inverse() [2/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> constexpr tnsr::I<DataVector, dim, SourceFrame> CoordinateMap< SourceFrame, TargetFrame, Maps >::inverse (const tnsr::I< DataVector, dim, TargetFrame > & target_point) const inline override
Apply the inverse Maps... to the point(s) target_point
inverse_impl()
template<typename SourceFrame, typename TargetFrame, typename... Maps> template<typename T > constexpr tnsr::I< T, CoordinateMap<SourceFrame, TargetFrame, Maps...>::dim, SourceFrame> CoordinateMap< SourceFrame, TargetFrame, Maps >::inverse_impl (const tnsr::I< T, dim, TargetFrame > & target_point) const
References SPECTRE_ALWAYS_INLINE.
jacobian() [1/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> constexpr Tensor<double, tmpl::integral_list<std::int32_t, 2, 1>, index_list<SpatialIndex<dim, UpLo::Up, TargetFrame>, SpatialIndex<dim, UpLo::Lo, SourceFrame> > > CoordinateMap< SourceFrame, TargetFrame, Maps >::jacobian (const tnsr::I< double, dim, SourceFrame > & source_point) const inline override
Compute the Jacobian of the Maps... at the point(s) source_point
jacobian() [2/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> constexpr Tensor<DataVector, tmpl::integral_list<std::int32_t, 2, 1>, index_list<SpatialIndex<dim, UpLo::Up, TargetFrame>, SpatialIndex<dim, UpLo::Lo, SourceFrame> > > CoordinateMap< SourceFrame, TargetFrame, Maps >::jacobian (const tnsr::I< DataVector, dim, SourceFrame > & source_point) const inline override
Compute the Jacobian of the Maps... at the point(s) source_point
References WRAPPED_PUPable_decl_base_template.
jacobian_impl()
template<typename SourceFrame, typename TargetFrame, typename... Maps> template<typename T > constexpr auto CoordinateMap< SourceFrame, TargetFrame, Maps >::jacobian_impl (const tnsr::I< T, dim, SourceFrame > & source_point) const -> Tensor<T, tmpl::integral_list<std::int32_t, 2, 1>, index_list<SpatialIndex<dim, UpLo::Up, TargetFrame>, SpatialIndex<dim, UpLo::Lo, SourceFrame>>>
References LIKELY, tuple_transform(), and Parallel::value.
operator()() [1/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> constexpr tnsr::I<double, dim, TargetFrame> CoordinateMap< SourceFrame, TargetFrame, Maps >::operator() (const tnsr::I< double, dim, SourceFrame > & source_point) const inline override
Apply the Maps... to the point(s) source_point
operator()() [2/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> constexpr tnsr::I<DataVector, dim, TargetFrame> CoordinateMap< SourceFrame, TargetFrame, Maps >::operator() (const tnsr::I< DataVector, dim, SourceFrame > & source_point) const inline override
Apply the Maps... to the point(s) source_point
operator=() [1/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> CoordinateMap& CoordinateMap< SourceFrame, TargetFrame, Maps >::operator= (const CoordinateMap< SourceFrame, TargetFrame, Maps > &) default
operator=() [2/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> CoordinateMap& CoordinateMap< SourceFrame, TargetFrame, Maps >::operator= (CoordinateMap< SourceFrame, TargetFrame, Maps > &&) default
pup()
template<typename SourceFrame, typename TargetFrame, typename... Maps> void CoordinateMap< SourceFrame, TargetFrame, Maps >::pup (PUP::er & p) inline override
WRAPPED_PUPable_decl_base_template()
template<typename SourceFrame, typename TargetFrame, typename... Maps> CoordinateMap< SourceFrame, TargetFrame, Maps >::WRAPPED_PUPable_decl_base_template (SINGLE_ARG(CoordinateMapBase< SourceFrame, TargetFrame, dim >) , CoordinateMap< SourceFrame, TargetFrame, Maps >)
Friends And Related Function Documentation
operator==
template<typename SourceFrame, typename TargetFrame, typename... Maps> bool operator== (const CoordinateMap< SourceFrame, TargetFrame, Maps > & lhs, const CoordinateMap< SourceFrame, TargetFrame, Maps > & rhs) friend
Member Data Documentation
dim
template<typename SourceFrame, typename TargetFrame, typename... Maps> constexpr size_t CoordinateMap< SourceFrame, TargetFrame, Maps >::dim = CoordinateMaps::map_dim<Maps...> static
Referenced by CoordinateMap< SourceFrame, TargetFrame, Maps >::call_impl(), CoordinateMap< SourceFrame, TargetFrame, Maps >::CoordinateMap(), and make_coordinate_map().
The documentation for this class was generated from the following file:
src/Domain/CoordinateMaps/CoordinateMap.hpp