SpECTRE: Option Class Reference
Option Class Reference
Option Parsing
The type that options are passed around as. Contains YAML node data and an OptionContext.
#include <ParseOptions.hpp>
Public Member Functions
Option (YAML::Node node, OptionContext context=OptionContext()) noexcept
NOTE: This constructor overwrites the mark data in the supplied context with the one from the node.
Option (OptionContext context) noexcept
const YAML::Node & node () const noexcept
const OptionContext & context () const noexcept
void append_context (const std::string &context) noexcept
Append a line to the contained context.
void set_node (YAML::Node node) noexcept
Sets the node and updates the context's mark to correspond to it.
template<typename T >
T parse_as () const
Convert to an object of type T.
Detailed Description
The type that options are passed around as. Contains YAML node data and an OptionContext.
Constructor & Destructor Documentation
Option() [1/2]
Option::Option (YAML::Node node, OptionContext context = OptionContext()) inline explicit noexcept
NOTE: This constructor overwrites the mark data in the supplied context with the one from the node.
References OptionContext::column, and OptionContext::line.
Option() [2/2]
Option::Option (OptionContext context) inline explicit noexcept
Member Function Documentation
append_context()
void Option::append_context (const std::string & context) inline noexcept
Append a line to the contained context.
References OptionContext::append(), and context().
Referenced by Options< option_list >::get().
context()
const OptionContext& Option::context () const inline noexcept
Referenced by append_context(), create_from_yaml< T >::create(), Options< option_list >::help(), and Options< option_list >::parse().
node()
const YAML::Node& Option::node () const inline noexcept
Referenced by Options< option_list >::parse(), and parse_as().
parse_as()
template<typename T > T Option::parse_as () const
Convert to an object of type T.
References node().
Referenced by create_from_yaml< T >::create(), and set_node().
set_node()
void Option::set_node (YAML::Node node) inline noexcept
Sets the node and updates the context's mark to correspond to it.
References OptionContext::column, OptionContext::line, and parse_as().
The documentation for this class was generated from the following file:
src/Options/ParseOptions.hpp