SpECTRE: Domain< VolumeDim, TargetFrame > Class Template Reference
Domain< VolumeDim, TargetFrame > Class Template Reference
Computational Domain
A wrapper around a vector of Blocks that represent the computational domain.
#include <Domain.hpp>
Public Member Functions
Domain (std::vector< Block< VolumeDim, TargetFrame >> blocks)
Domain (std::vector< std::unique_ptr< CoordinateMapBase< Frame::Logical, TargetFrame, VolumeDim >>> maps, const std::vector< std::array< size_t, two_to_the(VolumeDim)>> &corners_of_all_blocks, const std::vector< PairOfFaces > &identifications={})
Domain ()=default
~Domain ()=default
Domain (const Domain &)=delete
Domain (Domain &&)=default
Domain< VolumeDim, TargetFrame > & operator= (const Domain< VolumeDim, TargetFrame > &)=delete
Domain< VolumeDim, TargetFrame > & operator= (Domain< VolumeDim, TargetFrame > &&)=default
const std::vector< Block< VolumeDim, TargetFrame > > & blocks () const
void pup (PUP::er &p)
Detailed Description
template<size_t VolumeDim, typename TargetFrame>
class Domain< VolumeDim, TargetFrame >
A wrapper around a vector of Blocks that represent the computational domain.
Constructor & Destructor Documentation
Domain() [1/5]
template<size_t VolumeDim, typename TargetFrame > Domain< VolumeDim, TargetFrame >::Domain (std::vector< Block< VolumeDim, TargetFrame >> blocks) explicit
Domain() [2/5]
template<size_t VolumeDim, typename TargetFrame > Domain< VolumeDim, TargetFrame >::Domain (std::vector< std::unique_ptr< CoordinateMapBase< Frame::Logical, TargetFrame, VolumeDim >>> maps, const std::vector< std::array< size_t, two_to_the(VolumeDim)>> & corners_of_all_blocks, const std::vector< PairOfFaces > & identifications = {})
Create a Domain using a corner numbering scheme to encode the Orientations, with an optional parameter that encodes periodic boundary conditions.
Details
Each element of corners_of_all_blocks contains the corner numbering of that block's corners according to the global corner number scheme. The details of the corner numbering scheme are described in the tutorial. identifications is for imposing periodic boundary conditions on the domain. To identify two faces, identifications should contain the corners corresponding to the first face as its first element, and the second face as its second. If periodic boundary conditions need be set up in more than one direction, the corners corresponding to the 3rd and 4th elements of identifications will be identified as the same, and the 5th and 6th elements identified if necessary.
Requires: maps.size() == corners_of_all_blocks.size(), and identifications.size() is even.
Domain() [3/5]
template<size_t VolumeDim, typename TargetFrame> Domain< VolumeDim, TargetFrame >::Domain () default
~Domain()
template<size_t VolumeDim, typename TargetFrame> Domain< VolumeDim, TargetFrame >::~Domain () default
Domain() [4/5]
template<size_t VolumeDim, typename TargetFrame> Domain< VolumeDim, TargetFrame >::Domain (const Domain< VolumeDim, TargetFrame > &) delete
Domain() [5/5]
template<size_t VolumeDim, typename TargetFrame> Domain< VolumeDim, TargetFrame >::Domain (Domain< VolumeDim, TargetFrame > &&) default
Member Function Documentation
blocks()
template<size_t VolumeDim, typename TargetFrame> const std::vector<Block<VolumeDim, TargetFrame> >& Domain< VolumeDim, TargetFrame >::blocks () const inline
References operator<<(), and Domain< VolumeDim, TargetFrame >::pup().
Referenced by operator<<().
operator=() [1/2]
template<size_t VolumeDim, typename TargetFrame> Domain<VolumeDim, TargetFrame>& Domain< VolumeDim, TargetFrame >::operator= (const Domain< VolumeDim, TargetFrame > &) delete
operator=() [2/2]
template<size_t VolumeDim, typename TargetFrame> Domain<VolumeDim, TargetFrame>& Domain< VolumeDim, TargetFrame >::operator= (Domain< VolumeDim, TargetFrame > &&) default
pup()
template<size_t VolumeDim, typename TargetFrame > void Domain< VolumeDim, TargetFrame >::pup (PUP::er & p)
References operator<<().
Referenced by Domain< VolumeDim, TargetFrame >::blocks().
The documentation for this class was generated from the following files:
src/Domain/Domain.hpp
src/Domain/Domain.cpp