SpECTRE: Tensor< X, Symm, IndexList< Indices... > > Class Template Reference
Tensor< X, Symm, IndexList< Indices... > > Class Template Reference
Tensor
Represents an object with multiple components.
#include <Tensor.hpp>
Public Types
using storage_type = std::array< X, Tensor_detail::Structure< Symm, Indices... >::size()>
The type of the sequence that holds the data.
using type = X
The type that is stored by the Tensor.
using symmetry = Symm
Typelist of the symmetry of the Tensor.
using index_list = typelist< Indices... >
Typelist of the TensorIndexType's that the Tensor has.
template<typename ArgsList >
using TE = TensorExpression< Tensor< X, Symm, tmpl::list< Indices... > >, X, Symm, tmpl::list< Indices... >, ArgsList >
The type of the TensorExpression that would represent this Tensor in a tensor expression.
using value_type = typename storage_type::value_type
using reference = typename storage_type::reference
using const_reference = typename storage_type::const_reference
using iterator = typename storage_type::iterator
using const_iterator = typename storage_type::const_iterator
using pointer = typename storage_type::pointer
using const_pointer = typename storage_type::const_pointer
using reverse_iterator = typename storage_type::reverse_iterator
using const_reverse_iterator = typename storage_type::const_reverse_iterator
Public Member Functions
Tensor ()=default
~Tensor ()=default
Tensor (const Tensor &)=default
Tensor (Tensor &&) noexcept=default
Tensor & operator= (const Tensor &)=default
Tensor & operator= (Tensor &&) noexcept=default
template<size_t NumberOfIndices = sizeof...(Indices), Requires<(NumberOfIndices==1)> = nullptr>
Tensor (storage_type data)
Initialize a Vector with the value in the std::initializer_list.
template<typename... Args>
Tensor (Args &&... args)
Constructor that passes "args" to constructor of X and initializes each component to be the same.
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
const_reverse_iterator crbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator crend () const
std::pair< std::vector< std::string >, std::vector< X > > get_vector_of_data () const
Copy tensor data into an std::vector<X> along with the component names into a std::vector<std::string>
template<typename T >
constexpr reference get (const std::array< T, sizeof...(Indices)> &tensor_index)
Get data entry using an array representing a tensor index.
template<typename T >
constexpr const_reference get (const std::array< T, sizeof...(Indices)> &tensor_index) const
Get data entry using an array representing a tensor index.
template<typename... N>
constexpr reference get (N... n)
Get data entry using a list of integers representing a tensor index.
template<typename... N>
constexpr const_reference get (N... n) const
Get data entry using a list of integers representing a tensor index.
template<int... N>
constexpr reference get ()
Retrieve the index N... by computing the storage index at compile time.
template<int... N>
constexpr const_reference get () const
Retrieve the index N... by computing the storage index at compile time.
template<typename... N, Requires< cpp17::conjunction_v< tt::is_tensor_index< N >... > and tmpl::is_set< N... >::value > = nullptr>
constexpr TE< tmpl::list< N... > > operator() (N...) const
Retrieve a TensorExpression object with the index structure passed in.
template<typename... N, Requires< cpp17::conjunction_v< tt::is_tensor_index< N >... > and not tmpl::is_set< N... >::value > = nullptr>
constexpr auto operator() (N...) const -> decltype(TensorExpressions::fully_contracted< TE, replace_indices< tmpl::list< N... >, repeated< tmpl::list< N... >>>, tmpl::int32_t< 0 >, tmpl::size< repeated< tmpl::list< N... >>>>::apply(*this))
Retrieve a TensorExpression object with the index structure passed in.
constexpr reference operator[] (const size_t storage_index)
Return i'th component of storage vector.
constexpr const_reference operator[] (const size_t storage_index) const
Return i'th component of storage vector.
Static Public Member Functions
static constexpr size_t size () noexcept
Return the number of independent components of the Tensor.
static constexpr size_t rank () noexcept
Returns the rank of the Tensor.
static constexpr size_t index_dim (const size_t i) noexcept
Get dimensionality of i'th tensor index.
template<int I>
static constexpr size_t index_dim () noexcept
Get dimensionality of i'th tensor index.
static constexpr std::array< int, sizeof...(Indices)> symmetries () noexcept
Return an array corresponding to the Symmetry of the Tensor.
static constexpr std::array< IndexType, sizeof...(Indices)> index_types () noexcept
Return array of the IndexType's (spatial or spacetime)
static constexpr std::array< size_t, sizeof...(Indices)> index_dims () noexcept
Return array of dimensionality of each index.
static constexpr std::array< UpLo, sizeof...(Indices)> index_valences () noexcept
Return array of the valence of each index (UpLo)
static constexpr auto index_frames () noexcept
Returns std::tuple of the Frame of each index.
template<typename T = int>
static std::string component_name (const std::array< T, rank()> &tensor_index=std::array< T, rank()>{}, const std::array< std::string, rank()> &axis_labels=make_array< rank()>(std::string("")))
Given a tensor index, get the canonical label associated with the canonical TensorIndexType.
constexpr std::array< size_t, sizeof...(Indices)> get_tensor_index (const const_iterator &iter) const noexcept
Given an iterator or storage index, get the canonical tensor index. For scalars this is defined to be std::array<int, 1>{{0}}.
static constexpr std::array< size_t, sizeof...(Indices)> get_tensor_index (const size_t storage_index) noexcept
Given an iterator or storage index, get the canonical tensor index. For scalars this is defined to be std::array<int, 1>{{0}}.
constexpr size_t multiplicity (const iterator &iter) const noexcept
Given an iterator or storage index, get the multiplicity of an index.
static constexpr size_t multiplicity (const size_t storage_index) noexcept
Given an iterator or storage index, get the multiplicity of an index.
Detailed Description
template<typename X, typename Symm, template< typename... > class IndexList, typename... Indices>
class Tensor< X, Symm, IndexList< Indices... > >
Represents an object with multiple components.
Details
Tensor is a container that represents indexable geometric objects. Each index has its own dimension, valence, and frame and must be either spatial or spacetime. Note that the dimension passed to SpatialIndex and SpacetimeIndex is always the spatial dimension of the index. Tensors with symmetric indices are stored only once and must be of the same type. A list of available type aliases can be found in the tnsr namespace where the adopted conventions are:
Upper case for contravariant or upper indices, lower case for covariant or lower indices.
a, b, c, d are used for spacetime indices while i, j, k, l are used for spatial indices.
Scalar is not inside the tnsr namespace but is used to represent a scalar with no indices.
Example
  Tensor<double> scalar{};
  tnsr::I<double, 3, Frame::Grid> spatial_vector3{};
  tnsr::A<double, 3, Frame::Grid> spacetime_vector3{};
  Tensor<double, Symmetry<1, 2, 2>,
         index_list<SpacetimeIndex<1, UpLo::Lo, Frame::Grid>,
                    SpatialIndex<1, UpLo::Lo, Frame::Grid>,
                    SpatialIndex<1, UpLo::Lo, Frame::Grid>>>
      tensor_1{};
Template Parameters
X the type held
Symm the Symmetry of the indices
IndexList a typelist of TensorIndexType's
Member Typedef Documentation
const_iterator
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> using Tensor< X, Symm, IndexList< Indices... > >::const_iterator = typename storage_type::const_iterator
const_pointer
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> using Tensor< X, Symm, IndexList< Indices... > >::const_pointer = typename storage_type::const_pointer
const_reference
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> using Tensor< X, Symm, IndexList< Indices... > >::const_reference = typename storage_type::const_reference
const_reverse_iterator
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> using Tensor< X, Symm, IndexList< Indices... > >::const_reverse_iterator = typename storage_type::const_reverse_iterator
index_list
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> using Tensor< X, Symm, IndexList< Indices... > >::index_list = typelist<Indices...>
Typelist of the TensorIndexType's that the Tensor has.
iterator
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> using Tensor< X, Symm, IndexList< Indices... > >::iterator = typename storage_type::iterator
pointer
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> using Tensor< X, Symm, IndexList< Indices... > >::pointer = typename storage_type::pointer
reference
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> using Tensor< X, Symm, IndexList< Indices... > >::reference = typename storage_type::reference
reverse_iterator
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> using Tensor< X, Symm, IndexList< Indices... > >::reverse_iterator = typename storage_type::reverse_iterator
storage_type
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> using Tensor< X, Symm, IndexList< Indices... > >::storage_type = std::array<X, Tensor_detail::Structure<Symm, Indices...>::size()>
The type of the sequence that holds the data.
symmetry
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> using Tensor< X, Symm, IndexList< Indices... > >::symmetry = Symm
Typelist of the symmetry of the Tensor.
Details
For a rank-3 tensor symmetric in the last two indices, \(T_{a(bc)}\), the Symmetry is <2, 1, 1>. For a non-symmetric rank-2 tensor the Symmetry is <2, 1>.
TE
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> template<typename ArgsList > using Tensor< X, Symm, IndexList< Indices... > >::TE = TensorExpression<Tensor<X, Symm, tmpl::list<Indices...> >, X, Symm, tmpl::list<Indices...>, ArgsList>
The type of the TensorExpression that would represent this Tensor in a tensor expression.
type
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> using Tensor< X, Symm, IndexList< Indices... > >::type = X
The type that is stored by the Tensor.
value_type
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> using Tensor< X, Symm, IndexList< Indices... > >::value_type = typename storage_type::value_type
Constructor & Destructor Documentation
Tensor() [1/5]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> Tensor< X, Symm, IndexList< Indices... > >::Tensor () default
~Tensor()
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> Tensor< X, Symm, IndexList< Indices... > >::~Tensor () default
Tensor() [2/5]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> Tensor< X, Symm, IndexList< Indices... > >::Tensor (const Tensor< X, Symm, IndexList< Indices... > > &) default
Tensor() [3/5]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> Tensor< X, Symm, IndexList< Indices... > >::Tensor (Tensor< X, Symm, IndexList< Indices... > > &&) default noexcept
Tensor() [4/5]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> template<size_t NumberOfIndices, Requires<(NumberOfIndices==1)> > Tensor< X, Symm, IndexList< Indices... > >::Tensor (storage_type data) explicit
Initialize a Vector with the value in the std::initializer_list.
Example
  tnsr::I<std::vector<double>, 3, Frame::Grid> tensor_std_vector(
      {{{1, 2, 3}, {4, 5, 6}, {7, 8, 9}}});
Parameters
data the values of the individual components of the Vector
References cpp17::disjunction_v.
Tensor() [5/5]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> template<typename... Args> Tensor< X, Symm, IndexList< Indices... > >::Tensor (Args &&... args) explicit
Constructor that passes "args" to constructor of X and initializes each component to be the same.
Member Function Documentation
begin() [1/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> iterator Tensor< X, Symm, IndexList< Indices... > >::begin () inline
begin() [2/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> const_iterator Tensor< X, Symm, IndexList< Indices... > >::begin () const inline
cbegin()
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> const_iterator Tensor< X, Symm, IndexList< Indices... > >::cbegin () const inline
cend()
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> const_iterator Tensor< X, Symm, IndexList< Indices... > >::cend () const inline
component_name()
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> template<typename T = int> static std::string Tensor< X, Symm, IndexList< Indices... > >::component_name (const std::array< T, rank()> & tensor_index = std::array<T, rank()>{}, const std::array< std::string, rank()> & axis_labels = make_array<rank()>(std::string(""))) inline static
Given a tensor index, get the canonical label associated with the canonical TensorIndexType.
crbegin()
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> const_reverse_iterator Tensor< X, Symm, IndexList< Indices... > >::crbegin () const inline
crend()
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> const_reverse_iterator Tensor< X, Symm, IndexList< Indices... > >::crend () const inline
end() [1/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> iterator Tensor< X, Symm, IndexList< Indices... > >::end () inline
end() [2/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> const_iterator Tensor< X, Symm, IndexList< Indices... > >::end () const inline
get() [1/6]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> template<typename T > constexpr reference Tensor< X, Symm, IndexList< Indices... > >::get (const std::array< T, sizeof...(Indices)> & tensor_index) inline
Get data entry using an array representing a tensor index.
Details
Let \(T_{abc}\) be a Tensor. Then get({{0, 2, 1}}) returns the \(T_{0 2 1}\) component.
Parameters
tensor_index the index at which to get the data
References gsl::at().
get() [2/6]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> template<typename T > constexpr const_reference Tensor< X, Symm, IndexList< Indices... > >::get (const std::array< T, sizeof...(Indices)> & tensor_index) const inline
Get data entry using an array representing a tensor index.
Details
Let \(T_{abc}\) be a Tensor. Then get({{0, 2, 1}}) returns the \(T_{0 2 1}\) component.
Parameters
tensor_index the index at which to get the data
References gsl::at().
get() [3/6]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> template<typename... N> constexpr reference Tensor< X, Symm, IndexList< Indices... > >::get (N... n) inline
Get data entry using a list of integers representing a tensor index.
Details
Let \(T_{abc}\) be a Tensor. Then get(0, 2, 1) returns the \(T_{0 2 1}\) component.
Parameters
n the index at which to get the data
References gsl::at().
get() [4/6]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> template<typename... N> constexpr const_reference Tensor< X, Symm, IndexList< Indices... > >::get (N... n) const inline
Get data entry using a list of integers representing a tensor index.
Details
Let \(T_{abc}\) be a Tensor. Then get(0, 2, 1) returns the \(T_{0 2 1}\) component.
Parameters
n the index at which to get the data
References gsl::at().
get() [5/6]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> template<int... N> constexpr reference Tensor< X, Symm, IndexList< Indices... > >::get () inline
Retrieve the index N... by computing the storage index at compile time.
References gsl::at().
get() [6/6]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> template<int... N> constexpr const_reference Tensor< X, Symm, IndexList< Indices... > >::get () const inline
Retrieve the index N... by computing the storage index at compile time.
References gsl::at(), and Parallel::value.
get_tensor_index() [1/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> constexpr std::array<size_t, sizeof...(Indices)> Tensor< X, Symm, IndexList< Indices... > >::get_tensor_index (const const_iterator & iter) const inline noexcept
Given an iterator or storage index, get the canonical tensor index. For scalars this is defined to be std::array<int, 1>{{0}}.
References SPECTRE_ALWAYS_INLINE.
get_tensor_index() [2/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> static constexpr std::array<size_t, sizeof...(Indices)> Tensor< X, Symm, IndexList< Indices... > >::get_tensor_index (const size_t storage_index) inline static noexcept
Given an iterator or storage index, get the canonical tensor index. For scalars this is defined to be std::array<int, 1>{{0}}.
get_vector_of_data()
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> std::pair< std::vector< std::string >, std::vector< X > > Tensor< X, Symm, IndexList< Indices... > >::get_vector_of_data () const
Copy tensor data into an std::vector<X> along with the component names into a std::vector<std::string>
Requires: std::is_same<X, DataVector>::value is true
References gsl::at().
index_dim() [1/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> static constexpr size_t Tensor< X, Symm, IndexList< Indices... > >::index_dim (const size_t i) inline static noexcept
Get dimensionality of i'th tensor index.
Details
Consider the tensor \(T_{abc}\) where the dimensionality of each index is \((3, 2, 4)\), respectively. Then
dimensionality(0) = 3;
dimensionality(1) = 2;
dimensionality(2) = 4;
References gsl::at().
index_dim() [2/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> template<int I> static constexpr size_t Tensor< X, Symm, IndexList< Indices... > >::index_dim () inline static noexcept
Get dimensionality of i'th tensor index.
Details
Consider the tensor \(T_{abc}\) where the dimensionality of each index is \((3, 2, 4)\), respectively. Then
dimensionality(0) = 3;
dimensionality(1) = 2;
dimensionality(2) = 4;
References SPECTRE_ALWAYS_INLINE.
index_dims()
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> static constexpr std::array<size_t, sizeof...(Indices)> Tensor< X, Symm, IndexList< Indices... > >::index_dims () inline static noexcept
Return array of dimensionality of each index.
References SPECTRE_ALWAYS_INLINE.
index_frames()
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> static constexpr auto Tensor< X, Symm, IndexList< Indices... > >::index_frames () inline static noexcept
Returns std::tuple of the Frame of each index.
index_types()
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> static constexpr std::array<IndexType, sizeof...(Indices)> Tensor< X, Symm, IndexList< Indices... > >::index_types () inline static noexcept
Return array of the IndexType's (spatial or spacetime)
References SPECTRE_ALWAYS_INLINE.
index_valences()
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> static constexpr std::array<UpLo, sizeof...(Indices)> Tensor< X, Symm, IndexList< Indices... > >::index_valences () inline static noexcept
Return array of the valence of each index (UpLo)
multiplicity() [1/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> constexpr size_t Tensor< X, Symm, IndexList< Indices... > >::multiplicity (const iterator & iter) const inline noexcept
Given an iterator or storage index, get the multiplicity of an index.
See also
TensorMetafunctions::compute_multiplicity
multiplicity() [2/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> static constexpr size_t Tensor< X, Symm, IndexList< Indices... > >::multiplicity (const size_t storage_index) inline static noexcept
Given an iterator or storage index, get the multiplicity of an index.
See also
TensorMetafunctions::compute_multiplicity
operator()() [1/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> template<typename... N, Requires< cpp17::conjunction_v< tt::is_tensor_index< N >... > and tmpl::is_set< N... >::value > = nullptr> constexpr TE<tmpl::list<N...> > Tensor< X, Symm, IndexList< Indices... > >::operator() (N...) const inline
Retrieve a TensorExpression object with the index structure passed in.
References Parallel::value.
operator()() [2/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> template<typename... N, Requires< cpp17::conjunction_v< tt::is_tensor_index< N >... > and not tmpl::is_set< N... >::value > = nullptr> constexpr auto Tensor< X, Symm, IndexList< Indices... > >::operator() (N...) const -> decltype(TensorExpressions::fully_contracted< TE, replace_indices<tmpl::list<N...>, repeated<tmpl::list<N...>>>, tmpl::int32_t<0>, tmpl::size<repeated<tmpl::list<N...>>>>::apply(*this)) inline
Retrieve a TensorExpression object with the index structure passed in.
References db::apply().
operator=() [1/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> Tensor& Tensor< X, Symm, IndexList< Indices... > >::operator= (const Tensor< X, Symm, IndexList< Indices... > > &) default
operator=() [2/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> Tensor& Tensor< X, Symm, IndexList< Indices... > >::operator= (Tensor< X, Symm, IndexList< Indices... > > &&) default noexcept
operator[]() [1/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> constexpr reference Tensor< X, Symm, IndexList< Indices... > >::operator[] (const size_t storage_index) inline
Return i'th component of storage vector.
References gsl::at().
operator[]() [2/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> constexpr const_reference Tensor< X, Symm, IndexList< Indices... > >::operator[] (const size_t storage_index) const inline
Return i'th component of storage vector.
References gsl::at().
rank()
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> static constexpr size_t Tensor< X, Symm, IndexList< Indices... > >::rank () inline static noexcept
Returns the rank of the Tensor.
Details
The rank of a tensor is the number of indices it has. For example, the tensor \(v^a\) is rank-1, the tensor \(\phi\) is rank-0, and the tensor \(T_{abc}\) is rank-3.
References SPECTRE_ALWAYS_INLINE.
rbegin() [1/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> reverse_iterator Tensor< X, Symm, IndexList< Indices... > >::rbegin () inline
rbegin() [2/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> const_reverse_iterator Tensor< X, Symm, IndexList< Indices... > >::rbegin () const inline
rend() [1/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> reverse_iterator Tensor< X, Symm, IndexList< Indices... > >::rend () inline
rend() [2/2]
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> const_reverse_iterator Tensor< X, Symm, IndexList< Indices... > >::rend () const inline
size()
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> static constexpr size_t Tensor< X, Symm, IndexList< Indices... > >::size () inline static noexcept
Return the number of independent components of the Tensor.
Details
Returns the number of independent components of the Tensor taking into account symmetries. For example, let \(T_{ab}\) be a n-dimensional rank-2 symmetric tensor, then the number of independent components is \(n(n+1)/2\).
symmetries()
template<typename X , typename Symm , template< typename... > class IndexList, typename... Indices> static constexpr std::array<int, sizeof...(Indices)> Tensor< X, Symm, IndexList< Indices... > >::symmetries () inline static noexcept
Return an array corresponding to the Symmetry of the Tensor.
References SPECTRE_ALWAYS_INLINE.
The documentation for this class was generated from the following file:
src/DataStructures/Tensor/Tensor.hpp