SpECTRE: MathFunctions::PowX Class Reference
MathFunctions::PowX Class Reference
Power of X \(f(x)=x^X\).
#include <PowX.hpp>
Classes
struct Power
Public Types
using options = tmpl::list< Power >
Public Types inherited from MathFunction< 1 >
using creatable_classes = typelist< MathFunctions::Gaussian, MathFunctions::PowX, MathFunctions::Sinusoid >
Public Member Functions
PowX ()=default
~PowX () override=default
PowX (const PowX &)=delete
PowX & operator= (const PowX &)=delete
PowX (PowX &&) noexcept=default
PowX & operator= (PowX &&) noexcept=default
WRAPPED_PUPable_decl_template (PowX)
PowX (int power) noexcept
PowX (CkMigrateMessage *) noexcept
double operator() (const double &x) const noexcept override
Returns the function value at the coordinate 'x'.
DataVector operator() (const DataVector &x) const noexcept override
Returns the function value at the coordinate 'x'.
double first_deriv (const double &x) const noexcept override
Returns the first derivative at 'x'.
DataVector first_deriv (const DataVector &x) const noexcept override
Returns the first derivative at 'x'.
double second_deriv (const double &x) const noexcept override
Returns the second derivative at 'x'.
DataVector second_deriv (const DataVector &x) const noexcept override
Returns the second derivative at 'x'.
void pup (PUP::er &p) override
Public Member Functions inherited from MathFunction< 1 >
WRAPPED_PUPable_abstract (MathFunction)
MathFunction ()=default
MathFunction (const MathFunction &)=delete
MathFunction & operator= (const MathFunction &)=delete
MathFunction (MathFunction &&) noexcept=default
MathFunction & operator= (MathFunction &&) noexcept=default
~MathFunction () override=default
Static Public Attributes
static constexpr OptionString_t help
Detailed Description
Power of X \(f(x)=x^X\).
Member Typedef Documentation
options
using MathFunctions::PowX::options = tmpl::list<Power>
Constructor & Destructor Documentation
PowX() [1/5]
MathFunctions::PowX::PowX () default
~PowX()
MathFunctions::PowX::~PowX () override default
PowX() [2/5]
MathFunctions::PowX::PowX (const PowX &) delete
PowX() [3/5]
MathFunctions::PowX::PowX (PowX &&) default noexcept
PowX() [4/5]
MathFunctions::PowX::PowX (int power) explicit noexcept
PowX() [5/5]
MathFunctions::PowX::PowX (CkMigrateMessage *) inline explicit noexcept
References first_deriv(), operator()(), pup(), and second_deriv().
Member Function Documentation
first_deriv() [1/2]
double MathFunctions::PowX::first_deriv (const double & x) const override virtual noexcept
Returns the first derivative at 'x'.
Implements MathFunction< 1 >.
Referenced by PowX().
first_deriv() [2/2]
DataVector MathFunctions::PowX::first_deriv (const DataVector & x) const override virtual noexcept
Returns the first derivative at 'x'.
Implements MathFunction< 1 >.
operator()() [1/2]
double MathFunctions::PowX::operator() (const double & x) const override virtual noexcept
Returns the function value at the coordinate 'x'.
Implements MathFunction< 1 >.
Referenced by PowX().
operator()() [2/2]
DataVector MathFunctions::PowX::operator() (const DataVector & x) const override virtual noexcept
Returns the function value at the coordinate 'x'.
Implements MathFunction< 1 >.
operator=() [1/2]
PowX& MathFunctions::PowX::operator= (const PowX &) delete
operator=() [2/2]
PowX& MathFunctions::PowX::operator= (PowX &&) default noexcept
pup()
void MathFunctions::PowX::pup (PUP::er & p) override
Referenced by PowX().
second_deriv() [1/2]
double MathFunctions::PowX::second_deriv (const double & x) const override virtual noexcept
Returns the second derivative at 'x'.
Implements MathFunction< 1 >.
Referenced by PowX().
second_deriv() [2/2]
DataVector MathFunctions::PowX::second_deriv (const DataVector & x) const override virtual noexcept
Returns the second derivative at 'x'.
Implements MathFunction< 1 >.
References pow().
WRAPPED_PUPable_decl_template()
MathFunctions::PowX::WRAPPED_PUPable_decl_template (PowX)
Member Data Documentation
help
constexpr OptionString_t MathFunctions::PowX::help static
Initial value:
= {
      "Raises the input value to a given power"}
The documentation for this class was generated from the following files:
src/PointwiseFunctions/MathFunctions/PowX.hpp
src/PointwiseFunctions/MathFunctions/PowX.cpp