SpECTRE: ElementId< VolumeDim > Class Template Reference
ElementId< VolumeDim > Class Template Reference
Computational Domain
An ElementId uniquely labels a Element. It is constructed from the BlockId of the Block to which the Element belongs and the VolumeDim SegementIds that label the segments of the Block that the Element covers.
#include <ElementId.hpp>
Public Member Functions
constexpr ElementId ()=default
Default constructor needed for Charm++ serialization.
ElementId (size_t block_id) noexcept
Create the ElementId of the root Element of a Block.
ElementId (size_t block_id, std::array< SegmentId, VolumeDim > segment_ids) noexcept
Create an arbitrary ElementId.
ElementId< VolumeDim > id_of_child (size_t dim, Side side) const noexcept
ElementId< VolumeDim > id_of_parent (size_t dim) const noexcept
constexpr size_t block_id () const noexcept
const std::array< SegmentId, VolumeDim > & segment_ids () const noexcept
void pup (PUP::er &p)
Serialization for Charm++.
Detailed Description
template<size_t VolumeDim>
class ElementId< VolumeDim >
An ElementId uniquely labels a Element. It is constructed from the BlockId of the Block to which the Element belongs and the VolumeDim SegementIds that label the segments of the Block that the Element covers.
Constructor & Destructor Documentation
ElementId() [1/3]
template<size_t VolumeDim> constexpr ElementId< VolumeDim >::ElementId () default
Default constructor needed for Charm++ serialization.
ElementId() [2/3]
template<size_t VolumeDim> ElementId< VolumeDim >::ElementId (size_t block_id) explicit noexcept
Create the ElementId of the root Element of a Block.
ElementId() [3/3]
template<size_t VolumeDim> ElementId< VolumeDim >::ElementId (size_t block_id, std::array< SegmentId, VolumeDim > segment_ids) noexcept
Create an arbitrary ElementId.
Member Function Documentation
block_id()
template<size_t VolumeDim> constexpr size_t ElementId< VolumeDim >::block_id () const inline noexcept
Referenced by operator==().
id_of_child()
template<size_t VolumeDim> ElementId< VolumeDim > ElementId< VolumeDim >::id_of_child (size_t dim, Side side) const noexcept
References gsl::at().
id_of_parent()
template<size_t VolumeDim> ElementId< VolumeDim > ElementId< VolumeDim >::id_of_parent (size_t dim) const noexcept
References gsl::at().
pup()
template<size_t VolumeDim> void ElementId< VolumeDim >::pup (PUP::er & p)
Serialization for Charm++.
Referenced by ElementId< VolumeDim >::segment_ids().
segment_ids()
template<size_t VolumeDim> const std::array<SegmentId, VolumeDim>& ElementId< VolumeDim >::segment_ids () const inline noexcept
References hash_value(), std::numeric_limits::max(), operator!=(), operator==(), and ElementId< VolumeDim >::pup().
Referenced by operator==().
The documentation for this class was generated from the following files:
src/Domain/ElementId.hpp
src/Domain/ElementId.cpp