SpECTRE: SegmentId Class Reference
SegmentId Class Reference
Computational Domain
A SegmentId labels a segment of the interval [-1,1]. A SegmentId is used to (partially) identify an Element. The segment is the interval [-1 + 2*(N/D), -1 + 2*(N+1)/D] where N = index_ and D = 2 ^ refinement_level_.
#include <SegmentId.hpp>
Public Member Functions
constexpr SegmentId () noexcept=default
Default constructor needed for Charm++ serialization.
constexpr SegmentId (const SegmentId &segment_id) noexcept=default
constexpr SegmentId (SegmentId &&segment_id) noexcept=default
~SegmentId () noexcept=default
SegmentId & operator= (const SegmentId &segment_id) noexcept=default
SegmentId & operator= (SegmentId &&segment_id) noexcept=default
SegmentId (size_t refinement_level, size_t index)
constexpr size_t refinement_level () const noexcept
constexpr size_t index () const noexcept
SegmentId id_of_parent () const noexcept
SegmentId id_of_child (Side side) const noexcept
SegmentId id_if_flipped () const noexcept
The id this segment would have if the coordinate axis were flipped.
double endpoint (Side side) const noexcept
The logical coordinate of the endpoint of the segment on the given Side.
double midpoint () const noexcept
The logical coordinate of the midpoint of the segment.
bool overlaps (const SegmentId &other) const noexcept
Does the segment overlap with another?
void pup (PUP::er &p)
Serialization for Charm++.
Detailed Description
A SegmentId labels a segment of the interval [-1,1]. A SegmentId is used to (partially) identify an Element. The segment is the interval [-1 + 2*(N/D), -1 + 2*(N+1)/D] where N = index_ and D = 2 ^ refinement_level_.
Constructor & Destructor Documentation
SegmentId() [1/4]
constexpr SegmentId::SegmentId () default noexcept
Default constructor needed for Charm++ serialization.
SegmentId() [2/4]
constexpr SegmentId::SegmentId (const SegmentId & segment_id) default noexcept
SegmentId() [3/4]
constexpr SegmentId::SegmentId (SegmentId && segment_id) default noexcept
~SegmentId()
SegmentId::~SegmentId () default noexcept
SegmentId() [4/4]
SegmentId::SegmentId (size_t refinement_level, size_t index)
References ASSERT, and two_to_the().
Member Function Documentation
endpoint()
double SegmentId::endpoint (Side side) const inline noexcept
The logical coordinate of the endpoint of the segment on the given Side.
References Lower, and two_to_the().
Referenced by index().
id_if_flipped()
SegmentId SegmentId::id_if_flipped () const inline noexcept
The id this segment would have if the coordinate axis were flipped.
References two_to_the().
Referenced by index().
id_of_child()
SegmentId SegmentId::id_of_child (Side side) const inline noexcept
References Lower.
Referenced by index().
id_of_parent()
SegmentId SegmentId::id_of_parent () const inline noexcept
References CASSERT.
Referenced by index().
index()
constexpr size_t SegmentId::index () const inline noexcept
References endpoint(), id_if_flipped(), id_of_child(), and id_of_parent().
Referenced by operator==().
midpoint()
double SegmentId::midpoint () const inline noexcept
The logical coordinate of the midpoint of the segment.
References std::numeric_limits::max(), operator!=(), operator<<(), operator==(), overlaps(), pup(), and two_to_the().
operator=() [1/2]
SegmentId& SegmentId::operator= (const SegmentId & segment_id) default noexcept
operator=() [2/2]
SegmentId& SegmentId::operator= (SegmentId && segment_id) default noexcept
overlaps()
bool SegmentId::overlaps (const SegmentId & other) const inline noexcept
Does the segment overlap with another?
References hash_value(), and two_to_the().
Referenced by midpoint().
pup()
void SegmentId::pup (PUP::er & p)
Serialization for Charm++.
Referenced by midpoint().
refinement_level()
constexpr size_t SegmentId::refinement_level () const inline noexcept
Referenced by operator==().
The documentation for this class was generated from the following files:
src/Domain/SegmentId.hpp
src/Domain/SegmentId.cpp