SpECTRE: GeneralIndexIterator< Container > Class Template Reference
GeneralIndexIterator< Container > Class Template Reference
Iterate over a generic "block" of coordinates. The constructor takes a container of pairs defining the range (inclusive start, exclusive end) of each coordinate. The utility function make_general_index_iterator() is provided for easier construction.
#include <GeneralIndexIterator.hpp>
Public Types
using value_type = typename Container::value_type::first_type
using iterator_type = typename std::vector< value_type >::const_iterator
Public Member Functions
GeneralIndexIterator (Container ranges) noexcept
const value_type & operator[] (size_t i) const noexcept
Access the given coordinate of the current value.
operator bool () const noexcept
Check whether the iterator is complete. Calling any of the other methods on a completed iterator is undefined behavior.
void operator++ () noexcept
iterator_type cbegin () const noexcept
Iterate over the coordinates of the current value.
iterator_type cend () const noexcept
Iterate over the coordinates of the current value.
iterator_type begin () const noexcept
Iterate over the coordinates of the current value.
iterator_type end () const noexcept
Iterate over the coordinates of the current value.
Detailed Description
template<typename Container>
class GeneralIndexIterator< Container >
Iterate over a generic "block" of coordinates. The constructor takes a container of pairs defining the range (inclusive start, exclusive end) of each coordinate. The utility function make_general_index_iterator() is provided for easier construction.
Member Typedef Documentation
iterator_type
template<typename Container > using GeneralIndexIterator< Container >::iterator_type = typename std::vector<value_type>::const_iterator
value_type
template<typename Container > using GeneralIndexIterator< Container >::value_type = typename Container::value_type::first_type
Constructor & Destructor Documentation
GeneralIndexIterator()
template<typename Container > GeneralIndexIterator< Container >::GeneralIndexIterator (Container ranges) inline explicit noexcept
Member Function Documentation
begin()
template<typename Container > iterator_type GeneralIndexIterator< Container >::begin () const inline noexcept
Iterate over the coordinates of the current value.
References GeneralIndexIterator< Container >::cbegin().
cbegin()
template<typename Container > iterator_type GeneralIndexIterator< Container >::cbegin () const inline noexcept
Iterate over the coordinates of the current value.
Referenced by GeneralIndexIterator< Container >::begin().
cend()
template<typename Container > iterator_type GeneralIndexIterator< Container >::cend () const inline noexcept
Iterate over the coordinates of the current value.
Referenced by GeneralIndexIterator< Container >::end().
end()
template<typename Container > iterator_type GeneralIndexIterator< Container >::end () const inline noexcept
Iterate over the coordinates of the current value.
References GeneralIndexIterator< Container >::cend().
operator bool()
template<typename Container > GeneralIndexIterator< Container >::operator bool () const inline explicit noexcept
Check whether the iterator is complete. Calling any of the other methods on a completed iterator is undefined behavior.
operator++()
template<typename Container > void GeneralIndexIterator< Container >::operator++ () inline noexcept
References gsl::at().
operator[]()
template<typename Container > const value_type& GeneralIndexIterator< Container >::operator[] (size_t i) const inline noexcept
Access the given coordinate of the current value.
The documentation for this class was generated from the following file:
src/DataStructures/GeneralIndexIterator.hpp