SpECTRE: YlmSpherepack Class Reference
YlmSpherepack Class Reference
Spectral
C++ interface to SPHEREPACK.
#include <YlmSpherepack.hpp>
Classes
struct InterpolationInfoPerPoint
Cached information to interpolate to the target point.
Public Types
using FirstDeriv = tnsr::i< DataVector, 2, Frame::Logical >
Type returned by gradient function.
using SecondDeriv = tnsr::ij< DataVector, 2, Frame::Logical >
Type returned by second derivative function.
using InterpolationInfo = std::vector< InterpolationInfoPerPoint >
Type to hold cached information at a set of target interpolation points.
Public Member Functions
YlmSpherepack (size_t l_max, size_t m_max) noexcept
Here l_max and m_max are the largest fully-represented l and m in the Ylm expansion.
std::array< size_t, 2 > physical_extents () const noexcept
void gradient (const std::array< double *, 2 > &df, gsl::not_null< const double *> collocation_values, size_t physical_stride=1, size_t physical_offset=0) const noexcept
Computes Pfaffian derivative (df/dtheta, csc(theta) df/dphi) at the collocation values. To act on a slice of the input and output arrays, specify stride and offset (assumed to be the same for input and output).
void gradient_from_coefs (const std::array< double *, 2 > &df, gsl::not_null< const double *> spectral_coefs, size_t spectral_stride=1, size_t spectral_offset=0, size_t physical_stride=1, size_t physical_offset=0) const noexcept
Same as gradient, but takes the spectral coefficients (rather than collocation values) of the function. This is more efficient if one happens to already have the spectral coefficients. To act on a slice of the input and output arrays, specify strides and offsets.
void scalar_laplacian (gsl::not_null< double *> scalar_laplacian, gsl::not_null< const double *> collocation_values, size_t physical_stride=1, size_t physical_offset=0) const noexcept
Computes Laplacian in physical space. To act on a slice of the input and output arrays, specify stride and offset (assumed to be the same for input and output).
void scalar_laplacian_from_coefs (gsl::not_null< double *> scalar_laplacian, gsl::not_null< const double *> spectral_coefs, size_t spectral_stride=1, size_t spectral_offset=0, size_t physical_stride=1, size_t physical_offset=0) const noexcept
Same as scalar_laplacian above, but the input is the spectral coefficients (rather than collocation values) of the function. This is more efficient if one happens to already have the spectral coefficients. To act on a slice of the input and output arrays, specify strides and offsets.
void second_derivative (const std::array< double *, 2 > &df, gsl::not_null< SecondDeriv *> ddf, gsl::not_null< const double *> collocation_values, size_t physical_stride=1, size_t physical_offset=0) const noexcept
Computes Pfaffian first and second derivative in physical space. The first derivative is \(df(i) = d_i f\), and the second derivative is \(ddf(i,j) = d_i (d_j f)\), where \(d_0 = d/d\theta\) and \(d_1 = csc(\theta) d/d\phi\). ddf is not symmetric. To act on a slice of the input and output arrays, specify stride and offset (assumed to be the same for input and output).
std::pair< FirstDeriv, SecondDeriv > first_and_second_derivative (const DataVector &collocation_values) const noexcept
Simpler, less general interface to second_derivative.
double definite_integral (gsl::not_null< const double *> collocation_values, size_t physical_stride=1, size_t physical_offset=0) const noexcept
Computes the integral over the sphere.
const std::vector< double > & integration_weights () const noexcept
Returns weights \(w_i\) such that \(sum_i (c_i w_i)\) is the definite integral, where \(c_i\) are collocation values at point i.
void add_constant (const gsl::not_null< DataVector *> spectral_coefs, const double c) const noexcept
Adds a constant (i.e. \(f(\theta,\phi)\) += \(c\)) to the function given by the spectral coefficients, by modifying the coefficients.
double average (const DataVector &spectral_coefs) const noexcept
Returns the average of \(f(\theta,\phi)\) over \((\theta,\phi)\).
InterpolationInfo set_up_interpolation_info (const std::vector< std::array< double, 2 >> &target_points) const noexcept
Sets up the InterpolationInfo structure for interpolating onto a set of target \((\theta,\phi)\) points. Does not depend on the function being interpolated.
void interpolate (gsl::not_null< std::vector< double > *> result, gsl::not_null< const double *> collocation_values, const InterpolationInfo &interpolation_info, size_t physical_stride=1, size_t physical_offset=0) const noexcept
Interpolates from collocation_values onto the points that have been passed into the set_up_interpolation_info function. To interpolate a different function on the same spectral grid, there is no need to recompute interpolation_info. If you specify stride and offset, acts on a slice of the input values. The output has unit stride.
template<typename T >
void interpolate_from_coefs (gsl::not_null< std::vector< double > *> result, const T &spectral_coefs, const InterpolationInfo &interpolation_info, size_t spectral_stride=1, size_t spectral_offset=0) const noexcept
Same as interpolate, but assumes you have spectral coefficients. This is more efficient if you already have the spectral coefficients available. If you specify stride and offset, acts on a slice of the input coefs. The output has unit stride.
std::vector< double > interpolate (const DataVector &collocation_values, const std::vector< std::array< double, 2 >> &target_points) const noexcept
Simpler interface to interpolate. If you need to call this repeatedly on different spectral_coefs or collocation_values for the same target points, this is inefficient; instead use set_up_interpolation_info and the functions that use InterpolationInfo.
std::vector< double > interpolate_from_coefs (const DataVector &spectral_coefs, const std::vector< std::array< double, 2 >> &target_points) const noexcept
DataVector prolong_or_restrict (const DataVector &spectral_coefs, const YlmSpherepack &target) const noexcept
Takes spectral coefficients compatible with *this, and either prolongs them or restricts them to be compatible with target. This is done by truncation (restriction) or padding with zeros (prolongation).
template<typename T >
void interpolate_from_coefs (const gsl::not_null< std::vector< double > *> result, const T &spectral_coefs, const InterpolationInfo &interpolation_info, const size_t spectral_stride, const size_t spectral_offset) const noexcept
size_t l_max () const noexcept
Sizes in physical and spectral space for this instance.
size_t m_max () const noexcept
Sizes in physical and spectral space for this instance.
size_t physical_size () const noexcept
Sizes in physical and spectral space for this instance.
size_t spectral_size () const noexcept
Sizes in physical and spectral space for this instance.
const std::vector< double > & theta_points () const noexcept
Collocation points theta and phi.
const std::vector< double > & phi_points () const noexcept
Collocation points theta and phi.
std::array< DataVector, 2 > theta_phi_points () const noexcept
Collocation points theta and phi.
void phys_to_spec (gsl::not_null< double *> spectral_coefs, gsl::not_null< const double *> collocation_values, size_t physical_stride=1, size_t physical_offset=0, size_t spectral_stride=1, size_t spectral_offset=0) const noexcept
Spectral transformations. To act on a slice of the input and output arrays, specify strides and offsets.
void spec_to_phys (gsl::not_null< double *> collocation_values, gsl::not_null< const double *> spectral_coefs, size_t spectral_stride=1, size_t spectral_offset=0, size_t physical_stride=1, size_t physical_offset=0) const noexcept
Spectral transformations. To act on a slice of the input and output arrays, specify strides and offsets.
void phys_to_spec_all_offsets (gsl::not_null< double *> spectral_coefs, gsl::not_null< const double *> collocation_values, size_t stride) const noexcept
Spectral transformations where collocation_values and spectral_coefs are assumed to point to 3-dimensional arrays (I1 x S2 topology), and the transformations are done for all 'radial' points at once by internally looping over all values of the offset from zero to stride-1 (the physical and spectral strides are equal and are called stride).
void spec_to_phys_all_offsets (gsl::not_null< double *> collocation_values, gsl::not_null< const double *> spectral_coefs, size_t stride) const noexcept
Spectral transformations where collocation_values and spectral_coefs are assumed to point to 3-dimensional arrays (I1 x S2 topology), and the transformations are done for all 'radial' points at once by internally looping over all values of the offset from zero to stride-1 (the physical and spectral strides are equal and are called stride).
DataVector phys_to_spec (const DataVector &collocation_values, size_t physical_stride=1, size_t physical_offset=0) const noexcept
Simpler, less general interfaces to phys_to_spec and spec_to_phys. Acts on a slice of the input and returns a unit-stride result.
DataVector spec_to_phys (const DataVector &spectral_coefs, size_t spectral_stride=1, size_t spectral_offset=0) const noexcept
Simpler, less general interfaces to phys_to_spec and spec_to_phys. Acts on a slice of the input and returns a unit-stride result.
DataVector phys_to_spec_all_offsets (const DataVector &collocation_values, size_t stride) const noexcept
Simpler, less general interfaces to phys_to_spec_all_offsets and spec_to_phys_all_offsets. Result has the same stride as the input.
DataVector spec_to_phys_all_offsets (const DataVector &spectral_coefs, size_t stride) const noexcept
Simpler, less general interfaces to phys_to_spec_all_offsets and spec_to_phys_all_offsets. Result has the same stride as the input.
void gradient_all_offsets (const std::array< double *, 2 > &df, gsl::not_null< const double *> collocation_values, size_t stride=1) const noexcept
Same as gradient but pointers are assumed to point to 3-dimensional arrays (I1 x S2 topology), and the gradient is done for all 'radial' points at once by internally looping over all values of the offset from zero to stride-1.
void gradient_from_coefs_all_offsets (const std::array< double *, 2 > &df, gsl::not_null< const double *> spectral_coefs, size_t stride=1) const noexcept
Same as gradient but pointers are assumed to point to 3-dimensional arrays (I1 x S2 topology), and the gradient is done for all 'radial' points at once by internally looping over all values of the offset from zero to stride-1.
FirstDeriv gradient (const DataVector &collocation_values, size_t physical_stride=1, size_t physical_offset=0) const noexcept
Simpler, less general interfaces to gradient. Acts on a slice of the input and returns a unit-stride result.
FirstDeriv gradient_from_coefs (const DataVector &spectral_coefs, size_t spectral_stride=1, size_t spectral_offset=0) const noexcept
Simpler, less general interfaces to gradient. Acts on a slice of the input and returns a unit-stride result.
FirstDeriv gradient_all_offsets (const DataVector &collocation_values, size_t stride=1) const noexcept
Simpler, less general interfaces to gradient_all_offsets. Result has the same stride as the input.
FirstDeriv gradient_from_coefs_all_offsets (const DataVector &spectral_coefs, size_t stride=1) const noexcept
Simpler, less general interfaces to gradient_all_offsets. Result has the same stride as the input.
DataVector scalar_laplacian (const DataVector &collocation_values, size_t physical_stride=1, size_t physical_offset=0) const noexcept
Simpler, less general interfaces to scalar_laplacian. Acts on a slice of the input and returns a unit-stride result.
DataVector scalar_laplacian_from_coefs (const DataVector &spectral_coefs, size_t spectral_stride=1, size_t spectral_offset=0) const noexcept
Simpler, less general interfaces to scalar_laplacian. Acts on a slice of the input and returns a unit-stride result.
Static Public Member Functions
static constexpr size_t physical_size (const size_t l_max, const size_t m_max) noexcept
Static functions to return the correct sizes of vectors of collocation points and spectral coefficients for a given l_max and m_max. Useful for allocating space without having to create a YlmSpherepack.
static constexpr size_t spectral_size (const size_t l_max, const size_t m_max) noexcept
Static functions to return the correct sizes of vectors of collocation points and spectral coefficients for a given l_max and m_max. Useful for allocating space without having to create a YlmSpherepack.
Detailed Description
C++ interface to SPHEREPACK.
Member Typedef Documentation
FirstDeriv
using YlmSpherepack::FirstDeriv = tnsr::i<DataVector, 2, Frame::Logical>
Type returned by gradient function.
InterpolationInfo
using YlmSpherepack::InterpolationInfo = std::vector<InterpolationInfoPerPoint>
Type to hold cached information at a set of target interpolation points.
SecondDeriv
using YlmSpherepack::SecondDeriv = tnsr::ij<DataVector, 2, Frame::Logical>
Type returned by second derivative function.
Constructor & Destructor Documentation
YlmSpherepack()
YlmSpherepack::YlmSpherepack (size_t l_max, size_t m_max) noexcept
Here l_max and m_max are the largest fully-represented l and m in the Ylm expansion.
References ASSERT, ERROR, shags_(), shsgs_(), and UNLIKELY.
Member Function Documentation
add_constant()
void YlmSpherepack::add_constant (const gsl::not_null< DataVector *> spectral_coefs, const double c) const inline noexcept
Adds a constant (i.e. \(f(\theta,\phi)\) += \(c\)) to the function given by the spectral coefficients, by modifying the coefficients.
average()
double YlmSpherepack::average (const DataVector & spectral_coefs) const inline noexcept
Returns the average of \(f(\theta,\phi)\) over \((\theta,\phi)\).
References interpolate(), interpolate_from_coefs(), operator!=(), operator==(), prolong_or_restrict(), and set_up_interpolation_info().
definite_integral()
double YlmSpherepack::definite_integral (gsl::not_null< const double *> collocation_values, size_t physical_stride = 1, size_t physical_offset = 0) const inline noexcept
Computes the integral over the sphere.
References ddot_(), and gsl::not_null< T >::get().
first_and_second_derivative()
std::pair< YlmSpherepack::FirstDeriv, YlmSpherepack::SecondDeriv > YlmSpherepack::first_and_second_derivative (const DataVector & collocation_values) const noexcept
Simpler, less general interface to second_derivative.
References ASSERT, physical_size(), and second_derivative().
Referenced by gradient_from_coefs_all_offsets().
gradient() [1/2]
void YlmSpherepack::gradient (const std::array< double *, 2 > & df, gsl::not_null< const double *> collocation_values, size_t physical_stride = 1, size_t physical_offset = 0) const noexcept
Computes Pfaffian derivative (df/dtheta, csc(theta) df/dphi) at the collocation values. To act on a slice of the input and output arrays, specify stride and offset (assumed to be the same for input and output).
Referenced by gradient_from_coefs_all_offsets(), second_derivative(), and spec_to_phys_all_offsets().
gradient() [2/2]
YlmSpherepack::FirstDeriv YlmSpherepack::gradient (const DataVector & collocation_values, size_t physical_stride = 1, size_t physical_offset = 0) const noexcept
Simpler, less general interfaces to gradient. Acts on a slice of the input and returns a unit-stride result.
References ASSERT.
gradient_all_offsets() [1/2]
void YlmSpherepack::gradient_all_offsets (const std::array< double *, 2 > & df, gsl::not_null< const double *> collocation_values, size_t stride = 1) const noexcept
Same as gradient but pointers are assumed to point to 3-dimensional arrays (I1 x S2 topology), and the gradient is done for all 'radial' points at once by internally looping over all values of the offset from zero to stride-1.
Referenced by gradient_from_coefs(), gradient_from_coefs_all_offsets(), and spec_to_phys_all_offsets().
gradient_all_offsets() [2/2]
YlmSpherepack::FirstDeriv YlmSpherepack::gradient_all_offsets (const DataVector & collocation_values, size_t stride = 1) const noexcept
Simpler, less general interfaces to gradient_all_offsets. Result has the same stride as the input.
References ASSERT.
gradient_from_coefs() [1/2]
void YlmSpherepack::gradient_from_coefs (const std::array< double *, 2 > & df, gsl::not_null< const double *> spectral_coefs, size_t spectral_stride = 1, size_t spectral_offset = 0, size_t physical_stride = 1, size_t physical_offset = 0) const inline noexcept
Same as gradient, but takes the spectral coefficients (rather than collocation values) of the function. This is more efficient if one happens to already have the spectral coefficients. To act on a slice of the input and output arrays, specify strides and offsets.
References gradient_all_offsets().
Referenced by gradient_from_coefs_all_offsets().
gradient_from_coefs() [2/2]
YlmSpherepack::FirstDeriv YlmSpherepack::gradient_from_coefs (const DataVector & spectral_coefs, size_t spectral_stride = 1, size_t spectral_offset = 0) const noexcept
Simpler, less general interfaces to gradient. Acts on a slice of the input and returns a unit-stride result.
References ASSERT.
gradient_from_coefs_all_offsets() [1/2]
void YlmSpherepack::gradient_from_coefs_all_offsets (const std::array< double *, 2 > & df, gsl::not_null< const double *> spectral_coefs, size_t stride = 1) const inline noexcept
Same as gradient but pointers are assumed to point to 3-dimensional arrays (I1 x S2 topology), and the gradient is done for all 'radial' points at once by internally looping over all values of the offset from zero to stride-1.
References first_and_second_derivative(), gradient(), gradient_all_offsets(), gradient_from_coefs(), scalar_laplacian(), scalar_laplacian_from_coefs(), and second_derivative().
gradient_from_coefs_all_offsets() [2/2]
YlmSpherepack::FirstDeriv YlmSpherepack::gradient_from_coefs_all_offsets (const DataVector & spectral_coefs, size_t stride = 1) const noexcept
Simpler, less general interfaces to gradient_all_offsets. Result has the same stride as the input.
References ASSERT, ERROR, gsl::not_null< T >::get(), scalar_laplacian(), scalar_laplacian_from_coefs(), slapgs_(), and UNLIKELY.
integration_weights()
const std::vector<double>& YlmSpherepack::integration_weights () const inline noexcept
Returns weights \(w_i\) such that \(sum_i (c_i w_i)\) is the definite integral, where \(c_i\) are collocation values at point i.
interpolate() [1/2]
void YlmSpherepack::interpolate (gsl::not_null< std::vector< double > *> result, gsl::not_null< const double *> collocation_values, const InterpolationInfo & interpolation_info, size_t physical_stride = 1, size_t physical_offset = 0) const noexcept
Interpolates from collocation_values onto the points that have been passed into the set_up_interpolation_info function. To interpolate a different function on the same spectral grid, there is no need to recompute interpolation_info. If you specify stride and offset, acts on a slice of the input values. The output has unit stride.
Referenced by average(), interpolate(), and set_up_interpolation_info().
interpolate() [2/2]
std::vector< double > YlmSpherepack::interpolate (const DataVector & collocation_values, const std::vector< std::array< double, 2 >> & target_points) const noexcept
Simpler interface to interpolate. If you need to call this repeatedly on different spectral_coefs or collocation_values for the same target points, this is inefficient; instead use set_up_interpolation_info and the functions that use InterpolationInfo.
References ASSERT, interpolate(), physical_size(), and set_up_interpolation_info().
interpolate_from_coefs() [1/3]
template<typename T > void YlmSpherepack::interpolate_from_coefs (gsl::not_null< std::vector< double > *> result, const T & spectral_coefs, const InterpolationInfo & interpolation_info, size_t spectral_stride = 1, size_t spectral_offset = 0) const noexcept
Same as interpolate, but assumes you have spectral coefficients. This is more efficient if you already have the spectral coefficients available. If you specify stride and offset, acts on a slice of the input coefs. The output has unit stride.
Referenced by average(), interpolate_from_coefs(), and set_up_interpolation_info().
interpolate_from_coefs() [2/3]
std::vector< double > YlmSpherepack::interpolate_from_coefs (const DataVector & spectral_coefs, const std::vector< std::array< double, 2 >> & target_points) const noexcept
References ASSERT, ERROR, gaqd_(), interpolate_from_coefs(), Basis::lgl::quadrature_weights(), set_up_interpolation_info(), shagsi_(), shsgsi_(), spectral_size(), UNLIKELY, and vhsgsi_().
interpolate_from_coefs() [3/3]
template<typename T > void YlmSpherepack::interpolate_from_coefs (const gsl::not_null< std::vector< double > *> result, const T & spectral_coefs, const InterpolationInfo & interpolation_info, const size_t spectral_stride, const size_t spectral_offset) const noexcept
References ASSERT, and YlmSpherepack::InterpolationInfoPerPoint::cos_theta.
l_max()
size_t YlmSpherepack::l_max () const inline noexcept
Sizes in physical and spectral space for this instance.
Referenced by physical_size(), and spectral_size().
m_max()
size_t YlmSpherepack::m_max () const inline noexcept
Sizes in physical and spectral space for this instance.
Referenced by physical_size(), and spectral_size().
phi_points()
const std::vector< double > & YlmSpherepack::phi_points () const noexcept
Collocation points theta and phi.
Referenced by physical_extents(), second_derivative(), and theta_phi_points().
phys_to_spec() [1/2]
void YlmSpherepack::phys_to_spec (gsl::not_null< double *> spectral_coefs, gsl::not_null< const double *> collocation_values, size_t physical_stride = 1, size_t physical_offset = 0, size_t spectral_stride = 1, size_t spectral_offset = 0) const inline noexcept
Spectral transformations. To act on a slice of the input and output arrays, specify strides and offsets.
Referenced by set_up_interpolation_info(), and spec_to_phys_all_offsets().
phys_to_spec() [2/2]
DataVector YlmSpherepack::phys_to_spec (const DataVector & collocation_values, size_t physical_stride = 1, size_t physical_offset = 0) const noexcept
Simpler, less general interfaces to phys_to_spec and spec_to_phys. Acts on a slice of the input and returns a unit-stride result.
References ASSERT.
phys_to_spec_all_offsets() [1/2]
void YlmSpherepack::phys_to_spec_all_offsets (gsl::not_null< double *> spectral_coefs, gsl::not_null< const double *> collocation_values, size_t stride) const inline noexcept
Spectral transformations where collocation_values and spectral_coefs are assumed to point to 3-dimensional arrays (I1 x S2 topology), and the transformations are done for all 'radial' points at once by internally looping over all values of the offset from zero to stride-1 (the physical and spectral strides are equal and are called stride).
Referenced by spec_to_phys_all_offsets().
phys_to_spec_all_offsets() [2/2]
DataVector YlmSpherepack::phys_to_spec_all_offsets (const DataVector & collocation_values, size_t stride) const noexcept
Simpler, less general interfaces to phys_to_spec_all_offsets and spec_to_phys_all_offsets. Result has the same stride as the input.
References ASSERT.
physical_extents()
std::array<size_t, 2> YlmSpherepack::physical_extents () const inline noexcept
References phi_points(), theta_phi_points(), and theta_points().
physical_size() [1/2]
static constexpr size_t YlmSpherepack::physical_size (const size_t l_max, const size_t m_max) inline static noexcept
Static functions to return the correct sizes of vectors of collocation points and spectral coefficients for a given l_max and m_max. Useful for allocating space without having to create a YlmSpherepack.
References l_max(), and m_max().
physical_size() [2/2]
size_t YlmSpherepack::physical_size () const inline noexcept
Sizes in physical and spectral space for this instance.
Referenced by first_and_second_derivative(), interpolate(), second_derivative(), and theta_phi_points().
prolong_or_restrict()
DataVector YlmSpherepack::prolong_or_restrict (const DataVector & spectral_coefs, const YlmSpherepack & target) const noexcept
Takes spectral coefficients compatible with *this, and either prolongs them or restricts them to be compatible with target. This is done by truncation (restriction) or padding with zeros (prolongation).
References ASSERT, SpherepackIterator::coefficient_array(), SpherepackIterator::l(), SpherepackIterator::m(), and spectral_size().
Referenced by average().
scalar_laplacian() [1/2]
void YlmSpherepack::scalar_laplacian (gsl::not_null< double *> scalar_laplacian, gsl::not_null< const double *> collocation_values, size_t physical_stride = 1, size_t physical_offset = 0) const noexcept
Computes Laplacian in physical space. To act on a slice of the input and output arrays, specify stride and offset (assumed to be the same for input and output).
Referenced by gradient_from_coefs_all_offsets().
scalar_laplacian() [2/2]
DataVector YlmSpherepack::scalar_laplacian (const DataVector & collocation_values, size_t physical_stride = 1, size_t physical_offset = 0) const noexcept
Simpler, less general interfaces to scalar_laplacian. Acts on a slice of the input and returns a unit-stride result.
References ASSERT.
scalar_laplacian_from_coefs() [1/2]
void YlmSpherepack::scalar_laplacian_from_coefs (gsl::not_null< double *> scalar_laplacian, gsl::not_null< const double *> spectral_coefs, size_t spectral_stride = 1, size_t spectral_offset = 0, size_t physical_stride = 1, size_t physical_offset = 0) const noexcept
Same as scalar_laplacian above, but the input is the spectral coefficients (rather than collocation values) of the function. This is more efficient if one happens to already have the spectral coefficients. To act on a slice of the input and output arrays, specify strides and offsets.
Referenced by gradient_from_coefs_all_offsets().
scalar_laplacian_from_coefs() [2/2]
DataVector YlmSpherepack::scalar_laplacian_from_coefs (const DataVector & spectral_coefs, size_t spectral_stride = 1, size_t spectral_offset = 0) const noexcept
Simpler, less general interfaces to scalar_laplacian. Acts on a slice of the input and returns a unit-stride result.
References ASSERT.
second_derivative()
void YlmSpherepack::second_derivative (const std::array< double *, 2 > & df, gsl::not_null< SecondDeriv *> ddf, gsl::not_null< const double *> collocation_values, size_t physical_stride = 1, size_t physical_offset = 0) const noexcept
Computes Pfaffian first and second derivative in physical space. The first derivative is \(df(i) = d_i f\), and the second derivative is \(ddf(i,j) = d_i (d_j f)\), where \(d_0 = d/d\theta\) and \(d_1 = csc(\theta) d/d\phi\). ddf is not symmetric. To act on a slice of the input and output arrays, specify stride and offset (assumed to be the same for input and output).
References gsl::at(), gradient(), phi_points(), physical_size(), and theta_points().
Referenced by first_and_second_derivative(), and gradient_from_coefs_all_offsets().
set_up_interpolation_info()
YlmSpherepack::InterpolationInfo YlmSpherepack::set_up_interpolation_info (const std::vector< std::array< double, 2 >> & target_points) const noexcept
Sets up the InterpolationInfo structure for interpolating onto a set of target \((\theta,\phi)\) points. Does not depend on the function being interpolated.
References ASSERT, interpolate(), interpolate_from_coefs(), phys_to_spec(), and spectral_size().
Referenced by average(), interpolate(), and interpolate_from_coefs().
spec_to_phys() [1/2]
void YlmSpherepack::spec_to_phys (gsl::not_null< double *> collocation_values, gsl::not_null< const double *> spectral_coefs, size_t spectral_stride = 1, size_t spectral_offset = 0, size_t physical_stride = 1, size_t physical_offset = 0) const inline noexcept
Spectral transformations. To act on a slice of the input and output arrays, specify strides and offsets.
Referenced by spec_to_phys_all_offsets().
spec_to_phys() [2/2]
DataVector YlmSpherepack::spec_to_phys (const DataVector & spectral_coefs, size_t spectral_stride = 1, size_t spectral_offset = 0) const noexcept
Simpler, less general interfaces to phys_to_spec and spec_to_phys. Acts on a slice of the input and returns a unit-stride result.
References ASSERT.
spec_to_phys_all_offsets() [1/2]
void YlmSpherepack::spec_to_phys_all_offsets (gsl::not_null< double *> collocation_values, gsl::not_null< const double *> spectral_coefs, size_t stride) const inline noexcept
Spectral transformations where collocation_values and spectral_coefs are assumed to point to 3-dimensional arrays (I1 x S2 topology), and the transformations are done for all 'radial' points at once by internally looping over all values of the offset from zero to stride-1 (the physical and spectral strides are equal and are called stride).
References gradient(), phys_to_spec(), phys_to_spec_all_offsets(), and spec_to_phys().
spec_to_phys_all_offsets() [2/2]
DataVector YlmSpherepack::spec_to_phys_all_offsets (const DataVector & spectral_coefs, size_t stride) const noexcept
Simpler, less general interfaces to phys_to_spec_all_offsets and spec_to_phys_all_offsets. Result has the same stride as the input.
References ASSERT, ERROR, gradgs_(), gradient(), gradient_all_offsets(), and UNLIKELY.
spectral_size() [1/2]
static constexpr size_t YlmSpherepack::spectral_size (const size_t l_max, const size_t m_max) inline static noexcept
Static functions to return the correct sizes of vectors of collocation points and spectral coefficients for a given l_max and m_max. Useful for allocating space without having to create a YlmSpherepack.
References l_max(), and m_max().
spectral_size() [2/2]
size_t YlmSpherepack::spectral_size () const inline noexcept
Sizes in physical and spectral space for this instance.
Referenced by interpolate_from_coefs(), prolong_or_restrict(), and set_up_interpolation_info().
theta_phi_points()
std::array< DataVector, 2 > YlmSpherepack::theta_phi_points () const noexcept
Collocation points theta and phi.
References phi_points(), physical_size(), and theta_points().
Referenced by physical_extents().
theta_points()
const std::vector< double > & YlmSpherepack::theta_points () const noexcept
Collocation points theta and phi.
References ERROR, gaqd_(), and UNLIKELY.
Referenced by physical_extents(), second_derivative(), and theta_phi_points().
The documentation for this class was generated from the following files:
src/ApparentHorizons/YlmSpherepack.hpp
src/ApparentHorizons/YlmSpherepack.cpp