SpECTRE: vis::VolumeFile Class Reference
vis::VolumeFile Class Reference
HDF5
Writes out volume data as an HDF5 file and an XDMF file to be visualized in ParaView or VisIt.
#include <VolumeDataFile.hpp>
Public Member Functions
VolumeFile (std::string file_name, int format_id)
Open a file for volume data output.
VolumeFile (const VolumeFile &)=delete
VolumeFile & operator= (const VolumeFile &)=delete
VolumeFile (VolumeFile &&)=delete
VolumeFile & operator= (VolumeFile &&)=delete
~VolumeFile ()
void write_xdmf_time (double time)
template<size_t Dim, typename Fr >
void write_element_connectivity_and_coordinates (double time, const tnsr::I< DataVector, Dim, Fr > &grid_coordinates, const Index< Dim > &extents, const std::string &element_id, const std::vector< std::string > &coordinate_names={"x-coord", "y-coord", "z-coord"})
template<size_t Dim>
void write_element_data (std::unordered_map< std::string, std::pair< std::vector< std::string >, std::vector< DataVector >>> vars_map, const Index< Dim > &extents, const std::string &element_id)
Write the extents into the volume HDF5 file for the specific element.
Detailed Description
Writes out volume data as an HDF5 file and an XDMF file to be visualized in ParaView or VisIt.
Constructor & Destructor Documentation
VolumeFile() [1/3]
vis::VolumeFile::VolumeFile (std::string file_name, int format_id)
Open a file for volume data output.
VolumeFile() [2/3]
vis::VolumeFile::VolumeFile (const VolumeFile &) delete
VolumeFile() [3/3]
vis::VolumeFile::VolumeFile (VolumeFile &&) delete
~VolumeFile()
vis::VolumeFile::~VolumeFile ()
References CHECK_H5.
Member Function Documentation
operator=() [1/2]
VolumeFile& vis::VolumeFile::operator= (const VolumeFile &) delete
operator=() [2/2]
VolumeFile& vis::VolumeFile::operator= (VolumeFile &&) delete
write_element_connectivity_and_coordinates()
template<size_t Dim, typename Fr > void vis::VolumeFile::write_element_connectivity_and_coordinates (double time, const tnsr::I< DataVector, Dim, Fr > & grid_coordinates, const Index< Dim > & extents, const std::string & element_id, const std::vector< std::string > & coordinate_names = {"x-coord", "y-coord", "z-coord"})
Write the time, extents, connectivity and grid coordinates into the volume HDF5 file for the specific element.
Parameters
time the coordinate time
grid_coordinates the coordinates of the grid
extents the extents of the element
element_id the name/ID of the element
coordinate_names the names of the grid coordinates
References h5::ReadWrite, and h5::write_data().
write_element_data()
template<size_t Dim> void vis::VolumeFile::write_element_data (std::unordered_map< std::string, std::pair< std::vector< std::string >, std::vector< DataVector >>> vars_map, const Index< Dim > & extents, const std::string & element_id)
Write the extents into the volume HDF5 file for the specific element.
Parameters
vars_map the map storing all the variables to be written
extents the extents of the element
element_id the name/ID of the element
References ASSERT, CHECK_H5, ERROR, h5::h5_type(), h5::ReadWrite, and h5::write_data().
write_xdmf_time()
void vis::VolumeFile::write_xdmf_time (double time)
Writes the current time into the XDMF file and must only be called once per time step. write_xdmf_time() must also be called before looping over the elements and calling write_element_connectivity_and_coordinates()
Parameters
time the coordinate time
References h5::ReadWrite, and h5::write_time().
The documentation for this class was generated from the following files:
src/IO/VolumeDataFile.hpp
src/IO/VolumeDataFile.cpp