SpECTRE: Block< VolumeDim, TargetFrame > Class Template Reference
Block< VolumeDim, TargetFrame > Class Template Reference
Computational Domain
A Block<VolumeDim> is a region of a VolumeDim-dimensional computational domain that defines the root node of a tree which is used to construct the Elements that cover a region of the computational domain.
#include <Block.hpp>
Public Member Functions
Block (std::unique_ptr< CoordinateMapBase< Frame::Logical, TargetFrame, VolumeDim >> &&map, size_t id, std::unordered_map< Direction< VolumeDim >, BlockNeighbor< VolumeDim >> neighbors)
Block ()=default
~Block ()=default
Block (const Block &)=delete
Block (Block &&)=default
Block & operator= (const Block &)=delete
Block & operator= (Block &&)=default
const CoordinateMapBase< Frame::Logical, TargetFrame, VolumeDim > & coordinate_map () const noexcept
size_t id () const noexcept
A unique identifier for the Block that is in the range [0, number_of_blocks -1] where number_of_blocks is the number of Blocks that cover the computational domain.
const std::unordered_map< Direction< VolumeDim >, BlockNeighbor< VolumeDim > > & neighbors () const noexcept
Information about the neighboring Blocks.
const std::unordered_set< Direction< VolumeDim > > & external_boundaries () const noexcept
The directions of the faces of the Block that are external boundaries.
void pup (PUP::er &p)
Serialization for Charm++.
Detailed Description
template<size_t VolumeDim, typename TargetFrame>
class Block< VolumeDim, TargetFrame >
A Block<VolumeDim> is a region of a VolumeDim-dimensional computational domain that defines the root node of a tree which is used to construct the Elements that cover a region of the computational domain.
Each codimension 1 boundary of a Block<VolumeDim> is either an external boundary or identical to a boundary of one other Block.
A Block has logical coordinates that go from -1 to +1 in each dimension. The global coordinates are obtained from the logical coordinates from the Coordinatemap: CoordinateMap::operator() takes Points in the Logical Frame (i.e., logical coordinates) and returns Points in the Grid Frame (i.e., global coordinates).
Constructor & Destructor Documentation
Block() [1/4]
template<size_t VolumeDim, typename TargetFrame > Block< VolumeDim, TargetFrame >::Block (std::unique_ptr< CoordinateMapBase< Frame::Logical, TargetFrame, VolumeDim >> && map, size_t id, std::unordered_map< Direction< VolumeDim >, BlockNeighbor< VolumeDim >> neighbors)
Parameters
map the CoordinateMap.
id a unique ID.
neighbors info about the Blocks that share a codimension 1 boundary with this Block.
Block() [2/4]
template<size_t VolumeDim, typename TargetFrame> Block< VolumeDim, TargetFrame >::Block () default
~Block()
template<size_t VolumeDim, typename TargetFrame> Block< VolumeDim, TargetFrame >::~Block () default
Block() [3/4]
template<size_t VolumeDim, typename TargetFrame> Block< VolumeDim, TargetFrame >::Block (const Block< VolumeDim, TargetFrame > &) delete
Block() [4/4]
template<size_t VolumeDim, typename TargetFrame> Block< VolumeDim, TargetFrame >::Block (Block< VolumeDim, TargetFrame > &&) default
Member Function Documentation
coordinate_map()
template<size_t VolumeDim, typename TargetFrame> const CoordinateMapBase<Frame::Logical, TargetFrame, VolumeDim>& Block< VolumeDim, TargetFrame >::coordinate_map () const inline noexcept
external_boundaries()
template<size_t VolumeDim, typename TargetFrame> const std::unordered_set<Direction<VolumeDim> >& Block< VolumeDim, TargetFrame >::external_boundaries () const inline noexcept
The directions of the faces of the Block that are external boundaries.
References operator!=(), operator<<(), operator==(), and Block< VolumeDim, TargetFrame >::pup().
Referenced by operator<<().
id()
template<size_t VolumeDim, typename TargetFrame> size_t Block< VolumeDim, TargetFrame >::id () const inline noexcept
A unique identifier for the Block that is in the range [0, number_of_blocks -1] where number_of_blocks is the number of Blocks that cover the computational domain.
Referenced by operator<<().
neighbors()
template<size_t VolumeDim, typename TargetFrame> const std::unordered_map<Direction<VolumeDim>, BlockNeighbor<VolumeDim> >& Block< VolumeDim, TargetFrame >::neighbors () const inline noexcept
Information about the neighboring Blocks.
Referenced by operator<<().
operator=() [1/2]
template<size_t VolumeDim, typename TargetFrame> Block& Block< VolumeDim, TargetFrame >::operator= (const Block< VolumeDim, TargetFrame > &) delete
operator=() [2/2]
template<size_t VolumeDim, typename TargetFrame> Block& Block< VolumeDim, TargetFrame >::operator= (Block< VolumeDim, TargetFrame > &&) default
pup()
template<size_t VolumeDim, typename TargetFrame > void Block< VolumeDim, TargetFrame >::pup (PUP::er & p)
Serialization for Charm++.
Referenced by Block< VolumeDim, TargetFrame >::external_boundaries().
The documentation for this class was generated from the following files:
src/Domain/Block.hpp
src/Domain/Block.cpp