SpECTRE: DomainCreators::Interval Class Reference
DomainCreators::Interval Class Reference
Domain Creators
Create a 1D Domain consisting of a single Block.
#include <Interval.hpp>
Classes
struct InitialGridPoints
struct InitialRefinement
struct IsPeriodicIn
struct LowerBound
struct UpperBound
Public Types
using options = tmpl::list< LowerBound, UpperBound, IsPeriodicIn, InitialRefinement, InitialGridPoints >
Public Types inherited from DomainCreator< 1, Frame::Inertial >
using creatable_classes = typename DomainCreators_detail::domain_creators< VolumeDim >::type
Public Member Functions
Interval (typename LowerBound::type lower_x, typename UpperBound::type upper_x, typename IsPeriodicIn::type is_periodic_in_x, typename InitialRefinement::type initial_refinement_level_x, typename InitialGridPoints::type initial_number_of_grid_points_in_x) noexcept
Interval ()=default
Interval (const Interval &)=delete
Interval (Interval &&) noexcept=default
Interval & operator= (const Interval &)=delete
Interval & operator= (Interval &&) noexcept=default
~Interval () override=default
Interval (CkMigrateMessage *) noexcept
Domain< 1, Frame::Inertial > create_domain () const noexcept override
std::array< size_t, 1 > initial_extents (size_t block_index) const noexcept override
Obtain the initial grid extents of the block with the given index.
std::array< size_t, 1 > initial_refinement_levels (size_t block_index) const noexcept override
Obtain the initial refinement levels of the block with the given index.
Public Member Functions inherited from DomainCreator< 1, Frame::Inertial >
DomainCreator ()=default
DomainCreator (const DomainCreator< VolumeDim, Frame::Inertial > &)=delete
DomainCreator (DomainCreator< VolumeDim, Frame::Inertial > &&) noexcept=default
DomainCreator< VolumeDim, Frame::Inertial > & operator= (const DomainCreator< VolumeDim, Frame::Inertial > &)=delete
DomainCreator< VolumeDim, Frame::Inertial > & operator= (DomainCreator< VolumeDim, Frame::Inertial > &&) noexcept=default
virtual ~DomainCreator ()=default
Static Public Attributes
static constexpr OptionString_t help = {"Creates a 1D interval."}
Detailed Description
Create a 1D Domain consisting of a single Block.
Member Typedef Documentation
options
using DomainCreators::Interval::options = tmpl::list<LowerBound, UpperBound, IsPeriodicIn, InitialRefinement, InitialGridPoints>
Constructor & Destructor Documentation
Interval() [1/5]
DomainCreators::Interval::Interval (typename LowerBound::type lower_x, typename UpperBound::type upper_x, typename IsPeriodicIn::type is_periodic_in_x, typename InitialRefinement::type initial_refinement_level_x, typename InitialGridPoints::type initial_number_of_grid_points_in_x) noexcept
Interval() [2/5]
DomainCreators::Interval::Interval () default
Interval() [3/5]
DomainCreators::Interval::Interval (const Interval &) delete
Interval() [4/5]
DomainCreators::Interval::Interval (Interval &&) default noexcept
~Interval()
DomainCreators::Interval::~Interval () override default
Interval() [5/5]
DomainCreators::Interval::Interval (CkMigrateMessage *) inline explicit noexcept
References create_domain(), initial_extents(), and initial_refinement_levels().
Member Function Documentation
create_domain()
Domain< 1, Frame::Inertial > DomainCreators::Interval::create_domain () const override virtual noexcept
Implements DomainCreator< 1, Frame::Inertial >.
References make_vector().
Referenced by Interval().
initial_extents()
std::array< size_t, 1 > DomainCreators::Interval::initial_extents (size_t block_index) const override virtual noexcept
Obtain the initial grid extents of the block with the given index.
Implements DomainCreator< 1, Frame::Inertial >.
References ASSERT.
Referenced by Interval().
initial_refinement_levels()
std::array< size_t, 1 > DomainCreators::Interval::initial_refinement_levels (size_t block_index) const override virtual noexcept
Obtain the initial refinement levels of the block with the given index.
Implements DomainCreator< 1, Frame::Inertial >.
References ASSERT.
Referenced by Interval().
operator=() [1/2]
Interval& DomainCreators::Interval::operator= (const Interval &) delete
operator=() [2/2]
Interval& DomainCreators::Interval::operator= (Interval &&) default noexcept
Member Data Documentation
help
constexpr OptionString_t DomainCreators::Interval::help = {"Creates a 1D interval."} static
The documentation for this class was generated from the following files:
src/Domain/DomainCreators/Interval.hpp
src/Domain/DomainCreators/Interval.cpp