SpECTRE: AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox > Class Template Reference
AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox > Class Template Reference
Parallelization
A distributed object (Charm++ Chare) that executes a series of Actions and is capable of sending and receiving data. Acts as an interface to Charm++.
#include <Algorithm.hpp>
Public Types
using metavariables = Metavariables
The metavariables class passed to the Algorithm.
using actions_list = typelist< ActionsPack... >
List of Actions in the order they will be executed.
using inbox_tags_list = typelist< InboxTagsPack... >
List off all the Tags that can be received into the Inbox.
using array_index = ArrayIndex
The type of the object used to identify the element of the array, group or nodegroup spatially. The default should be an int.
using parallel_component = ParallelComponent
using chare_type = ChareType
The type of the Chare.
using cproxy_type = typename ChareType::template cproxy< ParallelComponent, metavariables, actions_list, inbox_tags_list, array_index, InitialDataBox >
The Charm++ proxy object type.
using cbase_type = typename ChareType::template cbase< ParallelComponent, metavariables, actions_list, inbox_tags_list, array_index, InitialDataBox >
The Charm++ base object type.
Public Member Functions
AlgorithmImpl (const Parallel::CProxy_ConstGlobalCache< metavariables > &global_cache_proxy) noexcept
Constructor used by Main to initialize the algorithm.
constexpr AlgorithmImpl (CkMigrateMessage *) noexcept
Charm++ migration constructor, used after a chare is migrated.
template<typename Action , typename Arg >
void reduction_action (Arg arg) noexcept
Calls the apply function Action after a reduction has been completed.
template<typename Action , typename... Args>
void explicit_single_action (std::tuple< Args... > args) noexcept
Explicitly call the action Action. If the returned DataBox type is not one of the types of the algorithm then a compilation error occurs.
template<typename Action >
void explicit_single_action () noexcept
template<typename Action , typename... Args, Requires<(sizeof...(Args), cpp17::is_same_v< Parallel::Algorithms::Nodegroup, ChareType >)> = nullptr>
void threaded_single_action (Args &&... args) noexcept
Call an Action on a local nodegroup requiring the Action to handle thread safety.
template<typename ReceiveTag , typename ReceiveData_t >
void receive_data (typename ReceiveTag::temporal_id instance, ReceiveData_t &&t, bool enable_if_disabled=false) noexcept
Receive data and store it in the Inbox, and try to continue executing the algorithm.
constexpr void perform_algorithm () noexcept
Start evaluating the algorithm until the is_ready function of an Action returns false, or an Action returns with terminate set to true
constexpr void set_terminate (bool t) noexcept
Tell the Algorithm it should no longer execute the algorithm. This does not mean that the execution of the program is terminated, but only that the algorithm has terminated. An algorithm can be restarted by pass true as the second argument to the receive_data method.
constexpr bool get_terminate () const noexcept
Check if an algorithm should continue being evaluated.
Detailed Description
template<typename ParallelComponent, typename ChareType, typename Metavariables, typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex, typename InitialDataBox>
class AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >
A distributed object (Charm++ Chare) that executes a series of Actions and is capable of sending and receiving data. Acts as an interface to Charm++.
Different Types of Algorithms
Charm++ chares can be one of four types, which is specified by the first template parameter, ChareType. The four available types of Algorithms are:
A Parallel::Algorithms::Singleton where there is only one in the entire execution of the program.
A Parallel::Algorithms::Array which holds zero or more elements each of which is a distributed object on some core. An array can grow and shrink in size dynamically if need be and can also be bound to another array. That is, the bound array has the same number of elements as the array it is bound to, and elements with the same ID are on the same core.
A Parallel::Algorithms::Group, which is an array but there is one element per core and they are not able to be moved around between cores. These are typically useful for gathering data from array elements on their core, and then processing or reducing it.
A Parallel::Algorithms::Nodegroup, which is similar to a group except that there is one element per node. For Charm++ SMP (shared memory parallelism) builds a node corresponds to the usual definition of a node on a supercomputer. However, for non-SMP builds nodes and cores are equivalent. An important difference between groups and nodegroups is that entry methods (remote calls to functions) are not threadsafe on nodegroups. It is up to the person writing the Actions that will be executed on the Nodegroup Algorithm to ensure they are threadsafe.
What is an Algorithm?
An Algorithm is a distributed object, a Charm++ chare, that repeatedly executes a series of Actions. An Action is a struct that has a static apply function with signature:
template <typename... DbTags, typename... InboxTags, typename Metavariables,
typename ArrayIndex,  typename ActionList>
static auto  apply(db::DataBox<tmpl::list<DbTags...>>& box,
                   tuples::TaggedTuple<InboxTags...>& inboxes,
                   const ConstGlobalCache<Metavariables>& cache,
                   const ArrayIndex& array_index,
                   const TemporalId& temporal_id, const ActionList meta);
Note that any of the arguments can be const or non-const references except array_index, which must be a const&.
Explicit instantiations of entry methods
The code in src/Parallel/CharmMain.cpp registers all entry methods, and if one is not properly registered then a static_assert explains how to have it be registered. If there is a bug in the implementation and an entry method isn't being registered or hitting a static_assert then Charm++ will give an error of the following form:
* registration happened after init Entry point: explicit_single_action(), addr:
* 0x555a3d0e2090
* ------------- Processor 0 Exiting: Called CmiAbort ------------
* Reason: Did you forget to instantiate a templated entry method in a .ci file?
*
If you encounter this issue please file a bug report supplying everything necessary to reproduce the issue.
Member Typedef Documentation
actions_list
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > using AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::actions_list = typelist<ActionsPack...>
List of Actions in the order they will be executed.
array_index
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > using AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::array_index = ArrayIndex
The type of the object used to identify the element of the array, group or nodegroup spatially. The default should be an int.
cbase_type
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > using AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::cbase_type = typename ChareType::template cbase<ParallelComponent, metavariables, actions_list, inbox_tags_list, array_index, InitialDataBox>
The Charm++ base object type.
chare_type
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > using AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::chare_type = ChareType
The type of the Chare.
cproxy_type
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > using AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::cproxy_type = typename ChareType::template cproxy<ParallelComponent, metavariables, actions_list, inbox_tags_list, array_index, InitialDataBox>
The Charm++ proxy object type.
inbox_tags_list
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > using AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::inbox_tags_list = typelist<InboxTagsPack...>
List off all the Tags that can be received into the Inbox.
metavariables
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > using AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::metavariables = Metavariables
The metavariables class passed to the Algorithm.
parallel_component
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > using AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::parallel_component = ParallelComponent
Constructor & Destructor Documentation
AlgorithmImpl() [1/2]
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::AlgorithmImpl (const Parallel::CProxy_ConstGlobalCache< metavariables > & global_cache_proxy) explicit noexcept
Constructor used by Main to initialize the algorithm.
AlgorithmImpl() [2/2]
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > constexpr AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::AlgorithmImpl (CkMigrateMessage *) explicit noexcept
Charm++ migration constructor, used after a chare is migrated.
Member Function Documentation
explicit_single_action() [1/2]
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > template<typename Action , typename... Args> void AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::explicit_single_action (std::tuple< Args... > args) noexcept
Explicitly call the action Action. If the returned DataBox type is not one of the types of the algorithm then a compilation error occurs.
explicit_single_action() [2/2]
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > template<typename Action > void AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::explicit_single_action () noexcept
get_terminate()
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > constexpr bool AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::get_terminate () const inline noexcept
Check if an algorithm should continue being evaluated.
References db::apply(), ASSERT, ERROR, tt::is_a_v, Parallel::lock(), make_overloader(), SPECTRE_JUST_ALWAYS_INLINE, Parallel::unlock(), Parallel::value, and Parallel::wall_time().
perform_algorithm()
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > constexpr void AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::perform_algorithm () noexcept
Start evaluating the algorithm until the is_ready function of an Action returns false, or an Action returns with terminate set to true
receive_data()
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > template<typename ReceiveTag , typename ReceiveData_t > void AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::receive_data (typename ReceiveTag::temporal_id instance, ReceiveData_t && t, bool enable_if_disabled = false) noexcept
Receive data and store it in the Inbox, and try to continue executing the algorithm.
When an algorithm has terminated it can be restarted by passing enable_if_disabled = true. This allows long-term disabling and re-enabling of algorithms
reduction_action()
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > template<typename Action , typename Arg > void AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::reduction_action (Arg arg) noexcept
Calls the apply function Action after a reduction has been completed.
The apply function must take arg as its last argument.
set_terminate()
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > constexpr void AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::set_terminate (bool t) inline noexcept
Tell the Algorithm it should no longer execute the algorithm. This does not mean that the execution of the program is terminated, but only that the algorithm has terminated. An algorithm can be restarted by pass true as the second argument to the receive_data method.
threaded_single_action()
template<typename ParallelComponent , typename ChareType , typename Metavariables , typename... ActionsPack, typename... InboxTagsPack, typename ArrayIndex , typename InitialDataBox > template<typename Action , typename... Args, Requires<(sizeof...(Args), cpp17::is_same_v< Parallel::Algorithms::Nodegroup, ChareType >)> = nullptr> void AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::threaded_single_action (Args &&... args) noexcept
Call an Action on a local nodegroup requiring the Action to handle thread safety.
The CmiNodelock of the nodegroup is passed to the Action instead of the action_list as a const gsl::not_null<CmiNodelock*>&. The node lock can be locked with the Parallel::lock() function, and unlocked with Parallel::unlock(). Parallel::try_lock() is also provided in case something useful can be done if the lock couldn't be acquired.
The documentation for this class was generated from the following file:
src/Parallel/Algorithm.hpp