SpECTRE: ScalarWave::Solutions::PlaneWave< Dim > Class Template Reference
ScalarWave::Solutions::PlaneWave< Dim > Class Template Reference
A plane wave solution to the Euclidean wave equation.
#include <PlaneWave.hpp>
Classes
struct Center
struct Profile
struct WaveVector
Public Types
using options = tmpl::list< WaveVector, Center, Profile >
Public Member Functions
PlaneWave (std::array< double, Dim > wave_vector, std::array< double, Dim > center, std::unique_ptr< MathFunction< 1 >> &&profile) noexcept
PlaneWave (const PlaneWave &) noexcept=delete
PlaneWave & operator= (const PlaneWave &) noexcept=delete
PlaneWave (PlaneWave &&) noexcept=default
PlaneWave & operator= (PlaneWave &&) noexcept=default
~PlaneWave () noexcept=default
template<typename T >
Scalar< T > psi (const tnsr::I< T, Dim > &x, double t) const noexcept
The value of the scalar field.
template<typename T >
Scalar< T > dpsi_dt (const tnsr::I< T, Dim > &x, double t) const noexcept
The time derivative of the scalar field.
template<typename T >
tnsr::i< T, Dim > dpsi_dx (const tnsr::I< T, Dim > &x, double t) const noexcept
The spatial derivatives of the scalar field.
template<typename T >
Scalar< T > d2psi_dt2 (const tnsr::I< T, Dim > &x, double t) const noexcept
The second time derivative of the scalar field.
template<typename T >
tnsr::i< T, Dim > d2psi_dtdx (const tnsr::I< T, Dim > &x, double t) const noexcept
The second mixed derivatives of the scalar field.
template<typename T >
tnsr::ii< T, Dim > d2psi_dxdx (const tnsr::I< T, Dim > &x, double t) const noexcept
The second spatial derivatives of the scalar field.
Static Public Attributes
static constexpr OptionString_t help
Detailed Description
template<size_t Dim>
class ScalarWave::Solutions::PlaneWave< Dim >
A plane wave solution to the Euclidean wave equation.
The solution is given by \(\Psi(\vec{x},t) = F(u(\vec{x},t))\) where the profile \(F\) of the plane wave is an arbitrary one-dimensional function of \(u = \vec{k} \cdot (\vec{x} - \vec{x_o}) - \omega t\) with the wave vector \(\vec{k}\), the frequency \(\omega = ||\vec{k}||\) and initial center of the profile \(\vec{x_o}\).
Template Parameters
Dim the spatial dimension of the solution
Member Typedef Documentation
options
template<size_t Dim> using ScalarWave::Solutions::PlaneWave< Dim >::options = tmpl::list<WaveVector, Center, Profile>
Constructor & Destructor Documentation
PlaneWave() [1/3]
template<size_t Dim> ScalarWave::Solutions::PlaneWave< Dim >::PlaneWave (std::array< double, Dim > wave_vector, std::array< double, Dim > center, std::unique_ptr< MathFunction< 1 >> && profile) noexcept
PlaneWave() [2/3]
template<size_t Dim> ScalarWave::Solutions::PlaneWave< Dim >::PlaneWave (const PlaneWave< Dim > &) delete noexcept
PlaneWave() [3/3]
template<size_t Dim> ScalarWave::Solutions::PlaneWave< Dim >::PlaneWave (PlaneWave< Dim > &&) default noexcept
~PlaneWave()
template<size_t Dim> ScalarWave::Solutions::PlaneWave< Dim >::~PlaneWave () default noexcept
Member Function Documentation
d2psi_dt2()
template<size_t Dim> template<typename T > Scalar< T > ScalarWave::Solutions::PlaneWave< Dim >::d2psi_dt2 (const tnsr::I< T, Dim > & x, double t) const noexcept
The second time derivative of the scalar field.
References square().
d2psi_dtdx()
template<size_t Dim> template<typename T > tnsr::i< T, Dim > ScalarWave::Solutions::PlaneWave< Dim >::d2psi_dtdx (const tnsr::I< T, Dim > & x, double t) const noexcept
The second mixed derivatives of the scalar field.
References gsl::at().
d2psi_dxdx()
template<size_t Dim> template<typename T > tnsr::ii< T, Dim > ScalarWave::Solutions::PlaneWave< Dim >::d2psi_dxdx (const tnsr::I< T, Dim > & x, double t) const noexcept
The second spatial derivatives of the scalar field.
References gsl::at(), and GENERATE_INSTANTIATIONS.
dpsi_dt()
template<size_t Dim> template<typename T > Scalar< T > ScalarWave::Solutions::PlaneWave< Dim >::dpsi_dt (const tnsr::I< T, Dim > & x, double t) const noexcept
The time derivative of the scalar field.
dpsi_dx()
template<size_t Dim> template<typename T > tnsr::i< T, Dim > ScalarWave::Solutions::PlaneWave< Dim >::dpsi_dx (const tnsr::I< T, Dim > & x, double t) const noexcept
The spatial derivatives of the scalar field.
References gsl::at().
operator=() [1/2]
template<size_t Dim> PlaneWave& ScalarWave::Solutions::PlaneWave< Dim >::operator= (const PlaneWave< Dim > &) delete noexcept
operator=() [2/2]
template<size_t Dim> PlaneWave& ScalarWave::Solutions::PlaneWave< Dim >::operator= (PlaneWave< Dim > &&) default noexcept
psi()
template<size_t Dim> template<typename T > Scalar< T > ScalarWave::Solutions::PlaneWave< Dim >::psi (const tnsr::I< T, Dim > & x, double t) const noexcept
The value of the scalar field.
Member Data Documentation
help
template<size_t Dim> constexpr OptionString_t ScalarWave::Solutions::PlaneWave< Dim >::help static
Initial value:
= {
      "A plane wave solution of the Euclidean wave equation"}
The documentation for this class was generated from the following files:
src/PointwiseFunctions/AnalyticSolutions/WaveEquation/PlaneWave.hpp
src/PointwiseFunctions/AnalyticSolutions/WaveEquation/PlaneWave.cpp