SpECTRE: TimeSteppers::RungeKutta3 Class Reference
TimeSteppers::RungeKutta3 Class Reference
Time Steppers
A "strong stability-preserving" 3rd-order Runge-Kutta time-stepper. Major reference: J. Hesthaven & T. Warburton, Nodal Discontinuous Galerkin Methods. section 5.7.
#include <RungeKutta3.hpp>
Public Types
using options = tmpl::list<>
Public Member Functions
RungeKutta3 ()=default
RungeKutta3 (const RungeKutta3 &) noexcept=default
RungeKutta3 & operator= (const RungeKutta3 &) noexcept=default
RungeKutta3 (RungeKutta3 &&) noexcept=default
RungeKutta3 & operator= (RungeKutta3 &&) noexcept=default
~RungeKutta3 () noexcept override=default
template<typename Vars , typename DerivVars >
void update_u (gsl::not_null< Vars *> u, const std::deque< std::tuple< Time, Vars, DerivVars >> &history, const TimeDelta &time_step) const noexcept
template<typename BoundaryVars , typename FluxVars , typename Coupling >
BoundaryVars compute_boundary_delta (const Coupling &coupling, const std::vector< std::deque< std::tuple< Time, BoundaryVars, FluxVars >>> &history, const TimeDelta &time_step) const noexcept
template<typename Vars , typename DerivVars >
std::deque< std::tuple< Time, Vars, DerivVars > >::const_iterator needed_history (const std::deque< std::tuple< Time, Vars, DerivVars >> &history) const noexcept
template<typename BoundaryVars , typename FluxVars >
std::vector< typename std::deque< std::tuple< Time, BoundaryVars, FluxVars > >::const_iterator > needed_boundary_history (const std::vector< std::deque< std::tuple< Time, BoundaryVars, FluxVars >>> &history, const TimeDelta &time_step) const noexcept
size_t number_of_substeps () const noexcept override
size_t number_of_past_steps () const noexcept override
bool is_self_starting () const noexcept override
double stable_step () const noexcept override
TimeId next_time_id (const TimeId &current_id, const TimeDelta &time_step) const noexcept override
WRAPPED_PUPable_decl_template (RungeKutta3)
RungeKutta3 (CkMigrateMessage *) noexcept
void pup (PUP::er &p) noexcept override
template<typename Vars , typename DerivVars >
void update_u (const gsl::not_null< Vars *> u, const std::deque< std::tuple< Time, Vars, DerivVars >> &history, const TimeDelta &time_step) const noexcept
template<typename Vars , typename UnusedData , typename DerivVars >
void step_work (const gsl::not_null< Vars *> u, const std::deque< std::tuple< Time, Vars, UnusedData >> &history, const TimeDelta &time_step, const DerivVars &dt_vars) const noexcept
Static Public Attributes
static constexpr OptionString_t help
Detailed Description
A "strong stability-preserving" 3rd-order Runge-Kutta time-stepper. Major reference: J. Hesthaven & T. Warburton, Nodal Discontinuous Galerkin Methods. section 5.7.
Member Typedef Documentation
options
using TimeSteppers::RungeKutta3::options = tmpl::list<>
Constructor & Destructor Documentation
RungeKutta3() [1/4]
TimeSteppers::RungeKutta3::RungeKutta3 () default
RungeKutta3() [2/4]
TimeSteppers::RungeKutta3::RungeKutta3 (const RungeKutta3 &) default noexcept
RungeKutta3() [3/4]
TimeSteppers::RungeKutta3::RungeKutta3 (RungeKutta3 &&) default noexcept
~RungeKutta3()
TimeSteppers::RungeKutta3::~RungeKutta3 () override default noexcept
RungeKutta3() [4/4]
TimeSteppers::RungeKutta3::RungeKutta3 (CkMigrateMessage *) inline explicit noexcept
Member Function Documentation
compute_boundary_delta()
template<typename BoundaryVars , typename FluxVars , typename Coupling > BoundaryVars TimeSteppers::RungeKutta3::compute_boundary_delta (const Coupling & coupling, const std::vector< std::deque< std::tuple< Time, BoundaryVars, FluxVars >>> & history, const TimeDelta & time_step) const noexcept
References make_not_null().
is_self_starting()
bool TimeSteppers::RungeKutta3::is_self_starting () const override noexcept
needed_boundary_history()
template<typename BoundaryVars , typename FluxVars > std::vector< typename std::deque< std::tuple< Time, BoundaryVars, FluxVars > >::const_iterator > TimeSteppers::RungeKutta3::needed_boundary_history (const std::vector< std::deque< std::tuple< Time, BoundaryVars, FluxVars >>> & history, const TimeDelta & time_step) const noexcept
References ASSERT, and number_of_substeps().
needed_history()
template<typename Vars , typename DerivVars > std::deque< std::tuple< Time, Vars, DerivVars > >::const_iterator TimeSteppers::RungeKutta3::needed_history (const std::deque< std::tuple< Time, Vars, DerivVars >> & history) const noexcept
References number_of_substeps().
next_time_id()
TimeId TimeSteppers::RungeKutta3::next_time_id (const TimeId & current_id, const TimeDelta & time_step) const override noexcept
References ERROR, TimeId::substep, and TimeId::time.
number_of_past_steps()
size_t TimeSteppers::RungeKutta3::number_of_past_steps () const override noexcept
number_of_substeps()
size_t TimeSteppers::RungeKutta3::number_of_substeps () const override noexcept
Referenced by needed_boundary_history(), and needed_history().
operator=() [1/2]
RungeKutta3& TimeSteppers::RungeKutta3::operator= (const RungeKutta3 &) default noexcept
operator=() [2/2]
RungeKutta3& TimeSteppers::RungeKutta3::operator= (RungeKutta3 &&) default noexcept
pup()
void TimeSteppers::RungeKutta3::pup (PUP::er & p) inline override noexcept
stable_step()
double TimeSteppers::RungeKutta3::stable_step () const override noexcept
step_work()
template<typename Vars , typename UnusedData , typename DerivVars > void TimeSteppers::RungeKutta3::step_work (const gsl::not_null< Vars *> u, const std::deque< std::tuple< Time, Vars, UnusedData >> & history, const TimeDelta & time_step, const DerivVars & dt_vars) const noexcept
References ERROR.
update_u() [1/2]
template<typename Vars , typename DerivVars > void TimeSteppers::RungeKutta3::update_u (gsl::not_null< Vars *> u, const std::deque< std::tuple< Time, Vars, DerivVars >> & history, const TimeDelta & time_step) const noexcept
update_u() [2/2]
template<typename Vars , typename DerivVars > void TimeSteppers::RungeKutta3::update_u (const gsl::not_null< Vars *> u, const std::deque< std::tuple< Time, Vars, DerivVars >> & history, const TimeDelta & time_step) const noexcept
WRAPPED_PUPable_decl_template()
TimeSteppers::RungeKutta3::WRAPPED_PUPable_decl_template (RungeKutta3)
Member Data Documentation
help
constexpr OptionString_t TimeSteppers::RungeKutta3::help static
Initial value:
= {
      "A third-order strong stability-preserving Runge-Kutta time-stepper."}
The documentation for this class was generated from the following files:
src/Time/TimeSteppers/RungeKutta3.hpp
src/Time/TimeSteppers/RungeKutta3.cpp