SpECTRE: TimeSteppers::AdamsBashforthN Class Reference
TimeSteppers::AdamsBashforthN Class Reference
Time Steppers
An Nth Adams-Bashforth time stepper.
#include <AdamsBashforthN.hpp>
Classes
struct SelfStart
struct TargetOrder
Public Types
using options = tmpl::list< TargetOrder, SelfStart >
Public Member Functions
AdamsBashforthN ()=default
AdamsBashforthN (size_t target_order, bool self_start, const OptionContext &context={})
AdamsBashforthN (const AdamsBashforthN &) noexcept=default
AdamsBashforthN & operator= (const AdamsBashforthN &) noexcept=default
AdamsBashforthN (AdamsBashforthN &&) noexcept=default
AdamsBashforthN & operator= (AdamsBashforthN &&) noexcept=default
~AdamsBashforthN () noexcept override=default
template<typename Vars , typename DerivVars >
void update_u (gsl::not_null< Vars *> u, const std::deque< std::tuple< Time, Vars, DerivVars >> &history, const TimeDelta &time_step) const noexcept
template<typename BoundaryVars , typename FluxVars , typename Coupling >
BoundaryVars compute_boundary_delta (const Coupling &coupling, const std::vector< std::deque< std::tuple< Time, BoundaryVars, FluxVars >>> &history, const TimeDelta &time_step) const noexcept
template<typename Vars , typename DerivVars >
std::deque< std::tuple< Time, Vars, DerivVars > >::const_iterator needed_history (const std::deque< std::tuple< Time, Vars, DerivVars >> &history) const noexcept
template<typename BoundaryVars , typename FluxVars >
std::vector< typename std::deque< std::tuple< Time, BoundaryVars, FluxVars > >::const_iterator > needed_boundary_history (const std::vector< std::deque< std::tuple< Time, BoundaryVars, FluxVars >>> &history, const TimeDelta &time_step) const noexcept
size_t number_of_substeps () const noexcept override
size_t number_of_past_steps () const noexcept override
bool is_self_starting () const noexcept override
double stable_step () const noexcept override
TimeId next_time_id (const TimeId &current_id, const TimeDelta &time_step) const noexcept override
WRAPPED_PUPable_decl_template (AdamsBashforthN)
AdamsBashforthN (CkMigrateMessage *) noexcept
void pup (PUP::er &p) noexcept override
template<typename Vars , typename DerivVars >
void update_u (const gsl::not_null< Vars *> u, const std::deque< std::tuple< Time, Vars, DerivVars >> &history, const TimeDelta &time_step) const noexcept
Static Public Attributes
static constexpr const size_t maximum_order = 8
static constexpr OptionString_t help
Detailed Description
An Nth Adams-Bashforth time stepper.
Member Typedef Documentation
options
using TimeSteppers::AdamsBashforthN::options = tmpl::list<TargetOrder, SelfStart>
Constructor & Destructor Documentation
AdamsBashforthN() [1/5]
TimeSteppers::AdamsBashforthN::AdamsBashforthN () default
AdamsBashforthN() [2/5]
TimeSteppers::AdamsBashforthN::AdamsBashforthN (size_t target_order, bool self_start, const OptionContext & context = {})
References maximum_order, and PARSE_ERROR.
AdamsBashforthN() [3/5]
TimeSteppers::AdamsBashforthN::AdamsBashforthN (const AdamsBashforthN &) default noexcept
AdamsBashforthN() [4/5]
TimeSteppers::AdamsBashforthN::AdamsBashforthN (AdamsBashforthN &&) default noexcept
~AdamsBashforthN()
TimeSteppers::AdamsBashforthN::~AdamsBashforthN () override default noexcept
AdamsBashforthN() [5/5]
TimeSteppers::AdamsBashforthN::AdamsBashforthN (CkMigrateMessage *) inline explicit noexcept
References h5::get_time(), and pup().
Member Function Documentation
compute_boundary_delta()
template<typename BoundaryVars , typename FluxVars , typename Coupling > BoundaryVars TimeSteppers::AdamsBashforthN::compute_boundary_delta (const Coupling & coupling, const std::vector< std::deque< std::tuple< Time, BoundaryVars, FluxVars >>> & history, const TimeDelta & time_step) const noexcept
An explanation of the computation being performed by this function:
We number the sides \(1\) through \(S\), and let the evaluation times on side \(s\) be \(\ldots, t^s_{-1}, t^s_0, t^s_1, \ldots\), with the starting location of the numbering arbitrary. The union of all these sets of times produces the sequence \(\ldots, \tilde{t}_{-1}, \tilde{t}_0, \tilde{t}_1, \ldots\), again numbered arbitrarily. For example, one possible sequence of times for a two-sided boundary is:
\begin{equation} \begin{aligned} \text{Side 1:} \\ \text{Union times:} \\ \text{Side 2:} \end{aligned} \cdots \begin{gathered} t^1_4 \\ \tilde{t}_8 \\ t^2_1 \end{gathered} \leftarrow \Delta \tilde{t}_8 \rightarrow \begin{gathered} \, \\ \tilde{t}_9 \\ t^2_2 \end{gathered} \leftarrow \Delta \tilde{t}_9 \rightarrow \begin{gathered} t^1_5 \\ \tilde{t}_{10} \\ \, \end{gathered} \cdots \end{equation}
We call the indices of the start and end times in the union time set \(n_S\) and \(n_E\), respectively, so for the above example, if we wish to compute the step on side 1 from \(t^1_4\) to \(t^1_5\), we would have \(n_S = 8\) and \(n_E = 10\). The indices of steps on each side containing or starting with union time number \(n\) are denoted \(\vec{m}_n\), so in the above example \(\vec{m}_9 = (4, 2)\). The union indices corresponding to the start of a set of side step indices \(\vec{m}\) are denoted \(\vec{n}_{\vec{m}}\), so in the example \(\vec{n}_{(4, 2)} = (8, 9)\). In the below equations, addition, subtraction, min, and max operations applied to vectors operate on each component individually, i.e., \(\vec{q} + k = (q^1 + k, \ldots, q^S + k)\).
Let \(k\) be the order of the integrator. For a sequence of times \(t^s_{j_s - (k-1)}, \ldots, t^s_{j_s}\) on each side \(s\), we can write the cardinal functions on those times as
\begin{equation} \newcommand\of[1]{\!\!\left(#1\right)} C_{a_1, \ldots, a_S}(t_1, \ldots, t_S; j_1, \ldots, j_S) = \prod_{s=1}^S \ell_{a_s}\of{t_s; t^s_{j_s - (k-1)}, \ldots, t^s_{j_s}}, \end{equation}
with \(\ell_a(t; x_1, \ldots, x_k)\) the Lagrange interpolating polynomials. (Note that we take the indices \(a\) to run from \(1\) to \(k\) here, but from \(0\) to \(k-1\) in the code.) The cardinal function satisfies \(C_{a_1, \ldots, a_S}(t^1_{i_1}, \ldots, t^S_{i_S}; j_1, \ldots, j_S) = \prod_{s=1}^S \delta_{i_s, j_s + a_s - k} \). We write the integral of a cardinal function using an Adams-Bashforth step based on the union times along the diagonal \(t_1 = t_2 = \cdots = t_S\) from \(\tilde{t}_n\) to \(\tilde{t}_{n+1}\) as
\begin{equation} \newcommand\of[1]{\!\!\left(#1\right)} I_{n,\vec{q}} = \Delta \tilde{t}_n \sum_{j = 0}^{k-1} \tilde{\alpha}_{nj} C_{\vec{q}-\vec{m}_n+k} \of{\tilde{t}_{n - j}, \ldots, \tilde{t}_{n - j}; \vec{m}_n}, \end{equation}
where \(\tilde{\alpha}_{nj}\) are the Adams-Bashforth coefficients derived from the union times and \(\vec{q}\) is a vector specifying the cardinal function indices. The boundary delta for the step is then
\begin{equation} \newcommand\mat{\mathbf} \mat{F}_{n_S, n_E} = \mspace{-7mu} \sum_{\vec{q} = \vec{m}_{n_s}-(k-1)}^{\vec{m}_{n_E-1}} \mspace{-4mu} \mat{D}_{\vec{q}} \mspace{-4mu} \sum_{n = \max\left\{n_S, \vec{n}_{\vec{q}} \right\}} ^{\min\left\{n_E, \vec{n}_{\vec{q} + k}\right\} - 1} \mspace{-7mu} I_{n,\vec{q}}, \end{equation}
where \(\mat{D}_{\vec{q}}\) is the coupling function evaluated at the side values at side step indices \(\vec{q}\).
References ASSERT, h5::get_time(), lagrange_polynomial(), make_general_index_iterator(), and Parallel::value.
is_self_starting()
bool TimeSteppers::AdamsBashforthN::is_self_starting () const override noexcept
needed_boundary_history()
template<typename BoundaryVars , typename FluxVars > std::vector< typename std::deque< std::tuple< Time, BoundaryVars, FluxVars > >::const_iterator > TimeSteppers::AdamsBashforthN::needed_boundary_history (const std::vector< std::deque< std::tuple< Time, BoundaryVars, FluxVars >>> & history, const TimeDelta & time_step) const noexcept
References maximum_order.
needed_history()
template<typename Vars , typename DerivVars > std::deque< std::tuple< Time, Vars, DerivVars > >::const_iterator TimeSteppers::AdamsBashforthN::needed_history (const std::deque< std::tuple< Time, Vars, DerivVars >> & history) const noexcept
next_time_id()
TimeId TimeSteppers::AdamsBashforthN::next_time_id (const TimeId & current_id, const TimeDelta & time_step) const override noexcept
References ASSERT, ERROR, maximum_order, and TimeId::time.
number_of_past_steps()
size_t TimeSteppers::AdamsBashforthN::number_of_past_steps () const override noexcept
number_of_substeps()
size_t TimeSteppers::AdamsBashforthN::number_of_substeps () const override noexcept
operator=() [1/2]
AdamsBashforthN& TimeSteppers::AdamsBashforthN::operator= (const AdamsBashforthN &) default noexcept
operator=() [2/2]
AdamsBashforthN& TimeSteppers::AdamsBashforthN::operator= (AdamsBashforthN &&) default noexcept
pup()
void TimeSteppers::AdamsBashforthN::pup (PUP::er & p) override noexcept
Referenced by AdamsBashforthN().
stable_step()
double TimeSteppers::AdamsBashforthN::stable_step () const override noexcept
update_u() [1/2]
template<typename Vars , typename DerivVars > void TimeSteppers::AdamsBashforthN::update_u (gsl::not_null< Vars *> u, const std::deque< std::tuple< Time, Vars, DerivVars >> & history, const TimeDelta & time_step) const noexcept
update_u() [2/2]
template<typename Vars , typename DerivVars > void TimeSteppers::AdamsBashforthN::update_u (const gsl::not_null< Vars *> u, const std::deque< std::tuple< Time, Vars, DerivVars >> & history, const TimeDelta & time_step) const noexcept
References ASSERT, and ERROR.
WRAPPED_PUPable_decl_template()
TimeSteppers::AdamsBashforthN::WRAPPED_PUPable_decl_template (AdamsBashforthN)
Member Data Documentation
help
constexpr OptionString_t TimeSteppers::AdamsBashforthN::help static
Initial value:
= {
      "An Adams-Bashforth Nth order time-stepper. The target order is the\n"
      "order of the method. If a self-starting approach is chosen then the\n"
      "method starts at first order and increases the step-size until the\n"
      "desired order is reached."}
maximum_order
constexpr const size_t TimeSteppers::AdamsBashforthN::maximum_order = 8 static
Referenced by AdamsBashforthN(), needed_boundary_history(), next_time_id(), and TimeSteppers::AdamsBashforthN::TargetOrder::upper_bound().
The documentation for this class was generated from the following files:
src/Time/TimeSteppers/AdamsBashforthN.hpp
src/Time/TimeSteppers/AdamsBashforthN.cpp