SpECTRE: CoordinateMaps::Wedge2D Class Reference
CoordinateMaps::Wedge2D Class Reference
Two dimensional map from the unit square to a wedge, which forms one quadrant of an annulus. The wedge can be oriented in the +/- x or y axis, with the inner and outer radii specifiable.
#include <Wedge2D.hpp>
Public Member Functions
Wedge2D (double inner_radius, double outer_radius, Direction< 2 > positioning_of_wedge)
Wedge2D ()=default
~Wedge2D ()=default
Wedge2D (Wedge2D &&)=default
Wedge2D & operator= (Wedge2D &&)=default
Wedge2D (const Wedge2D &)=default
Wedge2D & operator= (const Wedge2D &)=default
template<typename T >
std::array< std::decay_t< tt::remove_reference_wrapper_t< T > >, 2 > operator() (const std::array< T, 2 > &x) const noexcept
template<typename T >
std::array< std::decay_t< tt::remove_reference_wrapper_t< T > >, 2 > inverse (const std::array< T, 2 > &x) const noexcept
template<typename T >
Tensor< std::decay_t< tt::remove_reference_wrapper_t< T > >, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< 2, UpLo::Up, Frame::NoFrame >, SpatialIndex< 2, UpLo::Lo, Frame::NoFrame > > > jacobian (const std::array< T, 2 > &xi) const noexcept
template<typename T >
Tensor< std::decay_t< tt::remove_reference_wrapper_t< T > >, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< 2, UpLo::Up, Frame::NoFrame >, SpatialIndex< 2, UpLo::Lo, Frame::NoFrame > > > inv_jacobian (const std::array< T, 2 > &xi) const noexcept
void pup (PUP::er &p)
Static Public Attributes
static constexpr size_t dim = 2
Friends
bool operator== (const Wedge2D &lhs, const Wedge2D &rhs) noexcept
Detailed Description
Two dimensional map from the unit square to a wedge, which forms one quadrant of an annulus. The wedge can be oriented in the +/- x or y axis, with the inner and outer radii specifiable.
Constructor & Destructor Documentation
Wedge2D() [1/4]
CoordinateMaps::Wedge2D::Wedge2D (double inner_radius, double outer_radius, Direction< 2 > positioning_of_wedge) explicit
References ASSERT, Direction< VolumeDim >::axis(), and operator()().
Wedge2D() [2/4]
CoordinateMaps::Wedge2D::Wedge2D () default
~Wedge2D()
CoordinateMaps::Wedge2D::~Wedge2D () default
Wedge2D() [3/4]
CoordinateMaps::Wedge2D::Wedge2D (Wedge2D &&) default
Wedge2D() [4/4]
CoordinateMaps::Wedge2D::Wedge2D (const Wedge2D &) default
Member Function Documentation
inv_jacobian()
template<typename T > template Tensor< DataVector, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< 2, UpLo::Up, Frame::NoFrame >, SpatialIndex< 2, UpLo::Lo, Frame::NoFrame > > > CoordinateMaps::Wedge2D::inv_jacobian (const std::array< T, 2 > & xi) const noexcept
References determinant_and_inverse(), and jacobian().
Referenced by CoordinateMaps::operator!=().
inverse()
template<typename T > template std::array< DataVector, 2 > CoordinateMaps::Wedge2D::inverse (const std::array< T, 2 > & x) const noexcept
References ERROR.
Referenced by CoordinateMaps::operator!=().
jacobian()
template<typename T > template Tensor< DataVector, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< 2, UpLo::Up, Frame::NoFrame >, SpatialIndex< 2, UpLo::Lo, Frame::NoFrame > > > CoordinateMaps::Wedge2D::jacobian (const std::array< T, 2 > & xi) const noexcept
References Direction< VolumeDim >::axis().
Referenced by inv_jacobian(), and CoordinateMaps::operator!=().
operator()()
template<typename T > template std::array< DataVector, 2 > CoordinateMaps::Wedge2D::operator() (const std::array< T, 2 > & x) const noexcept
References Direction< VolumeDim >::axis(), Direction< VolumeDim >::side(), and Upper.
Referenced by CoordinateMaps::operator!=(), and Wedge2D().
operator=() [1/2]
Wedge2D& CoordinateMaps::Wedge2D::operator= (Wedge2D &&) default
operator=() [2/2]
Wedge2D& CoordinateMaps::Wedge2D::operator= (const Wedge2D &) default
pup()
void CoordinateMaps::Wedge2D::pup (PUP::er & p)
Friends And Related Function Documentation
operator==
bool operator== (const Wedge2D & lhs, const Wedge2D & rhs) friend
Member Data Documentation
dim
constexpr size_t CoordinateMaps::Wedge2D::dim = 2 static
The documentation for this class was generated from the following files:
src/Domain/CoordinateMaps/Wedge2D.hpp
src/Domain/CoordinateMaps/Wedge2D.cpp