SpECTRE: MathFunctions::Sinusoid Class Reference
MathFunctions::Sinusoid Class Reference
Sinusoid \(f = A \sin\left(k x + \delta \right)\).
#include <Sinusoid.hpp>
Classes
struct Amplitude
struct Phase
struct Wavenumber
Public Types
using options = tmpl::list< Amplitude, Wavenumber, Phase >
Public Types inherited from MathFunction< 1 >
using creatable_classes = typelist< MathFunctions::Gaussian, MathFunctions::PowX, MathFunctions::Sinusoid >
Public Member Functions
Sinusoid (double amplitude, double wavenumber, double phase) noexcept
Sinusoid ()=default
~Sinusoid () override=default
Sinusoid (const Sinusoid &)=delete
Sinusoid & operator= (const Sinusoid &)=delete
Sinusoid (Sinusoid &&) noexcept=default
Sinusoid & operator= (Sinusoid &&) noexcept=default
WRAPPED_PUPable_decl_template (Sinusoid)
Sinusoid (CkMigrateMessage *) noexcept
double operator() (const double &x) const noexcept override
Returns the function value at the coordinate 'x'.
DataVector operator() (const DataVector &x) const noexcept override
Returns the function value at the coordinate 'x'.
double first_deriv (const double &x) const noexcept override
Returns the first derivative at 'x'.
DataVector first_deriv (const DataVector &x) const noexcept override
Returns the first derivative at 'x'.
double second_deriv (const double &x) const noexcept override
Returns the second derivative at 'x'.
DataVector second_deriv (const DataVector &x) const noexcept override
Returns the second derivative at 'x'.
void pup (PUP::er &p) override
Public Member Functions inherited from MathFunction< 1 >
WRAPPED_PUPable_abstract (MathFunction)
MathFunction ()=default
MathFunction (const MathFunction &)=delete
MathFunction & operator= (const MathFunction &)=delete
MathFunction (MathFunction &&) noexcept=default
MathFunction & operator= (MathFunction &&) noexcept=default
~MathFunction () override=default
Static Public Attributes
static constexpr OptionString_t help
Detailed Description
Sinusoid \(f = A \sin\left(k x + \delta \right)\).
Details
Input file options are: Amplitude, Phase, and Wavenumber
Member Typedef Documentation
options
using MathFunctions::Sinusoid::options = tmpl::list<Amplitude, Wavenumber, Phase>
Constructor & Destructor Documentation
Sinusoid() [1/5]
MathFunctions::Sinusoid::Sinusoid (double amplitude, double wavenumber, double phase) noexcept
Sinusoid() [2/5]
MathFunctions::Sinusoid::Sinusoid () default
~Sinusoid()
MathFunctions::Sinusoid::~Sinusoid () override default
Sinusoid() [3/5]
MathFunctions::Sinusoid::Sinusoid (const Sinusoid &) delete
Sinusoid() [4/5]
MathFunctions::Sinusoid::Sinusoid (Sinusoid &&) default noexcept
Sinusoid() [5/5]
MathFunctions::Sinusoid::Sinusoid (CkMigrateMessage *) inline explicit noexcept
References first_deriv(), operator()(), pup(), and second_deriv().
Member Function Documentation
first_deriv() [1/2]
double MathFunctions::Sinusoid::first_deriv (const double & x) const override virtual noexcept
Returns the first derivative at 'x'.
Implements MathFunction< 1 >.
Referenced by Sinusoid().
first_deriv() [2/2]
DataVector MathFunctions::Sinusoid::first_deriv (const DataVector & x) const override virtual noexcept
Returns the first derivative at 'x'.
Implements MathFunction< 1 >.
operator()() [1/2]
double MathFunctions::Sinusoid::operator() (const double & x) const override virtual noexcept
Returns the function value at the coordinate 'x'.
Implements MathFunction< 1 >.
Referenced by Sinusoid().
operator()() [2/2]
DataVector MathFunctions::Sinusoid::operator() (const DataVector & x) const override virtual noexcept
Returns the function value at the coordinate 'x'.
Implements MathFunction< 1 >.
operator=() [1/2]
Sinusoid& MathFunctions::Sinusoid::operator= (const Sinusoid &) delete
operator=() [2/2]
Sinusoid& MathFunctions::Sinusoid::operator= (Sinusoid &&) default noexcept
pup()
void MathFunctions::Sinusoid::pup (PUP::er & p) override
Referenced by Sinusoid().
second_deriv() [1/2]
double MathFunctions::Sinusoid::second_deriv (const double & x) const override virtual noexcept
Returns the second derivative at 'x'.
Implements MathFunction< 1 >.
Referenced by Sinusoid().
second_deriv() [2/2]
DataVector MathFunctions::Sinusoid::second_deriv (const DataVector & x) const override virtual noexcept
Returns the second derivative at 'x'.
Implements MathFunction< 1 >.
References square().
WRAPPED_PUPable_decl_template()
MathFunctions::Sinusoid::WRAPPED_PUPable_decl_template (Sinusoid)
Member Data Documentation
help
constexpr OptionString_t MathFunctions::Sinusoid::help static
Initial value:
= {
      "Applies a Sinusoid function to the input value"}
The documentation for this class was generated from the following files:
src/PointwiseFunctions/MathFunctions/Sinusoid.hpp
src/PointwiseFunctions/MathFunctions/Sinusoid.cpp