SpECTRE: Informer Class Reference
Informer Class Reference
Utilities
The Informer manages textual output regarding the status of a simulation.
#include <Informer.hpp>
Static Public Member Functions
static void print_startup_info (CkArgMsg *msg)
Print useful information at the beginning of a simulation.
static void print_exit_info ()
Print useful information at the end of a simulation.
Detailed Description
The Informer manages textual output regarding the status of a simulation.
Member Function Documentation
print_exit_info()
void Informer::print_exit_info () static
Print useful information at the end of a simulation.
References current_date_and_time(), and Parallel::printf().
Referenced by Parallel::Main< Metavariables >::execute_next_phase().
print_startup_info()
void Informer::print_startup_info (CkArgMsg * msg) static
Print useful information at the beginning of a simulation.
References current_date_and_time(), info_from_build(), Parallel::number_of_procs(), and Parallel::printf().
Referenced by Parallel::Main< Metavariables >::Main().
The documentation for this class was generated from the following files:
src/Informer/Informer.hpp
src/Informer/Informer.cpp