SpECTRE: src/DataStructures/DataVector.hpp File Reference
DataVector.hpp File Reference
Defines class Data.
#include <blaze/math/typetraits/IsVector.h>
#include <cstddef>
#include <initializer_list>
#include <iosfwd>
#include <limits>
#include <memory>
#include <vector>
#include "DataStructures/MakeWithValue.hpp"
#include "ErrorHandling/Assert.hpp"
#include "Utilities/ConstantExpressions.hpp"
#include "Utilities/ForceInline.hpp"
#include "Utilities/Gsl.hpp"
#include "Utilities/PointerVector.hpp"
#include "Utilities/Requires.hpp"
Classes
class DataVector
A class for storing data on a mesh.
Namespaces
MakeWithValueImpls
Implementations of make_with_value.
Functions
std::ostream & operator<< (std::ostream &os, const DataVector &d)
Output operator for DataVector.
bool operator== (const DataVector &lhs, const DataVector &rhs)
Equivalence operator for DataVector.
bool operator!= (const DataVector &lhs, const DataVector &rhs)
Inequivalence operator for DataVector.
template<typename T , size_t Dim>
std::array< DataVector, Dim > operator+ (const std::array< T, Dim > &lhs, const std::array< DataVector, Dim > &rhs) noexcept
template<typename U , size_t Dim>
std::array< DataVector, Dim > operator+ (const std::array< DataVector, Dim > &lhs, const std::array< U, Dim > &rhs) noexcept
template<size_t Dim>
std::array< DataVector, Dim > operator+ (const std::array< DataVector, Dim > &lhs, const std::array< DataVector, Dim > &rhs) noexcept
template<size_t Dim>
std::array< DataVector, Dim > & operator+= (std::array< DataVector, Dim > &lhs, const std::array< DataVector, Dim > &rhs) noexcept
template<typename T , size_t Dim>
std::array< DataVector, Dim > operator- (const std::array< T, Dim > &lhs, const std::array< DataVector, Dim > &rhs) noexcept
template<typename U , size_t Dim>
std::array< DataVector, Dim > operator- (const std::array< DataVector, Dim > &lhs, const std::array< U, Dim > &rhs) noexcept
template<size_t Dim>
std::array< DataVector, Dim > operator- (const std::array< DataVector, Dim > &lhs, const std::array< DataVector, Dim > &rhs) noexcept
template<size_t Dim>
std::array< DataVector, Dim > & operator-= (std::array< DataVector, Dim > &lhs, const std::array< DataVector, Dim > &rhs) noexcept
Detailed Description
Defines class Data.
Function Documentation
operator!=()
bool operator!= (const DataVector & lhs, const DataVector & rhs)
Inequivalence operator for DataVector.
Referenced by DataVector::erfc().
operator+() [1/3]
template<typename T , size_t Dim> std::array<DataVector, Dim> operator+ (const std::array< T, Dim > & lhs, const std::array< DataVector, Dim > & rhs) noexcept
References gsl::at().
operator+() [2/3]
template<typename U , size_t Dim> std::array<DataVector, Dim> operator+ (const std::array< DataVector, Dim > & lhs, const std::array< U, Dim > & rhs) noexcept
operator+() [3/3]
template<size_t Dim> std::array<DataVector, Dim> operator+ (const std::array< DataVector, Dim > & lhs, const std::array< DataVector, Dim > & rhs) noexcept
References gsl::at().
operator+=()
template<size_t Dim> std::array<DataVector, Dim>& operator+= (std::array< DataVector, Dim > & lhs, const std::array< DataVector, Dim > & rhs) noexcept
References gsl::at().
Referenced by Time::fraction(), TimeDelta::is_positive(), and gsl::not_null< T >::operator*().
operator-() [1/3]
template<typename T , size_t Dim> std::array<DataVector, Dim> operator- (const std::array< T, Dim > & lhs, const std::array< DataVector, Dim > & rhs) noexcept
References gsl::at().
operator-() [2/3]
template<typename U , size_t Dim> std::array<DataVector, Dim> operator- (const std::array< DataVector, Dim > & lhs, const std::array< U, Dim > & rhs) noexcept
References gsl::at().
operator-() [3/3]
template<size_t Dim> std::array<DataVector, Dim> operator- (const std::array< DataVector, Dim > & lhs, const std::array< DataVector, Dim > & rhs) noexcept
References gsl::at().
operator-=()
template<size_t Dim> std::array<DataVector, Dim>& operator-= (std::array< DataVector, Dim > & lhs, const std::array< DataVector, Dim > & rhs) noexcept
References ASSERT, gsl::at(), DataVector::DataVector(), and DataVector::operator=().
Referenced by Time::fraction(), TimeDelta::is_positive(), and gsl::not_null< T >::operator*().
operator<<()
std::ostream& operator<< (std::ostream & os, const DataVector & d)
Output operator for DataVector.
Referenced by DataVector::erfc().
operator==()
bool operator== (const DataVector & lhs, const DataVector & rhs)
Equivalence operator for DataVector.
References DataVector::begin(), DataVector::end(), and DataVector::size().
Referenced by DataVector::erfc().