SpECTRE: src/Domain/Domain.cpp File Reference
Domain.cpp File Reference
#include "Domain/Domain.hpp"
#include "Domain/CoordinateMaps/CoordinateMap.hpp"
#include "Domain/DomainHelpers.hpp"
Functions
template<size_t VolumeDim, typename TargetFrame >
std::ostream & operator<< (std::ostream &os, const Domain< VolumeDim, TargetFrame > &d)
template std::ostream & operator<< (std::ostream &os, const Domain< 1, Frame::Grid > &block)
template std::ostream & operator<< (std::ostream &os, const Domain< 2, Frame::Grid > &block)
template std::ostream & operator<< (std::ostream &os, const Domain< 3, Frame::Grid > &block)
template std::ostream & operator<< (std::ostream &os, const Domain< 1, Frame::Inertial > &block)
template std::ostream & operator<< (std::ostream &os, const Domain< 2, Frame::Inertial > &block)
template std::ostream & operator<< (std::ostream &os, const Domain< 3, Frame::Inertial > &block)
Function Documentation
operator<<() [1/7]
template<size_t VolumeDim, typename TargetFrame > std::ostream& operator<< (std::ostream & os, const Domain< VolumeDim, TargetFrame > & d)
References Domain< VolumeDim, TargetFrame >::blocks().
Referenced by Domain< VolumeDim, TargetFrame >::blocks(), and Domain< VolumeDim, TargetFrame >::pup().
operator<<() [2/7]
template std::ostream& operator<< (std::ostream & os, const Domain< 1, Frame::Grid > & block)
operator<<() [3/7]
template std::ostream& operator<< (std::ostream & os, const Domain< 2, Frame::Grid > & block)
operator<<() [4/7]
template std::ostream& operator<< (std::ostream & os, const Domain< 3, Frame::Grid > & block)
operator<<() [5/7]
template std::ostream& operator<< (std::ostream & os, const Domain< 1, Frame::Inertial > & block)
operator<<() [6/7]
template std::ostream& operator<< (std::ostream & os, const Domain< 2, Frame::Inertial > & block)
operator<<() [7/7]
template std::ostream& operator<< (std::ostream & os, const Domain< 3, Frame::Inertial > & block)