SpECTRE: src/Domain/ElementIndex.hpp File Reference
ElementIndex.hpp File Reference
Defines class ElementIndex.
#include <array>
#include <iosfwd>
#include "Utilities/ConstantExpressions.hpp"
Classes
class ElementId< VolumeDim >
An ElementId uniquely labels a Element. It is constructed from the BlockId of the Block to which the Element belongs and the VolumeDim SegementIds that label the segments of the Block that the Element covers.
class ElementIndex< VolumeDim >
A class for indexing a Charm array by Element.
class ElementIndex< VolumeDim >
A class for indexing a Charm array by Element.
Functions
template<size_t VolumeDim>
std::ostream & operator<< (std::ostream &s, const ElementIndex< VolumeDim > &index) noexcept
template<size_t VolumeDim>
bool operator== (const ElementIndex< VolumeDim > &a, const ElementIndex< VolumeDim > &b) noexcept
template<size_t VolumeDim>
bool operator!= (const ElementIndex< VolumeDim > &a, const ElementIndex< VolumeDim > &b) noexcept
template<size_t VolumeDim>
size_t hash_value (const ElementIndex< VolumeDim > &index) noexcept
Detailed Description
Defines class ElementIndex.
Function Documentation
hash_value()
template<size_t VolumeDim> size_t hash_value (const ElementIndex< VolumeDim > & index) noexcept
References hash_value().
Referenced by hash_value(), and operator<<().
operator!=()
template<size_t VolumeDim> bool operator!= (const ElementIndex< VolumeDim > & a, const ElementIndex< VolumeDim > & b) noexcept
Referenced by operator<<().
operator<<()
template<size_t VolumeDim> std::ostream& operator<< (std::ostream & s, const ElementIndex< VolumeDim > & index) noexcept
References hash_value(), operator!=(), operator<<(), and operator==().
Referenced by operator<<().
operator==()
template<size_t VolumeDim> bool operator== (const ElementIndex< VolumeDim > & a, const ElementIndex< VolumeDim > & b) noexcept
Referenced by operator<<().