SpECTRE: src/Domain/Element.cpp File Reference
Element.cpp File Reference
#include "Domain/Element.hpp"
#include <ostream>
#include <pup.h>
#include <utility>
Functions
template<size_t VolumeDim>
bool operator== (const Element< VolumeDim > &lhs, const Element< VolumeDim > &rhs) noexcept
template<size_t VolumeDim>
bool operator!= (const Element< VolumeDim > &lhs, const Element< VolumeDim > &rhs) noexcept
template<size_t VolumeDim>
std::ostream & operator<< (std::ostream &os, const Element< VolumeDim > &element) noexcept
template bool operator== (const Element< 1 > &, const Element< 1 > &) noexcept
template bool operator== (const Element< 2 > &, const Element< 2 > &) noexcept
template bool operator== (const Element< 3 > &, const Element< 3 > &) noexcept
template bool operator!= (const Element< 1 > &, const Element< 1 > &) noexcept
template bool operator!= (const Element< 2 > &, const Element< 2 > &) noexcept
template bool operator!= (const Element< 3 > &, const Element< 3 > &) noexcept
template std::ostream & operator<< (std::ostream &, const Element< 1 > &) noexcept
template std::ostream & operator<< (std::ostream &, const Element< 2 > &) noexcept
template std::ostream & operator<< (std::ostream &, const Element< 3 > &) noexcept
Function Documentation
operator!=() [1/4]
template<size_t VolumeDim> bool operator!= (const Element< VolumeDim > & lhs, const Element< VolumeDim > & rhs) noexcept
Referenced by operator<<().
operator!=() [2/4]
template bool operator!= (const Element< 1 > & , const Element< 1 > &) noexcept
operator!=() [3/4]
template bool operator!= (const Element< 2 > & , const Element< 2 > &) noexcept
operator!=() [4/4]
template bool operator!= (const Element< 3 > & , const Element< 3 > &) noexcept
operator<<() [1/4]
template<size_t VolumeDim> std::ostream& operator<< (std::ostream & os, const Element< VolumeDim > & element) noexcept
References operator!=(), and operator==().
operator<<() [2/4]
template std::ostream& operator<< (std::ostream & , const Element< 1 > &) noexcept
operator<<() [3/4]
template std::ostream& operator<< (std::ostream & , const Element< 2 > &) noexcept
operator<<() [4/4]
template std::ostream& operator<< (std::ostream & , const Element< 3 > &) noexcept
operator==() [1/4]
template<size_t VolumeDim> bool operator== (const Element< VolumeDim > & lhs, const Element< VolumeDim > & rhs) noexcept
Referenced by operator<<().
operator==() [2/4]
template bool operator== (const Element< 1 > & , const Element< 1 > &) noexcept
operator==() [3/4]
template bool operator== (const Element< 2 > & , const Element< 2 > &) noexcept
operator==() [4/4]
template bool operator== (const Element< 3 > & , const Element< 3 > &) noexcept