SpECTRE: HDF5
HDF5
Functions and classes for manipulating HDF5 files.
Namespaces
h5
Contains functions and classes for manipulating HDF5 files.
Classes
class h5::Dat
Represents a multicolumn dat file inside an HDF5 file.
class h5::H5File< Access_t >
Opens an HDF5 file for access and allows manipulation of data.
class h5::Header
Writes header info about the build, git commit, branch, etc.
class h5::Object
Abstract base class representing an object in an HDF5 file.
class h5::Version
Used to store the version of the file.
class vis::VolumeFile
Writes out volume data as an HDF5 file and an XDMF file to be visualized in ParaView or VisIt.
Macros
#define CHECK_H5(h5_status, m)
Check if an HDF5 operation was successful.
Enumerations
enum h5::AccessType { h5::AccessType::ReadWrite, h5::AccessType::ReadOnly }
Set the access type to the H5File.
Functions
void h5::write_time (hid_t group_id, double time)
Write a "Time" attribute to the group.
template<size_t Dim>
void h5::write_data (hid_t group_id, const DataVector &data, const Index< Dim > &extents, const std::string &name="scalar")
Write a DataVector named name to the group group_id
template<size_t Dim>
void h5::write_extents (hid_t group_id, const Index< Dim > &extents, const std::string &name="Extents")
Write the extents as an attribute named name to the group group_id.
void h5::write_connectivity (hid_t group_id, const std::vector< int > &connectivity)
Write the connectivity into the group in the H5 file.
std::vector< std::string > h5::get_group_names (hid_t file_id, const std::string &group_name)
Get the names of all the groups in a group.
std::vector< std::string > h5::get_attribute_names (hid_t file_id, const std::string &group_name)
Get the names of all the attributes in a group.
bool h5::contains_attribute (hid_t file_id, const std::string &group_name, const std::string &attribute_name)
Check if an attribute is in a group.
double h5::get_time (hid_t file_id, const std::string &group_name, const std::string &attr_name="Time")
Get the "Time" attribute from a group.
DataVector h5::read_data (hid_t group_id, const std::string &dataset_name)
Read a DataVector from a dataset in a group.
template<size_t Dim>
Index< Dim > h5::read_extents (hid_t group_id, const std::string &extents_name="Extents")
Read the HDF5 attribute representing extents from a group.
template<typename T >
hid_t h5::h5_type ()
Returns the HDF5 datatype for the corresponding type T
Detailed Description
Functions and classes for manipulating HDF5 files.
Macro Definition Documentation
CHECK_H5
#define CHECK_H5 (h5_status, m)
Value:
if (h5_status < 0) {                     /*NOLINT*/ \
    ERROR("Failed HDF5 operation: " << m); /*NOLINT*/ \
  } else                                              \
    static_cast<void>(0)
Check if an HDF5 operation was successful.
Requires: h5_status is a valid HDF5 return type, m is a stringstream syntax error message.
Effects: if h5_status is set to error then aborts execution else none
Referenced by h5::H5File< Access_t >::get(), h5::get_attribute_names(), h5::Dat::get_data(), h5::Dat::get_data_subset(), h5::get_group_names(), h5::get_time(), h5::H5File< Access_t >::H5File(), h5::H5File< Access_t >::insert(), h5::read_data(), h5::read_extents(), h5::write_connectivity(), h5::write_data(), vis::VolumeFile::write_element_data(), h5::write_extents(), h5::write_time(), and vis::VolumeFile::~VolumeFile().
Enumeration Type Documentation
AccessType
enum h5::AccessType strong
Set the access type to the H5File.
Enumerator
ReadWrite
Allow read-write access to the file.
ReadOnly
Allow only read access to the file.
Function Documentation
contains_attribute()
bool h5::contains_attribute (const hid_t file_id, const std::string & group_name, const std::string & attribute_name)
Check if an attribute is in a group.
References h5::get_attribute_names().
Referenced by h5::get_time().
get_attribute_names()
std::vector< std::string > h5::get_attribute_names (const hid_t file_id, const std::string & group_name)
Get the names of all the attributes in a group.
References CHECK_H5, and h5::ReadOnly.
Referenced by h5::contains_attribute().
get_group_names()
std::vector< std::string > h5::get_group_names (const hid_t file_id, const std::string & group_name)
Get the names of all the groups in a group.
References CHECK_H5, and h5::ReadOnly.
get_time()
double h5::get_time (const hid_t file_id, const std::string & group_name, const std::string & attr_name)
Get the "Time" attribute from a group.
References CHECK_H5, h5::contains_attribute(), ERROR, and h5::ReadOnly.
Referenced by TimeSteppers::AdamsBashforthN::AdamsBashforthN(), and TimeSteppers::AdamsBashforthN::compute_boundary_delta().
h5_type()
template<typename T > hid_t h5::h5_type ()
Returns the HDF5 datatype for the corresponding type T
Requires: T is a valid type with a corresponding HDF5 datatype, i.e. a fundamental or a std::string
Returns: the HDF5 datatype for the corresponding type T
Note
For strings, the returned type must be released with H5Tclose
Referenced by h5::read_extents(), vis::VolumeFile::write_element_data(), and h5::write_extents().
read_data()
DataVector h5::read_data (const hid_t group_id, const std::string & dataset_name)
Read a DataVector from a dataset in a group.
References CHECK_H5, and DataVector::data().
read_extents()
template<size_t Dim> Index< Dim > h5::read_extents (const hid_t group_id, const std::string & extents_name)
Read the HDF5 attribute representing extents from a group.
References CHECK_H5, Index< Dim >::data(), h5::h5_type(), h5::read_extents< 1 >(), h5::read_extents< 2 >(), h5::read_extents< 3 >(), h5::write_data< 1 >(), h5::write_data< 2 >(), h5::write_data< 3 >(), h5::write_extents< 1 >(), h5::write_extents< 2 >(), and h5::write_extents< 3 >().
write_connectivity()
void h5::write_connectivity (const hid_t group_id, const std::vector< int > & connectivity)
Write the connectivity into the group in the H5 file.
References CHECK_H5.
write_data()
template<size_t Dim> void h5::write_data (const hid_t group_id, const DataVector & data, const Index< Dim > & extents, const std::string & name)
Write a DataVector named name to the group group_id
References CHECK_H5, and DataVector::data().
Referenced by vis::VolumeFile::write_element_connectivity_and_coordinates(), and vis::VolumeFile::write_element_data().
write_extents()
template<size_t Dim> void h5::write_extents (const hid_t group_id, const Index< Dim > & extents, const std::string & name)
Write the extents as an attribute named name to the group group_id.
References CHECK_H5, Index< Dim >::data(), and h5::h5_type().
write_time()
void h5::write_time (const hid_t group_id, const double time)
Write a "Time" attribute to the group.
References CHECK_H5.
Referenced by vis::VolumeFile::write_xdmf_time().