SpECTRE: Numerical Algorithms
Numerical Algorithms
Generic numerical algorithms.
Namespaces
Basis
Basis functions, derivative matrices, etc. for spectral-type methods.
Basis::lgl
Functions for using Legendre-Gauss-Lobatto basis.
Functions
template<typename DerivativeTags , typename VariableTags , size_t Dim>
auto logical_partial_derivatives (const Variables< VariableTags > &u, const Index< Dim > &extents)
Compute the partial derivatives of each variable with respect to the logical coordinate.
template<typename DerivativeTags , typename VariableTags , size_t Dim, typename DerivativeFrame >
auto partial_derivatives (const Variables< VariableTags > &u, const Index< Dim > &extents, const Tensor< DataVector, tmpl::integral_list< std::int32_t, 2, 1 >, typelist< SpatialIndex< Dim, UpLo::Up, Frame::Logical >, SpatialIndex< Dim, UpLo::Lo, DerivativeFrame >>> &inverse_jacobian)
Compute the partial derivatives of each variable with respect to the coordinates of DerivativeFrame.
double positive_root (double a, double b, double c)
Returns the positive root of a quadratic equation ax^2 + bx + c = 0.
std::array< double, 2 > real_roots (double a, double b, double c)
Returns the two real roots of a quadratic equation ax^2 + bx + c = 0.
template<typename Function >
double find_root_of_function (Function f, const double lower_bound, const double upper_bound, const double absolute_tolerance, const double relative_tolerance, const size_t max_iterations=100)
Finds the root of the function f with the TOMS_748 method.
template<size_t Dim>
double Basis::lgl::definite_integral (const DataVector &integrand, const Index< Dim > &extents) noexcept
Compute the definite integral of a grid-function over a manifold.
template<size_t Dim>
DataVector linearize (const DataVector &u, const Index< Dim > &extents)
template<size_t Dim>
DataVector linearize (const DataVector &u, const Index< Dim > &extents, size_t d)
template<size_t Dim>
double mean_value (const DataVector &f, const Index< Dim > &extents)
Compute the mean value of a grid-function over a manifold. \(mean value = \int f dV / \int dV\).
template<size_t Dim>
double mean_value_on_boundary (const DataVector &f, const Index< Dim > &extents, size_t d, Side side)
template<typename U , typename T >
void transpose (const U &u, const size_t chunk_size, const size_t number_of_chunks, const gsl::not_null< T *> transpose)
Function to compute transposed data.
template<typename U , typename T = U>
T transpose (const U &u, const size_t chunk_size, const size_t number_of_chunks)
Function to compute transposed data.
Detailed Description
Generic numerical algorithms.
Function Documentation
definite_integral()
template<size_t Dim> double Basis::lgl::definite_integral (const DataVector & integrand, const Index< Dim > & extents) noexcept
Compute the definite integral of a grid-function over a manifold.
The integral is computed on the reference element by multiplying the DataVector with the Basis::lgl integration weights in that dimension.
Requires: number of points in integrand and extents are equal.
Parameters
integrand the grid function to integrate.
extents the extents of the manifold on which integrand is located.
Returns: the definite integral of integrand on the manifold.
References ASSERT.
Referenced by mean_value(), and mean_value_on_boundary().
find_root_of_function()
template<typename Function > double find_root_of_function (Function f, const double lower_bound, const double upper_bound, const double absolute_tolerance, const double relative_tolerance, const size_t max_iterations = 100)
Finds the root of the function f with the TOMS_748 method.
Requires: Function f be callable
linearize() [1/2]
template<size_t Dim> DataVector linearize (const DataVector & u, const Index< Dim > & extents)
Truncate u to a linear function in each dimension. Ex in 2D: \(u^{Lin} = U_0 + U_x x + U_y y + U_{xy} xy\)
Returns: the linearization of u
References gsl::at(), Matrix::data(), dgemv_(), Basis::lgl::linear_filter_matrix(), linearize< 1 >(), linearize< 2 >(), linearize< 3 >(), and Index< Dim >::product().
linearize() [2/2]
template<size_t Dim> DataVector linearize (const DataVector & u, const Index< Dim > & extents, size_t d)
Truncate u to a linear function in the given dimension.
Returns: the linearization of u
Parameters
u the function to linearize.
extents the extents of the grid on the manifold on which u is located.
d the dimension that is to be linearized.
References Index< Dim >::data(), DataVector::data(), dgemv_(), Basis::lgl::linear_filter_matrix(), linearize< 1 >(), linearize< 2 >(), linearize< 3 >(), and Index< Dim >::product().
logical_partial_derivatives()
template<typename DerivativeTags , typename VariableTags , size_t Dim> auto logical_partial_derivatives (const Variables< VariableTags > & u, const Index< Dim > & extents)
Compute the partial derivatives of each variable with respect to the logical coordinate.
References db::apply().
mean_value()
template<size_t Dim> double mean_value (const DataVector & f, const Index< Dim > & extents)
Compute the mean value of a grid-function over a manifold. \(mean value = \int f dV / \int dV\).
Remarks: The mean value is computed on the reference element(s).
Note
The mean w.r.t. a different set of coordinates x can be computed by pre-multiplying the argument f by the Jacobian J = dx/dxi of the mapping from the reference coordinates xi to the coordinates x.
Returns: the mean value of f on the manifold
Parameters
f the grid function of which to find the mean.
extents the extents of the manifold on which f is located.
References Basis::lgl::definite_integral(), mean_value_on_boundary(), and two_to_the().
mean_value_on_boundary()
template<size_t Dim> double mean_value_on_boundary (const DataVector & f, const Index< Dim > & extents, size_t d, Side side)
Compute the mean value of a grid-function on a boundary of a manifold. \(mean value = \int f dV / \int dV\)
Remarks: The mean value is computed on the reference element(s).
Returns: the mean value of f on the boundary of the manifold
Parameters
f the grid function of which to find the mean.
extents the extents of the manifold on which f is located.
d the dimension which is sliced away to get the boundary.
side whether it is the lower or upper boundary in the d-th dimension.
References ASSERT, Basis::lgl::definite_integral(), Lower, mean_value_on_boundary(), Index< Dim >::slice_away(), and two_to_the().
Referenced by mean_value().
partial_derivatives()
template<typename DerivativeTags , typename VariableTags , size_t Dim, typename DerivativeFrame > auto partial_derivatives (const Variables< VariableTags > & u, const Index< Dim > & extents, const Tensor< DataVector, tmpl::integral_list< std::int32_t, 2, 1 >, typelist< SpatialIndex< Dim, UpLo::Up, Frame::Logical >, SpatialIndex< Dim, UpLo::Lo, DerivativeFrame >>> & inverse_jacobian)
Compute the partial derivatives of each variable with respect to the coordinates of DerivativeFrame.
References db::apply(), gsl::at(), Matrix::data(), Index< Dim >::data(), dgemm_(), Basis::lgl::differentiation_matrix(), make_not_null(), and transpose().
positive_root()
double positive_root (double a, double b, double c)
Returns the positive root of a quadratic equation ax^2 + bx + c = 0.
Returns: The positive root of a quadratic equation.
Requires: That there are two real roots, of which only one is positive.
References ASSERT, Ensures, and std::numeric_limits::signaling_NaN().
real_roots()
std::array<double, 2> real_roots (double a, double b, double c)
Returns the two real roots of a quadratic equation ax^2 + bx + c = 0.
Returns: An array of the roots of a quadratic equation
Requires: That there are two real roots.
References ASSERT, and std::numeric_limits::signaling_NaN().
transpose() [1/2]
template<typename U , typename T > void transpose (const U & u, const size_t chunk_size, const size_t number_of_chunks, const gsl::not_null< T *> transpose)
Function to compute transposed data.
The primary use of this function is to rearrange the memory layout so that another function can operate on contiguous chunks of memory.
Requires: transpose.size() to be the product of number_of_chunks and chunk_size,u.size()to be equal or greater thantranspose.size(), and that bothtransposeanduhave adata()` member function.
Details
The container u holds a contiguous array of data that is at least of size number_of_chunks times chunk_size. The output transpose has its data arranged such that the first number_of_chunks elements in transpose will be the first element of each chunk of u. The last number_of_chunks elements in transpose will be the last (i.e. chunk_size-th) element of each chunk of u.
Note
This is equivalent to treating the first part of u as a matrix and filling transpose (or the returned object) with the transpose of that matrix.
Example
  const size_t chunk_size_vars = 8;
  const size_t n_grid_pts = 2 * chunk_size_vars;
  Variables<two_vars<2>> variables(n_grid_pts, 0.);
  for (size_t i = 0; i < variables.size(); ++i) {
    // clang-tidy: pointer arithmetic
    variables.data()[i] = i * i;  // NOLINT
  }
  const size_t number_of_chunks_vars = variables.size() / chunk_size_vars;
  auto transposed_vars = variables;
  transpose(variables, chunk_size_vars, number_of_chunks_vars,
            make_not_null(&transposed_vars));
  for (size_t i = 0; i < chunk_size_vars; ++i) {
    for (size_t j = 0; j < number_of_chunks_vars; ++j) {
      // clang-tidy: pointer arithmetic
      CHECK(variables.data()[i + chunk_size_vars * j] ==             // NOLINT
            transposed_vars.data()[j + number_of_chunks_vars * i]);  // NOLINT
    }
  }
  const size_t chunk_size = 8;
  const size_t number_of_chunks = 2;
  const size_t n_pts = chunk_size * number_of_chunks;
  DataVector data(n_pts);
  for (size_t i = 0; i < data.size(); ++i) {
    data[i] = i * i;
  }
  DataVector transposed_data(n_pts, 0.);
  transposed_data = transpose(data, chunk_size, number_of_chunks);
  for (size_t i = 0; i < chunk_size; ++i) {
    for (size_t j = 0; j < number_of_chunks; ++j) {
      CHECK(data[i + chunk_size * j] ==
            transposed_data[j + number_of_chunks * i]);
    }
  }
  Variables<one_var<2>> partial_vars(n_grid_pts, 0.);
  get<Var1<2>>(partial_vars) = get<Var1<2>>(variables);
  Variables<one_var<2>> partial_transpose(n_grid_pts, 0.);
  const size_t partial_number_of_chunks = 2*number_of_chunks_vars / 3;
  transpose(variables, chunk_size_vars, partial_number_of_chunks,
            make_not_null(&partial_transpose));
  for (size_t i = 0; i < chunk_size_vars; ++i) {
    for (size_t j = 0; j < partial_number_of_chunks; ++j) {
      // clang-tidy: pointer arithmetic
      CHECK(partial_transpose
                .data()[j + partial_number_of_chunks * i] ==  // NOLINT
            variables.data()[i + chunk_size_vars * j]);       // NOLINT
      CHECK(partial_transpose
                .data()[j + partial_number_of_chunks * i] ==  // NOLINT
            partial_vars.data()[i + chunk_size_vars * j]);    // NOLINT
    }
  }
Template Parameters
U the type of data to be transposed
T the type of the transposed data
References ASSERT.
Referenced by partial_derivatives(), and transpose().
transpose() [2/2]
template<typename U , typename T = U> T transpose (const U & u, const size_t chunk_size, const size_t number_of_chunks)
Function to compute transposed data.
The primary use of this function is to rearrange the memory layout so that another function can operate on contiguous chunks of memory.
Requires: transpose.size() to be the product of number_of_chunks and chunk_size,u.size()to be equal or greater thantranspose.size(), and that bothtransposeanduhave adata()` member function.
Details
The container u holds a contiguous array of data that is at least of size number_of_chunks times chunk_size. The output transpose has its data arranged such that the first number_of_chunks elements in transpose will be the first element of each chunk of u. The last number_of_chunks elements in transpose will be the last (i.e. chunk_size-th) element of each chunk of u.
Note
This is equivalent to treating the first part of u as a matrix and filling transpose (or the returned object) with the transpose of that matrix.
Example
  const size_t chunk_size_vars = 8;
  const size_t n_grid_pts = 2 * chunk_size_vars;
  Variables<two_vars<2>> variables(n_grid_pts, 0.);
  for (size_t i = 0; i < variables.size(); ++i) {
    // clang-tidy: pointer arithmetic
    variables.data()[i] = i * i;  // NOLINT
  }
  const size_t number_of_chunks_vars = variables.size() / chunk_size_vars;
  auto transposed_vars = variables;
  transpose(variables, chunk_size_vars, number_of_chunks_vars,
            make_not_null(&transposed_vars));
  for (size_t i = 0; i < chunk_size_vars; ++i) {
    for (size_t j = 0; j < number_of_chunks_vars; ++j) {
      // clang-tidy: pointer arithmetic
      CHECK(variables.data()[i + chunk_size_vars * j] ==             // NOLINT
            transposed_vars.data()[j + number_of_chunks_vars * i]);  // NOLINT
    }
  }
  const size_t chunk_size = 8;
  const size_t number_of_chunks = 2;
  const size_t n_pts = chunk_size * number_of_chunks;
  DataVector data(n_pts);
  for (size_t i = 0; i < data.size(); ++i) {
    data[i] = i * i;
  }
  DataVector transposed_data(n_pts, 0.);
  transposed_data = transpose(data, chunk_size, number_of_chunks);
  for (size_t i = 0; i < chunk_size; ++i) {
    for (size_t j = 0; j < number_of_chunks; ++j) {
      CHECK(data[i + chunk_size * j] ==
            transposed_data[j + number_of_chunks * i]);
    }
  }
  Variables<one_var<2>> partial_vars(n_grid_pts, 0.);
  get<Var1<2>>(partial_vars) = get<Var1<2>>(variables);
  Variables<one_var<2>> partial_transpose(n_grid_pts, 0.);
  const size_t partial_number_of_chunks = 2*number_of_chunks_vars / 3;
  transpose(variables, chunk_size_vars, partial_number_of_chunks,
            make_not_null(&partial_transpose));
  for (size_t i = 0; i < chunk_size_vars; ++i) {
    for (size_t j = 0; j < partial_number_of_chunks; ++j) {
      // clang-tidy: pointer arithmetic
      CHECK(partial_transpose
                .data()[j + partial_number_of_chunks * i] ==  // NOLINT
            variables.data()[i + chunk_size_vars * j]);       // NOLINT
      CHECK(partial_transpose
                .data()[j + partial_number_of_chunks * i] ==  // NOLINT
            partial_vars.data()[i + chunk_size_vars * j]);    // NOLINT
    }
  }
Template Parameters
U the type of data to be transposed
T the type of the transposed data
References make_not_null(), and transpose().