SpECTRE: Parallelization
Parallelization
Functions, classes and documentation related to parallelization and Charm++.
Classes
class ElementIndex< VolumeDim >
A class for indexing a Charm array by Element.
class AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >
A distributed object (Charm++ Chare) that executes a series of Actions and is capable of sending and receiving data. Acts as an interface to Charm++.
struct Parallel::ArrayIndex< Index >
The array index used for indexing Chare Arrays, mostly an implementation detail.
class Parallel::ConstGlobalCache< Metavariables >
A Charm++ chare that caches constant data once per Charm++ node.
class Parallel::Main< Metavariables >
The main function of a Charm++ executable.
struct Parallel::ReductionData< Ts >
Used for reducing heterogeneous collection of types in a single reduction call.
struct Parallel::is_array_proxy< T >
Check if T is a Charm++ proxy for an array chare.
struct Parallel::is_chare_proxy< T >
Check if T is a Charm++ proxy for a chare.
struct Parallel::is_group_proxy< T >
Check if T is a Charm++ proxy for a group chare.
struct Parallel::is_node_group_proxy< T >
Check if T is a Charm++ proxy for a node group chare.
struct Parallel::is_bound_array< T, typename >
Check if T is a ParallelComponent for a Charm++ bound array.
struct Parallel::has_pup_member< T, typename >
Check if T has a pup member function.
struct Parallel::is_pupable< T, U >
Check if type T has operator| defined for Charm++ serialization.
Macros
#define WRAPPED_PUPable_decl_template(className) PUPable_decl_template(SINGLE_ARG(className))
Mark derived classes as serializable.
#define WRAPPED_PUPable_decl_base_template(baseClassName, className) PUPable_decl_base_template(SINGLE_ARG(baseClassName), SINGLE_ARG(className))
Mark derived template classes as serializable.
Functions
void Parallel::abort (const std::string &message)
Abort the program with an error message.
void Parallel::lock (const gsl::not_null< CmiNodeLock *> node_lock) noexcept
Lock a converse CmiNodeLock.
bool Parallel::try_lock (const gsl::not_null< CmiNodeLock *> node_lock) noexcept
Returns true if the lock was successfully acquired and false if the lock is already acquired by another processor.
void Parallel::unlock (const gsl::not_null< CmiNodeLock *> node_lock) noexcept
Unlock a converse CmiNodeLock.
void Parallel::exit ()
Exit the program normally. This should only be called once over all processors.
int Parallel::number_of_procs ()
Number of processing elements.
int Parallel::my_proc ()
Index of my processing element.
int Parallel::number_of_nodes ()
Number of nodes.
int Parallel::my_node ()
Index of my node.
int Parallel::procs_on_node (const int node_index)
Number of processing elements on the given node.
int Parallel::my_local_rank ()
The local index of my processing element on my node. This is in the interval 0, ..., procs_on_node(my_node()) - 1.
int Parallel::first_proc_on_node (const int node_index)
Index of first processing element on the given node.
int Parallel::node_of (const int proc_index)
Index of the node for the given processing element.
int Parallel::local_rank_of (const int proc_index)
The local index for the given processing element on its node.
double Parallel::wall_time ()
The current wall time in seconds.
template<typename... Args>
void Parallel::printf (const std::string &format, Args &&... args)
Print an atomic message to stdout with C printf usage.
template<size_t Index, class... Us>
auto Parallel::get (ReductionData< Us... > &reduction_data) noexcept -> decltype(std::get< Index >(reduction_data.data))
Retrieve the Indexth element from a ReductionData<Ts...>, similar to std::get for std::tuples.
template<class SenderParallelComponent , class TargetParallelComponent , class Action , class Metavariables , class ArrayIndex , class ReductionType , Requires< not Parallel_detail::is_custom_reduction_type_v< ReductionType >> = nullptr>
void Parallel::contribute_to_reduction (const ConstGlobalCache< Metavariables > &cache, const ArrayIndex &array_index, CkReduction::reducerType reducer, const ReductionType &reduction_data) noexcept
Perform a reduction from the current ParallelComponent to the TargetParallelComponent, performing the Action upon receiving the reduction.
template<class... Ts>
CkReductionMsg * Parallel::new_reduction_msg (ReductionData< Ts... > &reduction_data) noexcept
Convert a ReductionData to a CkReductionMsg. Used in custom reducers.
template<typename T , typename U >
std::vector< char > serialize (const U &obj)
Serialize an object using PUP.
template<typename T >
T deserialize (const void *const data)
Deserialize an object using PUP.
template<typename ParallelComponentTag , typename Metavariables >
Parallel::proxy_from_parallel_component< ParallelComponentTag > & Parallel::get_parallel_component (ConstGlobalCache< Metavariables > &cache) noexcept
Access the Charm++ proxy associated with a ParallelComponent.
template<typename ParallelComponentTag , typename Metavariables >
const Parallel::proxy_from_parallel_component< ParallelComponentTag > & Parallel::get_parallel_component (const ConstGlobalCache< Metavariables > &cache) noexcept
Access the Charm++ proxy associated with a ParallelComponent.
template<typename ConstGlobalCacheTag , typename Metavariables >
const ConstGlobalCache_detail::type_for_get< typename ConstGlobalCacheTag::type >::type & Parallel::get (const ConstGlobalCache< Metavariables > &cache) noexcept
Access data in the cache.
Detailed Description
Functions, classes and documentation related to parallelization and Charm++.
SpECTRE builds a layer on top of Charm++ that performs various safety checks and initialization for the user that can otherwise lead to difficult to debug undefined behavior. The central concept is what is called a Parallel Component. A Parallel Component is a struct with several type aliases that is used by SpECTRE to set up the Charm++ chares and allowed communication patterns. It might be most natural to think of Parallel Components as input arguments to a metaprogram that writes the parallelization infrastructure that you requested for the executable. There is no restriction on the number of Parallel Components, though practically it is best to have around 10 at most.
Each Parallel Component must have the following type aliases:
using chare_type is set to one of Parallel::Algorithms::Singleton, Parallel::Algorithms::Array, Parallel::Algorithms::Group, or Parallel::Algorithms::Nodegroup. What these mean is explained below.
using metavariables is set to the Metavariables struct that stores the global metavariables. It is often easiest to have the Parallel Component struct have a template parameter Metavariables that is the global metavariables struct. Examples of this are given below.
using action_list is set to a typelist of the Actions that the Algorithm running on the Parallel Component executes. The Actions are executed in the order that they are listed in in the typelist.
using inbox_tag_list is set to a typelist of the Tags that can be sent to the Parallel Component by calling the receive_data method. If the Inbox Tag needs to have some temporal locality, then an optional type alias temporal_id must be specified in the Inbox Tag and sent along with the data.
using initial_databox is set to the type of the DataBox that will be passed to the first Action of the action_list. Typically it is the output of some explicit_single_action call made during the initialize function. More on this below.
using options is set to a (possibly empty) typelist of the option structs which are read in from the input file specified in the main Metavariables struct and passed to the initialize function described below.
The following type aliases are not always required, but will be in some circumstances:
using array_index is set to the type that indexes the Parallel Component Array and is only required if chare_type = Parallel::Algorithms::Array. Charm++ allows arrays to be 1 through 6 dimensional or be indexed by a custom type. The Charm++ provided indexes are wrapped as `Parallel::ArrayIndex1D' through Parallel::ArrayIndex6D. When writing custom array indices, the Charm++ manual tells you to write your own CkArrayIndex, but we have written a general implementation that provides this functionality; all that you need to provide is a plain-old-data struct of the size of at most 3 integers.
using explicit_single_actions is set to a typelist of typelists for Actions that are not part of the algorithm but can be called remotely at any time, similar in spirit to a member function. For each Action, a typelist is specified with the Action as their first element, and the remaining elements are types of the data that is sent to the Parallel Component and passed into the Action.
using reduction_actions_list is set to a typelist of typelists. The nested typelists must have exactly two elements. The first element is the Action to call, and the second is the type being reduced. For example, the reduced type could be an int, a double, or a specialization of Parallel::ReductionData.
Parallel Components must also have two static member functions with the following signatures:
static void initialize(
   Parallel::CProxy_ConstGlobalCache<metavariables>& global_cache, opts...);
and
static void execute_next_global_actions(
    const typename metavariables::Phase next_phase,
    const Parallel::CProxy_ConstGlobalCache<metavariables>& global_cache);
The initialize function is called by the Main Parallel Component when the execution starts and will typically call an explicit single Action to set up the initial state of the Algorithm, similar to what a constructor does for classes. The initialize function also receives arguments that are read from the input file and can the be used to initialize the Parallel Component. For example, the value of an option could be distributed to all members of a Parallel Component Array, or could be used to control the size of the Parallel Component Array.
The execute_next_global_actions function gets run at the end of each Parallel Phase and determines what the Parallel Component should do during the next phase. For example, it may simply call perform_algorithm, call a series of single Actions, perform a reduction over an Array, or not do anything at all.
An example of a singleton Parallel Component is:
template <class Metavariables>
struct SingletonParallelComponent {
  using chare_type = Parallel::Algorithms::Singleton;
  using const_global_cache_tag_list = typelist<>;
  using metavariables = Metavariables;
  using action_list = typelist<SingletonActions::CountReceives>;
  using inbox_tag_list = typelist<Tags::IntReceiveTag>;
  using initial_databox = db::DataBox<db::get_databox_list<typelist<>>>;
  using explicit_single_actions_list =
      tmpl::list<tmpl::list<SingletonActions::Initialize>>;
  using options = typelist<>;
  static void initialize(
      Parallel::CProxy_ConstGlobalCache<Metavariables>& global_cache) {
    auto& local_cache = *(global_cache.ckLocalBranch());
    Parallel::get_parallel_component<SingletonParallelComponent>(local_cache)
        .template explicit_single_action<SingletonActions::Initialize>();
  }
  static void execute_next_global_actions(
      const typename Metavariables::Phase next_phase,
      const Parallel::CProxy_ConstGlobalCache<Metavariables>& global_cache) {
    if (next_phase == Metavariables::Phase::PerformSingletonAlgorithm) {
      auto& local_cache = *(global_cache.ckLocalBranch());
      Parallel::get_parallel_component<SingletonParallelComponent>(local_cache)
          .perform_algorithm();
      return;
    }
  }
};
and similarly of a Parallel Component Array:
template <class Metavariables>
struct ArrayParallelComponent {
  using chare_type = Parallel::Algorithms::Array;
  using const_global_cache_tag_list = typelist<>;
  using metavariables = Metavariables;
  using action_list =
      typelist<ArrayActions::AddIntValue10, ArrayActions::IncrementInt0,
               ArrayActions::RemoveInt0, ArrayActions::SendToSingleton>;
  using inbox_tag_list = typelist<Tags::IntReceiveTag>;
  using array_index = int;
  using initial_databox =
      db::DataBox<db::get_databox_list<typelist<Tags::CountActionsCalled>>>;
  using explicit_single_actions_list =
      tmpl::list<tmpl::list<ArrayActions::Initialize>>;
  using options = typelist<>;
  static void initialize(
      Parallel::CProxy_ConstGlobalCache<Metavariables>& global_cache) {
    auto& local_cache = *(global_cache.ckLocalBranch());
    auto& array_proxy =
        Parallel::get_parallel_component<ArrayParallelComponent>(local_cache);
    for (int i = 0, which_proc = 0,
             number_of_procs = Parallel::number_of_procs();
         i < number_of_1d_array_elements; ++i) {
      array_proxy[i].insert(global_cache, which_proc);
      which_proc = which_proc + 1 == number_of_procs ? 0 : which_proc + 1;
    }
    array_proxy.doneInserting();
    array_proxy.template explicit_single_action<ArrayActions::Initialize>();
  }
  static void execute_next_global_actions(
      const typename Metavariables::Phase next_phase,
      Parallel::CProxy_ConstGlobalCache<Metavariables>& global_cache) {
    auto& local_cache = *(global_cache.ckLocalBranch());
    if (next_phase == Metavariables::Phase::PerformArrayAlgorithm) {
      Parallel::get_parallel_component<ArrayParallelComponent>(local_cache)
          .perform_algorithm();
    }
  }
};
Elements are inserted into the Array by using the Charm++ insert member function of the CProxy for the array. The insert function is is documented in the Charm++ manual. In the above Array example array_proxy is a CProxy to the AlgorithmImpl<Parallel::Algorithms::Array, ...> and so all the documentation for Charm++ array proxies applies. We always create empty Arrays with the constructor and require users to insert however many elements they want and on which cores they want them to be placed. Note that load balancing calls may result in Array elements being moved.
There are four types of Algorithms with one Algorithm object per Charm++ chare object. The four types of Algorithms are:
A Parallel::Algorithms::Singleton where there is only one object in the entire execution of the program.
A Parallel::Algorithms::Array which holds zero or more elements each of which is an object distributed to some core. An array can grow and shrink in size dynamically if need be and can also be bound to another array. A bound array has the same number of elements as the array it is bound to, and elements with the same ID are on the same core. See Charm++'s chare arrays for details.
A Parallel::Algorithms::Group is an array with one element per core which are not able to be moved around between cores. These are typically useful for gathering data from array elements on their core, and then processing or reducing it. See Charm++'s group chares for details
A Parallel::Algorithms::Nodegroup, which is similar to a group except that there is one element per node. For Charm++ SMP (shared memory parallelism) builds a node corresponds to the usual definition of a node on a supercomputer. However, for non-SMP builds nodes and cores are equivalent. We ensure that all entry method calls done through the Algorithm's explicit_single_action and receive_data functions are threadsafe. User controlled threading is possible by calling the non-entry method member function threaded_single_action.
Entry Methods and Remote Function Invocation
Charm++ refers to functions that can be called remotely as entry methods. The Parallel Components provide several generic entry methods. These fall into two classes:
Entry methods that perform a single Action once
Entry methods that iterate the Actions in the Algorithm's action_list.
Macro Definition Documentation
WRAPPED_PUPable_decl_base_template
#define WRAPPED_PUPable_decl_base_template (baseClassName, className) PUPable_decl_base_template(SINGLE_ARG(baseClassName), SINGLE_ARG(className))
Mark derived template classes as serializable.
Any class that derives off of a class template base class must contain this macro if it is to be serialized.
Referenced by CoordinateMap< SourceFrame, TargetFrame, Maps >::jacobian().
WRAPPED_PUPable_decl_template
#define WRAPPED_PUPable_decl_template (className) PUPable_decl_template(SINGLE_ARG(className))
Mark derived classes as serializable.
Any class that derives off of a non-class template base class must contain this macro if it is to be serialized.
Function Documentation
abort()
void Parallel::abort (const std::string & message) inline
Abort the program with an error message.
Referenced by abort_with_error_message(), and setup_error_handling().
contribute_to_reduction()
template<class SenderParallelComponent , class TargetParallelComponent , class Action , class Metavariables , class ArrayIndex , class ReductionType , Requires< not Parallel_detail::is_custom_reduction_type_v< ReductionType >> = nullptr> void Parallel::contribute_to_reduction (const ConstGlobalCache< Metavariables > & cache, const ArrayIndex & array_index, CkReduction::reducerType reducer, const ReductionType & reduction_data) noexcept
Perform a reduction from the current ParallelComponent to the TargetParallelComponent, performing the Action upon receiving the reduction.
The function must receive a ConstGlobalCache and ArrayIndex of the sending ParallelComponent. A Charm++ reducer specifying what type of reduction is to be done must also be passed (see here), as well as the data that is to be reduced.
Example
Built-in Charm++ reductions are supported as:
    Parallel::contribute_to_reduction<ArrayParallelComponent<Metavariables>,
                                      SingletonParallelComponent<Metavariables>,
                                      singleton_reduce_sum_int>(
        cache, array_index, CkReduction::sum_int, my_send_int);
and similarly custom reductions:
    Parallel::contribute_to_reduction<ArrayParallelComponent<Metavariables>,
                                      SingletonParallelComponent<Metavariables>,
                                      singleton_reduce_custom_reduction>(
        cache, array_index, reduction_data_reducer,
        Parallel::ReductionData<int, std::unordered_map<std::string, int>,
                                std::vector<int>>{
            10, std::move(my_send_map), std::vector<int>{array_index, 10, -8}});
deserialize()
template<typename T > T deserialize (const void *const data)
Deserialize an object using PUP.
Template Parameters
T the type to deserialize to
exit()
void Parallel::exit () inline
Exit the program normally. This should only be called once over all processors.
Referenced by Parallel::Main< Metavariables >::execute_next_phase(), and Parallel::Main< Metavariables >::Main().
first_proc_on_node()
int Parallel::first_proc_on_node (const int node_index) inline
Index of first processing element on the given node.
get() [1/2]
template<size_t Index, class... Us> auto Parallel::get (ReductionData< Us... > & reduction_data) -> decltype(std::get<Index>(reduction_data.data)) noexcept
Retrieve the Indexth element from a ReductionData<Ts...>, similar to std::get for std::tuples.
Note
Also available for rvalue and const references
get() [2/2]
template<typename ConstGlobalCacheTag , typename Metavariables > const ConstGlobalCache_detail::type_for_get< typename ConstGlobalCacheTag::type>::type& Parallel::get (const ConstGlobalCache< Metavariables > & cache) noexcept
Access data in the cache.
Requires: ConstGlobalCacheTag is a tag in tag_list
Returns: a constant reference to an object in the cache
References make_overloader().
get_parallel_component() [1/2]
template<typename ParallelComponentTag , typename Metavariables > Parallel::proxy_from_parallel_component<ParallelComponentTag>& Parallel::get_parallel_component (ConstGlobalCache< Metavariables > & cache) noexcept
Access the Charm++ proxy associated with a ParallelComponent.
Requires: ParallelComponentTag is a tag in component_list
Returns: a Charm++ proxy that can be used to call an entry method on the chare(s)
References tuples::get().
Referenced by Parallel::ConstGlobalCache< Metavariables >::ConstGlobalCache().
get_parallel_component() [2/2]
template<typename ParallelComponentTag , typename Metavariables > const Parallel::proxy_from_parallel_component<ParallelComponentTag>& Parallel::get_parallel_component (const ConstGlobalCache< Metavariables > & cache) noexcept
Access the Charm++ proxy associated with a ParallelComponent.
Requires: ParallelComponentTag is a tag in component_list
Returns: a Charm++ proxy that can be used to call an entry method on the chare(s)
References tuples::get().
local_rank_of()
int Parallel::local_rank_of (const int proc_index) inline
The local index for the given processing element on its node.
lock()
void Parallel::lock (const gsl::not_null< CmiNodeLock *> node_lock) inline noexcept
Lock a converse CmiNodeLock.
Referenced by AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::get_terminate().
my_local_rank()
int Parallel::my_local_rank () inline
The local index of my processing element on my node. This is in the interval 0, ..., procs_on_node(my_node()) - 1.
my_node()
int Parallel::my_node () inline
Index of my node.
Referenced by abort_with_error_message().
my_proc()
int Parallel::my_proc () inline
Index of my processing element.
Referenced by abort_with_error_message().
new_reduction_msg()
template<class... Ts> CkReductionMsg* Parallel::new_reduction_msg (ReductionData< Ts... > & reduction_data) noexcept
Convert a ReductionData to a CkReductionMsg. Used in custom reducers.
Example
See the return statement of:
CkReductionMsg* reduce_reduction_data(const int number_of_messages,
                                      CkReductionMsg** const msgs) {
  // clang-tidy: do not use pointer arithmetic
  Parallel::ReductionData<int, std::unordered_map<std::string, int>,
                          std::vector<int>>
      reduced(msgs[0]);  // NOLINT
  for (int msg_id = 1; msg_id < number_of_messages; ++msg_id) {
    // clang-tidy: do not use pointer arithmetic
    Parallel::ReductionData<int, std::unordered_map<std::string, int>,
                            std::vector<int>>
        current(msgs[msg_id]);  // NOLINT
    if (Parallel::get<0>(current) != Parallel::get<0>(reduced)) {
      Parallel::abort("Tried to reduce from different iteration values.");
    }
    // compute maximum of each value in an unordered_map
    for (const auto& string_double : Parallel::get<1>(current)) {
      if (string_double.second >
          Parallel::get<1>(reduced)[string_double.first]) {
        Parallel::get<1>(reduced)[string_double.first] = string_double.second;
      }
    }
    // compute sum of each element in a vector
    for (size_t i = 0; i < Parallel::get<2>(current).size(); ++i) {
      Parallel::get<2>(reduced)[i] += Parallel::get<2>(current)[i];
    }
  }
  return Parallel::new_reduction_msg(reduced);
}
node_of()
int Parallel::node_of (const int proc_index) inline
Index of the node for the given processing element.
number_of_nodes()
int Parallel::number_of_nodes () inline
Number of nodes.
number_of_procs()
int Parallel::number_of_procs () inline
Number of processing elements.
Referenced by Informer::print_startup_info().
printf()
template<typename... Args> void Parallel::printf (const std::string & format, Args &&... args) inline
Print an atomic message to stdout with C printf usage.
Similar to Python, you can print any object that's streamable by passing it in as an argument and using the formatter "%s". For example,
std::vector<double> a{0.8, 73, 9.8};
Parallel::printf("%s\n", a);
References disable_floating_point_exceptions().
Referenced by file_system::create_directory(), Parallel::Main< Metavariables >::Main(), Informer::print_exit_info(), and Informer::print_startup_info().
procs_on_node()
int Parallel::procs_on_node (const int node_index) inline
Number of processing elements on the given node.
serialize()
template<typename T , typename U > std::vector<char> serialize (const U & obj)
Serialize an object using PUP.
The type to serialize as must be explicitly specified. We require this because a mismatch between the serialize and deserialize calls causes undefined behavior and we do not want this to depend on inferred types for safety.
Template Parameters
T type to serialize
try_lock()
bool Parallel::try_lock (const gsl::not_null< CmiNodeLock *> node_lock) inline noexcept
Returns true if the lock was successfully acquired and false if the lock is already acquired by another processor.
unlock()
void Parallel::unlock (const gsl::not_null< CmiNodeLock *> node_lock) inline noexcept
Unlock a converse CmiNodeLock.
References db::apply().
Referenced by AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::get_terminate().
wall_time()
double Parallel::wall_time () inline
The current wall time in seconds.
Referenced by AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::get_terminate().