SpECTRE: Tensor
Tensor
Namespaces
Frame
Indicates the Frame that a TensorIndexType is in.
TensorMetafunctions
Contains all metafunctions related to Tensor manipulations.
tnsr
Type aliases to construct common Tensors.
Classes
struct Frame::FrameIsPhysical
Marks a Frame as being "physical" in the sense that it is meaningful to evaluate an analytic solution in that frame.
struct tt::is_tensor_index_type< T >
Inherits from std::true_type if T is a TensorIndexType.
class Tensor< X, Symm, IndexList< Indices... > >
Represents an object with multiple components.
Typedefs
template<typename CheckFrame >
using Frame::is_frame_physical = std::integral_constant< bool, cpp17::is_base_of_v< FrameIsPhysical, CheckFrame > >
Returns std::true_type if the frame is "physical" in the sense that it is meaningful to evaluate an analytic solution in that frame.
template<size_t SpatialDim, UpLo Ul, typename Fr >
using SpatialIndex = Tensor_detail::TensorIndexType< SpatialDim, Ul, Fr, IndexType::Spatial >
A SpatialIndex holds information about the number of spatial dimensions, whether the index is covariant or contravariant (UpLo), and the Frame the index is in.
template<size_t SpatialDim, UpLo Ul, typename Fr >
using SpacetimeIndex = Tensor_detail::TensorIndexType< SpatialDim, Ul, Fr, IndexType::Spacetime >
A SpacetimeIndex holds information about the number of spatial dimensions, whether the index is covariant or contravariant (UpLo), and the Frame the index is in.
template<typename Index >
using change_index_up_lo = Tensor_detail::TensorIndexType< Index::index_type==IndexType::Spatial ? Index::value :Index::value - 1, Index::ul==UpLo::Up ? UpLo::Lo :UpLo::Up, typename Index::Frame, Index::index_type >
Change the TensorIndexType to be covariant if it's contravariant and vice-versa.
template<typename Symmetry_t , typename Indices_t >
using TensorMetafunctions::independent_components = typename detail::number_of_independent_components_impl< Symmetry_t, Indices_t >::number_of_independent_components
Compute the number of independent components for a given Symmetry and TensorIndexType list.
template<typename Symmetry_t , typename Indices_t >
using TensorMetafunctions::number_of_components = typename detail::number_of_independent_components_impl< Symmetry_t, Indices_t >::number_of_components
Compute the number of components for a given Symmetry and TensorIndexType list.
template<typename IndexList , typename TensorIndex >
using TensorMetafunctions::increment_tensor_index = typename detail::increment_tensor_index_impl<(tmpl::at< TensorIndex, tmpl::size_t< 0 > >::value+1 >=tmpl::at< IndexList, tmpl::size_t< 0 > >::dim)>::template type< IndexList, TensorIndex, 0 >
Increment a tensor index.
template<typename Symm , typename TensorIndex , size_t Rank, size_t I, size_t Offset>
using TensorMetafunctions::tensor_index_to_swap = typename detail::tensor_index_to_swap_impl< Rank==Offset+1 >::template type< Symm, TensorIndex, tmpl::size_t< Rank >, tmpl::size_t< I >, tmpl::size_t< Offset > >
template<typename Symm , typename IndexList , typename TensorIndex >
using TensorMetafunctions::canonicalize_tensor_index = typename detail::canonicalize_tensor_index_impl<(tmpl::size< IndexList >::value > 0)>::template type< Symm, IndexList, TensorIndex, tmpl::size< IndexList >::value, 0 >
template<typename TensorIndex , typename IndexList >
using TensorMetafunctions::compute_collapsed_index = typename detail::compute_collapsed_index_impl<(tmpl::size< TensorIndex >::value > 1)>::template type< TensorIndex, IndexList >
template<typename IndexList , typename CanonicalTensorIndex , typename TensorIndex , typename CollapsedToStorageList , typename I , typename Count >
using TensorMetafunctions::update_collapsed_to_storage_using_canonical_tensor_index = typename detail::update_collapsed_to_storage_using_canonical_tensor_index_impl< std::is_same< CanonicalTensorIndex, TensorIndex >::value >::template type< IndexList, CanonicalTensorIndex, TensorIndex, CollapsedToStorageList, I, Count >
template<typename CanonicalizeTensorIndex , typename TI , typename Count >
using TensorMetafunctions::increase_count = tmpl::conditional_t< std::is_same< CanonicalizeTensorIndex, TI >::value, tmpl::size_t< Count::value+1 >, Count >
given a TensorIndex checks if it is the canonical form, if so returns tmpl::plus<Count, tmpl::size_t<1>> otherwise returns Count
template<typename IndexList , typename Symm , typename NumComps >
using TensorMetafunctions::compute_collapsed_to_storage = typename detail::compute_collapsed_to_storage_impl<(0< NumComps::value - 1)>::template type< tmpl::filled_list< tmpl::size_t< 0 >, NumComps::value >, IndexList, Symm, tmpl::filled_list< tmpl::size_t< 0 >, tmpl::size< IndexList >::value >, tmpl::size_t< 0 >, tmpl::size_t< 0 >, NumComps >
Compute the collapse index to storage index typelist.
template<typename Symm , typename IndexList , typename CollapsedToStorageList , typename NumIndComps >
using TensorMetafunctions::compute_storage_to_tensor = typename detail::compute_storage_to_tensor_impl<(tmpl::size< CollapsedToStorageList >::value > 1) ? 2 :(tmpl::size< CollapsedToStorageList >::value==2 and std::is_same< tmpl::back< CollapsedToStorageList >, tmpl::list< tmpl::size_t< 0 > >>::value) ? 1 :0 >::template type< Symm, IndexList, CollapsedToStorageList, tmpl::filled_list< tmpl::size_t< 0 >, tmpl::size< IndexList >::value >, tmpl::filled_list< tmpl::size_t< 0 >, NumIndComps::value > >
Compute a typelist holding the tensor index for each storage index.
template<typename CollapsedToStorageList , typename NumIndComps >
using TensorMetafunctions::compute_multiplicity = typename detail::compute_multiplicity_impl<(tmpl::size< CollapsedToStorageList >::value > 1)>::template type< CollapsedToStorageList, tmpl::filled_list< tmpl::size_t< 0 >, NumIndComps::value > >
Compute typelist of the multiplicity of each storage index of a Tensor.
template<typename Symm , typename IndexList >
using TensorMetafunctions::check_index_symmetry = typename detail::check_index_symmetry_impl< tmpl::size< Symm >::value==0 ? 0 :2 >::template type< Symm, IndexList, tmpl::map<> >
Check that each of symmetric indices is in the same frame and have the same dimensionality.
template<typename Tensor_t , std::size_t VolumeDim, UpLo Ul, typename Fr = Frame::Grid>
using TensorMetafunctions::prepend_spatial_index = Tensor< typename Tensor_t::type, tmpl::push_front< typename Tensor_t::symmetry, tmpl::int32_t< 1+tmpl::fold< typename Tensor_t::symmetry, tmpl::int32_t< 0 >, tmpl::max< tmpl::_state, tmpl::_element > >::value > >, tmpl::push_front< typename Tensor_t::index_list, SpatialIndex< VolumeDim, Ul, Fr > >>
Add a spatial index to the from of a Tensor.
template<typename Tensor_t , std::size_t VolumeDim, UpLo Ul, typename Fr = Frame::Grid>
using TensorMetafunctions::prepend_spacetime_index = Tensor< typename Tensor_t::type, tmpl::push_front< typename Tensor_t::symmetry, tmpl::int32_t< 1+tmpl::fold< typename Tensor_t::symmetry, tmpl::int32_t< 0 >, tmpl::max< tmpl::_state, tmpl::_element > >::value > >, tmpl::push_front< typename Tensor_t::index_list, SpacetimeIndex< VolumeDim, Ul, Fr > >>
Add a spacetime index to the from of a Tensor.
template<std::int32_t... T>
using Symmetry = typename detail::symm< T... >::type
Computes the canonical symmetry from the integers T
template<typename T >
using Scalar = Tensor< T, Symmetry<>, index_list<> >
Scalar type.
Enumerations
enum UpLo { UpLo::Up, UpLo::Lo }
Whether a TensorIndexType is covariant or contravariant.
enum IndexType : char { IndexType::Spatial, IndexType::Spacetime }
Indicates whether the TensorIndexType is Spatial or Spacetime.
Functions
template<typename T , typename Symm , typename Index0 , typename Index1 >
Scalar< T > determinant (const Tensor< T, Symm, index_list< Index0, Index1 >> &tensor)
Computes the determinant of a rank-2 Tensor tensor.
template<typename T , typename Symm , typename Index0 , typename Index1 >
std::pair< Scalar< T >, Tensor< T, Symm, typelist< change_index_up_lo< Index1 >, change_index_up_lo< Index0 > > > > determinant_and_inverse (const Tensor< T, Symm, typelist< Index0, Index1 >> &tensor)
Computes the determinant and inverse of a rank-2 Tensor.
template<typename TensorType >
TensorType divide_by (TensorType tensor, const DataVector &divisor)
Divides the components of a tensor by a scalar.
template<typename DataType , typename Index >
DataType magnitude (const Tensor< DataType, Symmetry< 1 >, typelist< Index >> &tensor)
compute the Euclidean magnitude of a rank-1 tensor
template<typename DataType , typename Index0 , typename Index1 >
DataType magnitude (const Tensor< DataType, Symmetry< 1 >, typelist< Index0 >> &tensor, const Tensor< DataType, Symmetry< 1, 1 >, typelist< Index1, Index1 >> &metric)
compute the magnitude of a rank-1 tensor
Variables
template<typename CheckFrame >
constexpr bool Frame::is_frame_physical_v = is_frame_physical<CheckFrame>::value
Returns true if the frame is "physical" in the sense that it is meaningful to evaluate an analytic solution in that frame.
Detailed Description
Tensor use documentation.
Typedef Documentation
canonicalize_tensor_index
template<typename Symm , typename IndexList , typename TensorIndex > using TensorMetafunctions::canonicalize_tensor_index = typedef typename detail::canonicalize_tensor_index_impl<(tmpl::size<IndexList>::value > 0)>::template type<Symm, IndexList, TensorIndex, tmpl::size<IndexList>::value, 0>
change_index_up_lo
template<typename Index > using change_index_up_lo = Tensor_detail::TensorIndexType< Index::index_type == IndexType::Spatial ? Index::value : Index::value - 1, Index::ul == UpLo::Up ? UpLo::Lo : UpLo::Up, typename Index::Frame, Index::index_type>
Change the TensorIndexType to be covariant if it's contravariant and vice-versa.
Here is an example of how to use change_index_up_lo
using Index = SpatialIndex<3, UpLo::Lo, Frame::Grid>;
using UpIndex = change_index_up_lo<Index>;
static_assert(cpp17::is_same_v<UpIndex, SpatialIndex<3, UpLo::Up, Frame::Grid>>,
              "Failed testing change_index_up_lo");
Template Parameters
Index the TensorIndexType to change
check_index_symmetry
template<typename Symm , typename IndexList > using TensorMetafunctions::check_index_symmetry = typedef typename detail::check_index_symmetry_impl< tmpl::size<Symm>::value == 0 ? 0 : 2>::template type<Symm, IndexList, tmpl::map<> >
Check that each of symmetric indices is in the same frame and have the same dimensionality.
compute_collapsed_index
template<typename TensorIndex , typename IndexList > using TensorMetafunctions::compute_collapsed_index = typedef typename detail::compute_collapsed_index_impl<(tmpl::size<TensorIndex>::value > 1)>::template type<TensorIndex, IndexList>
Requires: is_a<typelist, IndexList>::value is true, tt::is_a<typelist, TensorIndex>::value is true, and tmpl::all<TensorIndex, is_a<std::integral_constant, tmpl::_1>>::value is true
compute_collapsed_to_storage
template<typename IndexList , typename Symm , typename NumComps > using TensorMetafunctions::compute_collapsed_to_storage = typedef typename detail:: compute_collapsed_to_storage_impl<(0 < NumComps::value - 1)>::template type< tmpl::filled_list<tmpl::size_t<0>, NumComps::value>, IndexList, Symm, tmpl::filled_list<tmpl::size_t<0>, tmpl::size<IndexList>::value>, tmpl::size_t<0>, tmpl::size_t<0>, NumComps>
Compute the collapse index to storage index typelist.
compute_multiplicity
template<typename CollapsedToStorageList , typename NumIndComps > using TensorMetafunctions::compute_multiplicity = typedef typename detail::compute_multiplicity_impl<(tmpl::size<CollapsedToStorageList>::value > 1)>::template type<CollapsedToStorageList, tmpl::filled_list<tmpl::size_t<0>, NumIndComps::value> >
Compute typelist of the multiplicity of each storage index of a Tensor.
Details
The multiplicity of a storage index is the number of tensor components it represents. For example, if a tensor is symmetric then the multiplicity for the storage index's representing symmetric terms have a multiplicity of 2. Specifically, consider a rank-2 symmetric tensor \(T_{ab}\), let the storage of the \(T_{02}\) component be N, for example. Then, since \(T_{20} = T_{02}\)
using result = tmpl::at<ComputeMultiplicity<ColToStor, NumIndComps>,
                         tmpl::size_t<5>> = tmpl::size_t<2>;
compute_storage_to_tensor
template<typename Symm , typename IndexList , typename CollapsedToStorageList , typename NumIndComps > using TensorMetafunctions::compute_storage_to_tensor = typedef typename detail::compute_storage_to_tensor_impl< (tmpl::size<CollapsedToStorageList>::value > 1) ? 2 : (tmpl::size<CollapsedToStorageList>::value == 2 and std::is_same<tmpl::back<CollapsedToStorageList>, tmpl::list<tmpl::size_t<0> >>::value) ? 1 : 0>:: template type< Symm, IndexList, CollapsedToStorageList, tmpl::filled_list<tmpl::size_t<0>, tmpl::size<IndexList>::value>, tmpl::filled_list<tmpl::size_t<0>, NumIndComps::value> >
Compute a typelist holding the tensor index for each storage index.
increase_count
template<typename CanonicalizeTensorIndex , typename TI , typename Count > using TensorMetafunctions::increase_count = typedef tmpl::conditional_t<std::is_same<CanonicalizeTensorIndex, TI>::value, tmpl::size_t<Count::value + 1>, Count>
given a TensorIndex checks if it is the canonical form, if so returns tmpl::plus<Count, tmpl::size_t<1>> otherwise returns Count
increment_tensor_index
template<typename IndexList , typename TensorIndex > using TensorMetafunctions::increment_tensor_index = typedef typename detail::increment_tensor_index_impl<(tmpl::at<TensorIndex, tmpl::size_t<0> >::value + 1 >= tmpl::at<IndexList, tmpl::size_t<0> >::dim)>::template type<IndexList, TensorIndex, 0>
Increment a tensor index.
Details
Given a tensor index TensorIndex and a list of TensorIndex's, IndexList, increment the tensor index to the next component. Incrementing is done by incremeting the first (left-most) index first, once it reaches the dimensionality of that index, the next index is increment. That is, for a tensor \(T_{abc}\) where all indices are 3-dimensional, incrementing the index \((1, 3, 0)\) results in the index \((2, 3, 0)\), and incrementing the index \((3, 3, 0)\) results \((0, 0, 1)\).
For a typelist of TensorIndexType's IndexList and a tensor index (typelist of std::integral_constant) TensorIndex,
using result = IncrementTensorIndex<IndexList, TensorIndex>;
Returns: typelist<std::integral_constant...>
Semantics: Let IndexList by a typelist
typelist<SpacetimeTensorIndex<3, UpLo::Lo, Frame::Grid>,
         SpacetimeTensorIndex<3, UpLo::Lo, Frame::Grid>,
         SpacetimeTensorIndex<3, UpLo::Lo, Frame::Grid>>;
and TensorIndex be tmpl::integral_list<int, 3, 3, 0>, then
using result = tmpl::integral_list<int, 0, 0, 1>;
independent_components
template<typename Symmetry_t , typename Indices_t > using TensorMetafunctions::independent_components = typedef typename detail::number_of_independent_components_impl< Symmetry_t, Indices_t>::number_of_independent_components
Compute the number of independent components for a given Symmetry and TensorIndexType list.
Template Parameters
Symmetry_t Symmetry of the Tensor
Indices_t typelist of the TensorIndex's of the Tensor
is_frame_physical
template<typename CheckFrame > using Frame::is_frame_physical = typedef std::integral_constant<bool, cpp17::is_base_of_v<FrameIsPhysical, CheckFrame> >
Returns std::true_type if the frame is "physical" in the sense that it is meaningful to evaluate an analytic solution in that frame.
Example
static_assert(not Frame::is_frame_physical_v<Frame::Logical>,
              "Failed testing Frame::is_frame_physical");
static_assert(not Frame::is_frame_physical_v<Frame::Distorted>,
              "Failed testing Frame::is_frame_physical");
static_assert(not Frame::is_frame_physical_v<Frame::Grid>,
              "Failed testing Frame::is_frame_physical");
static_assert(Frame::is_frame_physical_v<Frame::Inertial>,
              "Failed testing Frame::is_frame_physical");
number_of_components
template<typename Symmetry_t , typename Indices_t > using TensorMetafunctions::number_of_components = typedef typename detail::number_of_independent_components_impl< Symmetry_t, Indices_t>::number_of_components
Compute the number of components for a given Symmetry and TensorIndexType list.
Template Parameters
Symmetry_t Symmetry of the Tensor
Indices_t typelist of the TensorIndex's of the Tensor
prepend_spacetime_index
template<typename Tensor_t , std::size_t VolumeDim, UpLo Ul, typename Fr = Frame::Grid> using TensorMetafunctions::prepend_spacetime_index = typedef Tensor< typename Tensor_t::type, tmpl::push_front< typename Tensor_t::symmetry, tmpl::int32_t< 1 + tmpl::fold<typename Tensor_t::symmetry, tmpl::int32_t<0>, tmpl::max<tmpl::_state, tmpl::_element> >::value> >, tmpl::push_front<typename Tensor_t::index_list, SpacetimeIndex<VolumeDim, Ul, Fr> >>
Add a spacetime index to the from of a Tensor.
Template Parameters
Tensor_t the tensor type to prepend
VolumeDim the volume dimension of the tensor index to prepend
Fr the Frame of the tensor index to prepend
prepend_spatial_index
template<typename Tensor_t , std::size_t VolumeDim, UpLo Ul, typename Fr = Frame::Grid> using TensorMetafunctions::prepend_spatial_index = typedef Tensor< typename Tensor_t::type, tmpl::push_front< typename Tensor_t::symmetry, tmpl::int32_t< 1 + tmpl::fold<typename Tensor_t::symmetry, tmpl::int32_t<0>, tmpl::max<tmpl::_state, tmpl::_element> >::value> >, tmpl::push_front<typename Tensor_t::index_list, SpatialIndex<VolumeDim, Ul, Fr> >>
Add a spatial index to the from of a Tensor.
Template Parameters
Tensor_t the tensor type to prepend
VolumeDim the volume dimension of the tensor index to prepend
Fr the Frame of the tensor index to prepend
Scalar
template<typename T > using Scalar = Tensor<T, Symmetry<>, index_list<> >
Scalar type.
SpacetimeIndex
template<size_t SpatialDim, UpLo Ul, typename Fr > using SpacetimeIndex = Tensor_detail::TensorIndexType<SpatialDim, Ul, Fr, IndexType::Spacetime>
A SpacetimeIndex holds information about the number of spatial dimensions, whether the index is covariant or contravariant (UpLo), and the Frame the index is in.
Template Parameters
SpatialDim the spatial dimensionality of the TensorIndexType
Ul either UpLo::Up or UpLo::Lo for contra or covariant
Fr the Frame the TensorIndexType is in
SpatialIndex
template<size_t SpatialDim, UpLo Ul, typename Fr > using SpatialIndex = Tensor_detail::TensorIndexType<SpatialDim, Ul, Fr, IndexType::Spatial>
A SpatialIndex holds information about the number of spatial dimensions, whether the index is covariant or contravariant (UpLo), and the Frame the index is in.
Template Parameters
SpatialDim the spatial dimensionality of the TensorIndexType
Ul either UpLo::Up or UpLo::Lo for contra or covariant
Fr the Frame the TensorIndexType is in
Symmetry
template<std::int32_t... T> using Symmetry = typename detail::symm<T...>::type
Computes the canonical symmetry from the integers T
Details
Compute the canonical symmetry typelist given a set of integers, T. The resulting typelist is in descending order of the absolute value of the integers. For example, the result of Symmetry<1, 2, 3> is integral_list<int32_t, 3, 2, 1>. Anti-symmetries can be denoted with a minus sign on either or both indices. That is, Symmetry<-1, 2, 1> is anti-symmetric in the first and last index and is the same as Symmetry<-1, 2, -1>. Note: two minus signs are still anti-symmetric because it simplifies the algorithm used to compute the canonical form of the symmetry.
Template Parameters
T the integers denoting the symmetry of the Tensor
tensor_index_to_swap
template<typename Symm , typename TensorIndex , size_t Rank, size_t I, size_t Offset> using TensorMetafunctions::tensor_index_to_swap = typedef typename detail::tensor_index_to_swap_impl< Rank == Offset + 1>::template type<Symm, TensorIndex, tmpl::size_t<Rank>, tmpl::size_t<I>, tmpl::size_t<Offset> >
update_collapsed_to_storage_using_canonical_tensor_index
template<typename IndexList , typename CanonicalTensorIndex , typename TensorIndex , typename CollapsedToStorageList , typename I , typename Count > using TensorMetafunctions::update_collapsed_to_storage_using_canonical_tensor_index = typedef typename detail:: update_collapsed_to_storage_using_canonical_tensor_index_impl< std::is_same<CanonicalTensorIndex, TensorIndex>::value>:: template type<IndexList, CanonicalTensorIndex, TensorIndex, CollapsedToStorageList, I, Count>
Note
Cannot use std::conditional_t because typelist<> will fail
Enumeration Type Documentation
IndexType
enum IndexType : char strong
Indicates whether the TensorIndexType is Spatial or Spacetime.
Enumerator
Spatial
The TensorIndexType is purely spatial.
Spacetime
The TensorIndexType is a spacetime index.
UpLo
enum UpLo strong
Whether a TensorIndexType is covariant or contravariant.
Enumerator
Up
Contravariant, or Upper index.
Lo
Covariant, or Lower index.
Function Documentation
determinant()
template<typename T , typename Symm , typename Index0 , typename Index1 > Scalar<T> determinant (const Tensor< T, Symm, index_list< Index0, Index1 >> & tensor)
Computes the determinant of a rank-2 Tensor tensor.
Returns: The determinant of tensor.
Requires: That tensor be a rank-2 Tensor, with both indices sharing the same dimension and type.
References db::apply().
determinant_and_inverse()
template<typename T , typename Symm , typename Index0 , typename Index1 > std::pair<Scalar<T>, Tensor<T, Symm, typelist<change_index_up_lo<Index1>, change_index_up_lo<Index0> > > > determinant_and_inverse (const Tensor< T, Symm, typelist< Index0, Index1 >> & tensor)
Computes the determinant and inverse of a rank-2 Tensor.
Computes the determinant and inverse together, because this leads to fewer operations compared to computing the determinant independently.
Parameters
tensor the input rank-2 Tensor.
Returns: a std::pair that holds the determinant (in pair.first) and inverse (in pair.second) of the input tensor.
Details
Treats the input rank-2 tensor as a matrix. The first (second) index of the tensor corresponds to the rows (columns) of the matrix. The determinant is a scalar tensor. The inverse is a rank-2 tensor whose indices are reversed and of opposite valence relative to the input tensor, i.e. given \(T_a^b\) returns \((Tinv)_b^a\).
Note
When inverting a 4x4 spacetime metric, it is typically more efficient to use the 3+1 decomposition of the 4-metric in terms of lapse, shift, and spatial 3-metric, in which only the spatial 3-metric needs to be inverted.
References db::apply().
Referenced by CoordinateMaps::Wedge2D::inv_jacobian(), and CoordinateMaps::Wedge3D::inv_jacobian().
divide_by()
template<typename TensorType > TensorType divide_by (TensorType tensor, const DataVector & divisor)
Divides the components of a tensor by a scalar.
Returns: a tensor of the same type as the input tensor
References ASSERT, and DataVector::size().
magnitude() [1/2]
template<typename DataType , typename Index > DataType magnitude (const Tensor< DataType, Symmetry< 1 >, typelist< Index >> & tensor)
compute the Euclidean magnitude of a rank-1 tensor
Returns: the Euclidean magnitude of the rank-1 tensor
Details
Computes the square root of the sum of the squares of the components of the rank-1 tensor.
References square().
magnitude() [2/2]
template<typename DataType , typename Index0 , typename Index1 > DataType magnitude (const Tensor< DataType, Symmetry< 1 >, typelist< Index0 >> & tensor, const Tensor< DataType, Symmetry< 1, 1 >, typelist< Index1, Index1 >> & metric)
compute the magnitude of a rank-1 tensor
Returns: the magnitude of the rank-1 tensor
Details
Returns the square root of the input tensor contracted twice with the given metric.
References Parallel::value.
Variable Documentation
is_frame_physical_v
template<typename CheckFrame > constexpr bool Frame::is_frame_physical_v = is_frame_physical<CheckFrame>::value
Returns true if the frame is "physical" in the sense that it is meaningful to evaluate an analytic solution in that frame.
Example
static_assert(not Frame::is_frame_physical_v<Frame::Logical>,
              "Failed testing Frame::is_frame_physical");
static_assert(not Frame::is_frame_physical_v<Frame::Distorted>,
              "Failed testing Frame::is_frame_physical");
static_assert(not Frame::is_frame_physical_v<Frame::Grid>,
              "Failed testing Frame::is_frame_physical");
static_assert(Frame::is_frame_physical_v<Frame::Inertial>,
              "Failed testing Frame::is_frame_physical");