SpECTRE: Utilities
Utilities
A collection of useful classes, functions and metafunctions.
Namespaces
gsl
Implementations from the Guideline Support Library.
tmpl2
Metaprogramming things that are not planned to be submitted to Brigand.
Classes
class Informer
The Informer manages textual output regarding the status of a simulation.
class Deferred< Rt >
Provides deferred or lazy evaluation of a function or function object, as well as efficient storage of an object that is mutable.
class ContinuedFraction< T >
Compute the continued fraction representation of a number.
class ContinuedFractionSummer< Fraction >
Sum a continued fraction.
class gsl::not_null< T >
Require a pointer to not be a nullptr
struct NoSuchType
Used to mark "no type" or "bad state" for metaprogramming.
class Overloader< Fs >
Used for overloading lambdas, useful for lambda-SFINAE.
struct PointerVector< Type, AF, PF, TF >
A raw pointer endowed with expression template support via the Blaze library.
class tuples::TaggedTuple< Tags >
An associative container that is indexed by structs.
struct tmpl2::value_list< T,... >
A compile-time list of values of the same type.
struct TypeDisplayer<... >
Get compiler error with type of template parameter.
struct cpp17::void_type
Mark a return type as being "void". In C++17 void is a regular type under certain circumstances, so this can be replaced by void then.
Macros
#define DEFINE_FAKE_VIRTUAL(function)
Define a function that acts similarly to a virtual function, but can take template parameters.
#define SPECTRE_ALWAYS_INLINE inline
Always inline a function. Only use this if you benchmarked the code.
#define SPECTRE_JUST_ALWAYS_INLINE
Always inline a function, but do not mark it inline
#define GENERATE_INSTANTIATIONS(INSTANTIATION_MACRO, ...)
Macro useful for generating many explicit instantiations of function or class templates.
#define LIKELY(x) (x)
#define UNLIKELY(x) (x)
Typedefs
template<typename Sequence >
using make_boost_variant_over = typename detail::make_boost_variant_over_impl< Sequence >::type
Create a boost::variant with all all the types inside the typelist Sequence.
template<bool B>
using Requires = typename Requires_detail::requires_impl< B >::template_error_type_failed_to_meet_requirements_on_template_parameters
Express requirements on the template parameters of a function or class, replaces std::enable_if_t
template<typename T >
using tuples::TaggedTupleTypelist = typename TaggedTuple_detail::tagged_tuple_typelist_impl< T >::type
template<typename... Ts>
using typelist = tmpl::list< Ts... >
Construct a typelist of types Ts.
template<bool... Bs>
using tmpl2::flat_all = std::is_same< value_list< bool, Bs... >, value_list< bool,(static_cast< void >(Bs), true)... > >
A non-short-circuiting logical AND between bools 'B"".
template<bool... Bs>
using tmpl2::flat_any = std::integral_constant< bool, not std::is_same< value_list< bool, Bs... >, value_list< bool,(static_cast< void >(Bs), false)... > >::value >
A non-short-circuiting logical OR between bools 'B"".
Functions
std::string info_from_build ()
Information about the version, date, host, git commit, and link time.
std::string spectre_version ()
Retrieve a string containing the current version of SpECTRE.
int spectre_major_version ()
Returns major version.
int spectre_minor_version ()
Returns minor version.
int spectre_patch_version ()
Returns patch version.
double ddot_ (const size_t &N, const double *X, const size_t &INCX, const double *Y, const size_t &INCY)
template<typename Fp , typename... Args>
Deferred< Rt1 > make_deferred (Fp f, Args &&... args)
Create a deferred function call object.
template<typename T >
decltype(auto) dereference_wrapper (T &&t)
Returns the reference object held by a reference wrapper, if a non-reference_wrapper type is passed in then the object is returned.
template<typename Fraction , typename T1 , typename T2 >
Fraction simplest_fraction_in_interval (const T1 &end1, const T2 &end2) noexcept
Find the fraction in the supplied interval with the smallest denominator.
template<class T , class U >
constexpr T gsl::narrow_cast (U &&u) noexcept
Cast u to a type T where the cast may result in narrowing.
template<class T , class U >
T gsl::narrow (U u)
A checked version of narrow_cast() that ERRORs if the cast changed the value.
constexpr size_t operator"" _st (const unsigned long long n)
Defines the _st size_t suffix.
template<std::size_t size, typename T >
constexpr std::array< std::decay_t< T >, size > make_array (T &&value) noexcept(noexcept(make_array(std::integral_constant< std::size_t, size >{}, std::forward< T >(value))))
Helper class to initialize a std::array.
template<typename T , typename... V, Requires<(sizeof...(V) > 0>
constexpr std::array< typename std::decay_t< T >, sizeof...(V)+1 > make_array (T &&t, V &&... values) noexcept(noexcept(std::array< std::decay_t< T >, sizeof...(V)+1 >{ {std::forward< T >(t), std::forward< V >(values)...}}))
Helper function to initialize a std::array with varying number of arguments.
template<typename T , size_t size, typename Seq >
constexpr std::array< T, size > make_array (Seq &&seq) noexcept(noexcept(MakeArray_detail::make_array_from_iterator_impl< T, size >(std::forward< Seq >(seq), std::make_index_sequence< size >{})))
Create an std::array<T, size> from the first size values of seq
template<typename T >
T number_of_digits (const T number)
Returns the number of digits in an integer number.
template<class... Fs>
OVERLOADER_CONSTEXPR Overloader< Fs... > make_overloader (Fs... fs)
Create Overloader<Fs...>, see Overloader for details.
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::list< T > &v)
Output the items of a std::list.
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::vector< T > &v)
Output the items of a std::vector.
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::deque< T > &v)
Output the items of a std::deque.
template<typename T , size_t N>
std::ostream & operator<< (std::ostream &os, const std::array< T, N > &a)
Output the items of a std::array.
template<typename... Args>
std::ostream & operator<< (std::ostream &os, const std::tuple< Args... > &t)
Stream operator for tuples.
template<typename K , typename V , typename H >
std::ostream & operator<< (std::ostream &os, const std::unordered_map< K, V, H > &m)
Output all the key, value pairs of a std::unordered_map.
template<typename K , typename V , typename C >
std::ostream & operator<< (std::ostream &os, const std::map< K, V, C > &m)
Output all the key, value pairs of a std::map.
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::unordered_set< T > &v)
Output the items of a std::unordered_set.
template<typename T , typename C >
std::ostream & operator<< (std::ostream &os, const std::set< T, C > &v)
Output the items of a std::set.
template<typename T , Requires< tt::is_streamable< std::ostream, T >::value > >
std::ostream & operator<< (std::ostream &os, const std::unique_ptr< T > &t)
Stream operator for std::unique_ptr.
template<typename T , Requires< tt::is_streamable< std::ostream, T >::value > >
std::ostream & operator<< (std::ostream &os, const std::shared_ptr< T > &t)
Stream operator for std::shared_ptr.
template<typename T , typename U >
std::ostream & operator<< (std::ostream &os, const std::pair< T, U > &t)
Stream operator for std::pair.
template<typename K , typename V , typename H >
std::string keys_of (const std::unordered_map< K, V, H > &m)
Construct a string containing the keys of a std::unordered_map.
template<typename K , typename V , typename C >
std::string keys_of (const std::map< K, V, C > &m)
Construct a string containing the keys of a std::map.
template<typename... Args>
std::string formatted_string (const std::string &fmt, Args... args)
Format a string like printf.
std::string current_date_and_time ()
Get the current date and time.
template<size_t ElementToRemove, typename T , size_t Dim>
std::array< T, Dim - 1 > all_but_specified_element_of (const std::array< T, Dim > &a) noexcept
Construct an array from an existing array omitting one element.
template<typename... Ts>
constexpr void swallow (Ts &&...) noexcept
Allows zero-cost unordered expansion of a parameter.
template<bool ReverseIteration = false, typename... Elements, typename N_aryOp , typename... Args>
constexpr void tuple_transform (const std::tuple< Elements... > &tuple, N_aryOp &&op, Args &&... args) noexcept(noexcept(tuple_impl_detail::tuple_transform_impl< ReverseIteration >(tuple, std::forward< N_aryOp >(op), std::make_index_sequence< sizeof...(Elements)>{}, args...)))
Perform a transform over a std::tuple.
Variables
template<bool... Bs>
constexpr bool tmpl2::flat_all_v = flat_all<Bs...>::value
A non-short-circuiting logical AND between bools 'B"".
template<bool... Bs>
constexpr bool tmpl2::flat_any_v = flat_any<Bs...>::value
A non-short-circuiting logical OR between bools 'B"".
template<bool UseLibXsmm = false>
void dgemm_ (const char &TRANSA, const char &TRANSB, const size_t &M, const size_t &N, const size_t &K, const double &ALPHA, const double *A, const size_t &LDA, const double *B, const size_t &LDB, const double &BETA, double *C, const size_t &LDC)
Perform a matrix-matrix multiplication.
template<>
void dgemm_< true > (const char &TRANSA, const char &TRANSB, const size_t &M, const size_t &N, const size_t &K, const double &ALPHA, const double *A, const size_t &LDA, const double *B, const size_t &LDB, const double &BETA, double *C, const size_t &LDC)
Perform a matrix-matrix multiplication.
void dgemv_ (const char &TRANS, const size_t &M, const size_t &N, const double &ALPHA, const double *A, const size_t &LDA, const double *X, const size_t &INCX, const double &BETA, double *Y, const size_t &INCY)
Perform a matrix-vector multiplication.
template<class T , std::size_t N, typename Size >
constexpr T & gsl::at (std::array< T, N > &arr, Size index)
Retrieve a entry from a container, with checks in Debug mode that the index being retrieved is valid.
template<class Cont , typename Size >
constexpr const Cont::value_type & gsl::at (const Cont &cont, Size index)
Retrieve a entry from a container, with checks in Debug mode that the index being retrieved is valid.
template<class T , typename Size >
constexpr const T & gsl::at (std::initializer_list< T > cont, Size index)
Retrieve a entry from a container, with checks in Debug mode that the index being retrieved is valid.
template<typename T >
T magnitude (const std::array< T, 1 > &a) noexcept
Euclidean magnitude of the elements of the array.
template<>
double magnitude (const std::array< double, 1 > &a) noexcept
Euclidean magnitude of the elements of the array.
template<typename T >
T magnitude (const std::array< T, 2 > &a) noexcept
Euclidean magnitude of the elements of the array.
template<typename T >
T magnitude (const std::array< T, 3 > &a) noexcept
Euclidean magnitude of the elements of the array.
template<class Tag , class... Tags>
constexpr const Tag::type & tuples::get (const TaggedTuple< Tags... > &t) noexcept
Retrieve the element of Tag in the TaggedTuple.
template<class Tag , class... Tags>
constexpr Tag::type & tuples::get (TaggedTuple< Tags... > &t) noexcept
Retrieve the element of Tag in the TaggedTuple.
template<class Tag , class... Tags>
constexpr const Tag::type && tuples::get (const TaggedTuple< Tags... > &&t) noexcept
Retrieve the element of Tag in the TaggedTuple.
template<class Tag , class... Tags>
constexpr Tag::type && tuples::get (TaggedTuple< Tags... > &&t) noexcept
Retrieve the element of Tag in the TaggedTuple.
template<bool ReverseIteration = false, typename... Elements, typename N_aryOp , typename... Args>
constexpr void tuple_fold (const std::tuple< Elements... > &tuple, N_aryOp &&op, Args &&... args) noexcept(noexcept(tuple_impl_detail::tuple_fold_impl< ReverseIteration >(tuple, std::forward< N_aryOp >(op), std::make_index_sequence< sizeof...(Elements)>{}, args...)))
Perform a fold over a std::tuple.
template<bool ReverseIteration = false, typename... Elements, typename N_aryOp , typename... Args>
constexpr void tuple_counted_fold (const std::tuple< Elements... > &tuple, N_aryOp &&op, Args &&... args) noexcept(noexcept(tuple_impl_detail::tuple_counted_fold_impl< ReverseIteration >(tuple, std::forward< N_aryOp >(op), std::make_index_sequence< sizeof...(Elements)>{}, args...)))
Perform a fold over a std::tuple.
Detailed Description
A collection of useful classes, functions and metafunctions.
Macro Definition Documentation
DEFINE_FAKE_VIRTUAL
#define DEFINE_FAKE_VIRTUAL (function)
Define a function that acts similarly to a virtual function, but can take template parameters.
Details
DEFINE_FAKE_VIRTUAL(func) defines the function fake_virtual_func and the struct FakeVirtualInherit_func. It should usually be called in a detail namespace.
A base class Base using this functionality should define a type
using Inherit = FakeVirtualInherit_func<Base>;
and a member function func wrapping fake_virtual_func, with the wrapper passing the derived classes as a typelist as the first template argument and the this pointer as the first normal argument.
Derived classes should then inherit from Base::Inherit instead of directly from Base. (Base::Inherit inherits from Base.)
If the base class has no pure virtual functions remaining it will generally be desirable to mark the constructors and assignment operators protected so that a bare base class cannot be instantiated.
If it is necessary to use multiple fake virtual functions with the same base class, the Inherit definition can nest the fake virtual classes:
using Inherit = FakeVirtualInherit_func1<FakeVirtualInherit_func2<Base>>;
Example
DEFINE_FAKE_VIRTUAL(fv)
class Derived;
class Base {
 public:
  using Inherit = FakeVirtualInherit_fv<Base>;
 protected:
  Base() = default;
  Base(const Base&) = default;
  Base(Base&&) = default;
  Base& operator=(const Base&) = default;
  Base& operator=(Base&&) = default;
 public:
  virtual ~Base() = default;
  template <typename T>
  int fv(int x) {
    return fake_virtual_fv<typelist<Derived>, T>(this, x);
  }
};
class Derived : public Base::Inherit {
 public:
  template <typename T>
  int fv(int x) {
    return x + 3;
  }
};
GENERATE_INSTANTIATIONS
#define GENERATE_INSTANTIATIONS (INSTANTIATION_MACRO, ...)
Value:
GENERATE_INSTANTIATIONS_DO_PRODUCT(\
      INSTANTIATION_MACRO,                                               \
      BOOST_PP_LIST_TRANSFORM(GENERATE_INSTANTIATION_TUPLES_TO_LISTS, _, \
                              BOOST_PP_VARIADIC_TO_LIST(__VA_ARGS__)))
Macro useful for generating many explicit instantiations of function or class templates.
It is often necessary to generate explicit instantiations of function or class templates. Since the total number of explicit instantiations scales as the product of the number of possible number of parameter values of each template parameter, this quickly becomes tedious. This macro allows you to easily generate hundreds of explicit instantiations.
The first argument to the macro is a macro that takes two arguments and is described below. The remaining arguments are macro-tuples, e.g. (1, 2, 3). The Cartesian product of the macro-tuples is then computed and each term is passed as a tuple as the second argument to the INSTANTIATION_MACRO. The first argument to the INSTANTIATION_MACRO is a Boost.Preprocessor internal variable so just make it _. The INSTANTIATION(_, data) macro below serves as an example. A concrete example is generating explicit instantiations of the class Index<Dim> for Dim = 0,1,2,3, which you would do as follows:
#define GET_DIM(data) BOOST_PP_TUPLE_ELEM(0, data)
#define INSTANTIATION(_, data)         \
  template class Index<GET_DIM(data)>;
GENERATE_INSTANTIATIONS(INSTANTIATION, (0, 1, 2, 3))
#undef GET_DIM
#undef INSTANTIATION
This will generate:
template class Index<0>;
template class Index<1>;
template class Index<2>;
template class Index<3>;
It is also possible to generate explicit instantiations for multiple classes or functions in a single call to GENERATE_INSTANTIATIONS. For example, the (in)equivalence operators can be generated using:
#define GET_DIM(data) BOOST_PP_TUPLE_ELEM(0, data)
#define GEN_OP(op, dim)                            \
  template bool operator op(const Index<dim>& lhs, \
                            const Index<dim>& rhs) noexcept;
#define INSTANTIATION(_, data)         \
  template class Index<GET_DIM(data)>; \
  GEN_OP(==, GET_DIM(data))            \
  GEN_OP(!=, GET_DIM(data))
GENERATE_INSTANTIATIONS(INSTANTIATION, (0, 1, 2, 3))
#undef GET_DIM
#undef GEN_OP
#undef INSTANTIATION
which will result in the instantiations:
template class Index<0>;
template bool operator==(const Index<0>& lhs, const Index<0>& rhs) noexcept;
template bool operator!=(const Index<0>& lhs, const Index<0>& rhs) noexcept;
template class Index<1>;
template bool operator==(const Index<1>& lhs, const Index<1>& rhs) noexcept;
template bool operator!=(const Index<1>& lhs, const Index<1>& rhs) noexcept;
template class Index<2>;
template bool operator==(const Index<2>& lhs, const Index<2>& rhs) noexcept;
template bool operator!=(const Index<2>& lhs, const Index<2>& rhs) noexcept;
template class Index<3>;
template bool operator==(const Index<3>& lhs, const Index<3>& rhs) noexcept;
template bool operator!=(const Index<3>& lhs, const Index<3>& rhs) noexcept;
Now let's look at generating instantiations of member function templates of class templates, which will be a common use case. In this example we generate explicit instantiations of all the member function templates of the class ScalarWave::Solutions::PlaneWave. In total, for Dim = 1,2,3 and types double and DataVector this is about 42 explicit instantiations, which would be extremely annoying to write by hand. The macro code is surprisingly simple:
#define DIM(data) BOOST_PP_TUPLE_ELEM(0, data)
#define DTYPE(data) BOOST_PP_TUPLE_ELEM(1, data)
#define INSTANTIATE(_, data)                                              \
  template Scalar<DTYPE(data)>                                            \
  ScalarWave::Solutions::PlaneWave<DIM(data)>::psi(                       \
      const tnsr::I<DTYPE(data), DIM(data)>& x, double t) const noexcept; \
  template Scalar<DTYPE(data)>                                            \
  ScalarWave::Solutions::PlaneWave<DIM(data)>::dpsi_dt(                   \
      const tnsr::I<DTYPE(data), DIM(data)>& x, double t) const noexcept;
GENERATE_INSTANTIATIONS(INSTANTIATE, (1, 2, 3), (double, DataVector))
#undef DIM
#undef DTYPE
#undef INSTANTIATE
We don't show the result from preprocessor since for all of the member functions of PlaneWave the total output is approximately 150 lines, but you can hopefully see the benefits of generating explicit instantiations using the GENERATE_INSTANTIATIONS way.
One thing that can be difficult is debugging metaprograms (be they template or macro-based). To this end we provide a make target DebugPreprocessor which prints the output of running the preprocessor on the file src/Executables/DebugPreprocessor/DebugPreprocessor.cpp . Note that the output of the GENERATE_INSTANTIATIONS macro will be on a single line, so it often proves useful to copy-paste the output into an editor and run clang-format over the code so it's easier to reason about.
Referenced by ScalarWave::Solutions::PlaneWave< Dim >::d2psi_dxdx(), and EinsteinSolutions::Minkowski< Dim >::extrinsic_curvature().
LIKELY
#define LIKELY (x) (x)
The if statement is expected to evaluate true most of the time
Referenced by CoordinateMap< SourceFrame, TargetFrame, Maps >::inv_jacobian_impl(), and CoordinateMap< SourceFrame, TargetFrame, Maps >::jacobian_impl().
SPECTRE_ALWAYS_INLINE
#define SPECTRE_ALWAYS_INLINE inline
Always inline a function. Only use this if you benchmarked the code.
Referenced by TensorExpressions::AddSub< T1, T2, ArgsList1< Args1... >, ArgsList2< Args2... >, Sign >::AddSub(), MakeWithValueImpls::MakeWithValueImpl< R, T >::apply(), CoordinateMap< SourceFrame, TargetFrame, Maps >::call_impl(), TensorExpressions::contract(), CoordinateMap< SourceFrame, TargetFrame, Maps >::CoordinateMap(), cube(), TensorExpressions::TensorContract< Index1, Index2, T, X, Symm, IndexList, ArgsList >::fill_contracting_tensor_index(), TensorExpressions::AddSub< T1, T2, ArgsList1< Args1... >, ArgsList2< Args2... >, Sign >::get(), TensorExpression< Derived, DataType, Symm, IndexList, ArgsList< Args... > >::get(), Tensor< X, Symm, IndexList< Indices... > >::get_tensor_index(), Tensor< X, Symm, IndexList< Indices... > >::index_dim(), Tensor< X, Symm, IndexList< Indices... > >::index_dims(), Tensor< X, Symm, IndexList< Indices... > >::index_types(), CoordinateMap< SourceFrame, TargetFrame, Maps >::inverse_impl(), make_array(), Variables< tmpl::list< Tags... > >::operator/(), TensorExpression< Derived, DataType, Symm, IndexList, ArgsList< Args... > >::operator~(), TensorExpressions::Product< T1, T2, ArgsList1< Args1... >, ArgsList2< Args2... > >::Product(), Tensor< X, Symm, IndexList< Indices... > >::rank(), and Tensor< X, Symm, IndexList< Indices... > >::symmetries().
SPECTRE_JUST_ALWAYS_INLINE
#define SPECTRE_JUST_ALWAYS_INLINE
Always inline a function, but do not mark it inline
Referenced by AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::get_terminate().
UNLIKELY
#define UNLIKELY (x) (x)
The if statement is expected to evaluate false most of the time
Typedef Documentation
flat_all
template<bool... Bs> using tmpl2::flat_all = typedef std::is_same<value_list<bool, Bs...>, value_list<bool, (static_cast<void>(Bs), true)...> >
A non-short-circuiting logical AND between bools 'B"".
Useful when arbitrarily large parameter packs need to be evaluated, since cpp17::conjunction and cpp17::disjunction use recursion
flat_any
template<bool... Bs> using tmpl2::flat_any = typedef std::integral_constant< bool, not std::is_same< value_list<bool, Bs...>, value_list<bool, (static_cast<void>(Bs), false)...> >::value>
A non-short-circuiting logical OR between bools 'B"".
Useful when arbitrarily large parameter packs need to be evaluated, since cpp17::conjunction and cpp17::disjunction use recursion
make_boost_variant_over
template<typename Sequence > using make_boost_variant_over = typename detail::make_boost_variant_over_impl<Sequence>::type
Create a boost::variant with all all the types inside the typelist Sequence.
Returns: boost::variant of all types inside Sequence
Requires
template<bool B> using Requires = typename Requires_detail::requires_impl< B>::template_error_type_failed_to_meet_requirements_on_template_parameters
Express requirements on the template parameters of a function or class, replaces std::enable_if_t
Replacement for std::enable_if_t and Concepts for expressing requirements on template parameters. This does not require merging of the Concepts TS (whose merit is debatable) and provides an "error message" if substitution of a template parameter failed. Specifically, the compiler error will contain "template_error_type_failed_to_meet_requirements_on_template_parameters", aiding the user of a function or class in tracking down the list of requirements on the deduced type.
For example, if a function foo is defined as:
template <typename T, Requires<tt::is_a_v<std::vector, T>> = nullptr>
std::string foo(const T& /*unused*/) {
  return "vector";
}
then calling the function with a list, foo(std::list<double>{}); results in the following compilation error from clang:
./tests/Unit/Utilities/Test_Requires.cpp:29:3: error: no matching function
   for call to 'foo'
  foo(std::list<double>{});
  ^~~
./tests/Unit/Utilities/Test_Requires.cpp:15:13: note: candidate
    template ignored: substitution failure [with T = std::__1::list<double,
    std::__1::allocator<double> >]: no type named
    'template_error_type_failed_to_meet_requirements_on_template_parameters'
    in 'Requires_detail::requires_impl<false>'
std::string foo(const T&) {
            ^
1 error generated.
Here is an example of how write function overloads using Requires or to express constraints on the template parameters:
/// [foo_definition]
template <typename T, Requires<tt::is_a_v<std::vector, T>> = nullptr>
std::string foo(const T& /*unused*/) {
  return "vector";
}
/// [foo_definition]
template <typename T, Requires<tt::is_a_v<std::list, T>> = nullptr>
std::string foo(const T& /*unused*/) {
  return "list";
}
Note
Using Requires is safer than using std::enable_if_t because the nested type alias is of type std::nullptr_t and so usage is always:
template <typename T, Requires<(bool depending on T)> = nullptr>
TaggedTupleTypelist
template<typename T > using tuples::TaggedTupleTypelist = typedef typename TaggedTuple_detail::tagged_tuple_typelist_impl<T>::type
typelist
template<typename... Ts> using typelist = tmpl::list<Ts...>
Construct a typelist of types Ts.
Function Documentation
all_but_specified_element_of()
template<size_t ElementToRemove, typename T , size_t Dim> std::array<T, Dim - 1> all_but_specified_element_of (const std::array< T, Dim > & a) inline noexcept
Construct an array from an existing array omitting one element.
References gsl::at().
at() [1/3]
template<class T , std::size_t N, typename Size > constexpr T& gsl::at (std::array< T, N > & arr, Size index)
Retrieve a entry from a container, with checks in Debug mode that the index being retrieved is valid.
References Expects.
Referenced by all_but_specified_element_of(), Actions::SendDataForFluxes< Receiver >::apply(), create_initial_element(), ScalarWave::Solutions::PlaneWave< Dim >::d2psi_dtdx(), ScalarWave::Solutions::PlaneWave< Dim >::d2psi_dxdx(), ScalarWave::Solutions::PlaneWave< Dim >::dpsi_dx(), ElementIndex< VolumeDim >::ElementIndex(), Tensor< X, Symm, IndexList< Indices... > >::get(), Tensor< X, Symm, IndexList< Indices... > >::get_vector_of_data(), ElementId< VolumeDim >::id_of_child(), ElementId< VolumeDim >::id_of_parent(), Tensor< X, Symm, IndexList< Indices... > >::index_dim(), interface_logical_coordinates(), linearize(), make_array_from_list(), Orientation< VolumeDim >::mapped(), operator*(), operator+(), GeneralIndexIterator< Container >::operator++(), operator+=(), operator-(), operator-=(), operator/(), Index< Dim >::operator[](), Tensor< X, Symm, IndexList< Indices... > >::operator[](), Orientation< VolumeDim >::Orientation(), partial_derivatives(), YlmSpherepack::second_derivative(), and Index< Dim >::slice_away().
at() [2/3]
template<class Cont , typename Size > constexpr const Cont::value_type& gsl::at (const Cont & cont, Size index)
Retrieve a entry from a container, with checks in Debug mode that the index being retrieved is valid.
References Expects.
at() [3/3]
template<class T , typename Size > constexpr const T& gsl::at (std::initializer_list< T > cont, Size index)
Retrieve a entry from a container, with checks in Debug mode that the index being retrieved is valid.
References Expects.
current_date_and_time()
std::string current_date_and_time () inline
Get the current date and time.
References std::chrono::system_clock::now(), and std::chrono::system_clock::to_time_t().
Referenced by Informer::print_exit_info(), and Informer::print_startup_info().
ddot_()
double ddot_ (const size_t & N, const double * X, const size_t & INCX, const double * Y, const size_t & INCY) inline
The dot product of two vectors.
Parameters
N the length of the vectors.
X a pointer to the first element of the first vector.
INCX the stride for the elements of the first vector.
Y a pointer to the first element of the second vector.
INCY the stride for the elements of the second vector.
Returns: the dot product of the given vectors.
Referenced by YlmSpherepack::definite_integral(), and Basis::lgl::definite_integral< 1 >().
dereference_wrapper()
template<typename T > decltype(auto) dereference_wrapper (T && t)
Returns the reference object held by a reference wrapper, if a non-reference_wrapper type is passed in then the object is returned.
Referenced by CoordinateMaps::Identity< Dim >::inv_jacobian(), CoordinateMaps::AffineMap::inv_jacobian(), CoordinateMaps::Rotation< 2 >::inv_jacobian(), CoordinateMaps::Rotation< 3 >::inv_jacobian(), CoordinateMaps::ProductOf3Maps< Map1, Map2, Map3 >::inv_jacobian(), CoordinateMaps::Identity< Dim >::jacobian(), CoordinateMaps::AffineMap::jacobian(), CoordinateMaps::Rotation< 2 >::jacobian(), CoordinateMaps::Rotation< 3 >::jacobian(), and CoordinateMaps::ProductOf3Maps< Map1, Map2, Map3 >::jacobian().
dgemm_()
template<bool UseLibXsmm = false> void dgemm_ (const char & TRANSA, const char & TRANSB, const size_t & M, const size_t & N, const size_t & K, const double & ALPHA, const double * A, const size_t & LDA, const double * B, const size_t & LDB, const double & BETA, double * C, const size_t & LDC) inline
Perform a matrix-matrix multiplication.
Perform the matrix-matrix multiplication
\[ C = \alpha \mathrm{op}(A) \mathrm{op}(B) + \beta \mathrm{op}(C) \]
where \(\mathrm{op}(A)\) represents either \(A\) or \(A^{T}\) (transpose of \(A\)).
LIBXSMM, which is much faster than BLAS for small matrices, can be called instead of BLAS by passing the template parameter true.
Parameters
TRANSA either 'N', 'T' or 'C', transposition of matrix A
TRANSB either 'N', 'T' or 'C', transposition of matrix B
M Number of rows in \(\mathrm{op}(A)\)
N Number of columns in \(\mathrm{op}(B)\) and \(\mathrm{op}(C)\)
K Number of columns in \(\mathrm{op}(A)\)
ALPHA specifies \(\alpha\)
A Matrix \(A\)
LDA Specifies first dimension of \(\mathrm{op}(A)\)
B Matrix \(B\)
LDB Specifies first dimension of \(\mathrm{op}(B)\)
BETA specifies \(\beta\)
C Matrix \(C\)
LDC Specifies first dimension of \(\mathrm{op}(C)\)
Template Parameters
UseLibXsmm if true then use LIBXSMM
References ASSERT.
Referenced by Basis::lgl::linear_filter_matrix(), and partial_derivatives().
dgemm_< true >()
template<> void dgemm_< true > (const char & TRANSA, const char & TRANSB, const size_t & M, const size_t & N, const size_t & K, const double & ALPHA, const double * A, const size_t & LDA, const double * B, const size_t & LDB, const double & BETA, double * C, const size_t & LDC) inline
Perform a matrix-matrix multiplication.
Perform the matrix-matrix multiplication
\[ C = \alpha \mathrm{op}(A) \mathrm{op}(B) + \beta \mathrm{op}(C) \]
where \(\mathrm{op}(A)\) represents either \(A\) or \(A^{T}\) (transpose of \(A\)).
LIBXSMM, which is much faster than BLAS for small matrices, can be called instead of BLAS by passing the template parameter true.
Parameters
TRANSA either 'N', 'T' or 'C', transposition of matrix A
TRANSB either 'N', 'T' or 'C', transposition of matrix B
M Number of rows in \(\mathrm{op}(A)\)
N Number of columns in \(\mathrm{op}(B)\) and \(\mathrm{op}(C)\)
K Number of columns in \(\mathrm{op}(A)\)
ALPHA specifies \(\alpha\)
A Matrix \(A\)
LDA Specifies first dimension of \(\mathrm{op}(A)\)
B Matrix \(B\)
LDB Specifies first dimension of \(\mathrm{op}(B)\)
BETA specifies \(\beta\)
C Matrix \(C\)
LDC Specifies first dimension of \(\mathrm{op}(C)\)
Template Parameters
UseLibXsmm if true then use LIBXSMM
References ASSERT, and gsl::narrow_cast().
dgemv_()
void dgemv_ (const char & TRANS, const size_t & M, const size_t & N, const double & ALPHA, const double * A, const size_t & LDA, const double * X, const size_t & INCX, const double & BETA, double * Y, const size_t & INCY) inline
Perform a matrix-vector multiplication.
\[ y = \alpha \mathrm{op}(A) x + \beta y \]
where \(\mathrm{op}(A)\) represents either \(A\) or \(A^{T}\) (transpose of \(A\)).
Parameters
TRANS either 'N', 'T' or 'C', transposition of matrix A
M Number of rows in \(\mathrm{op}(A)\)
N Number of columns in \(\mathrm{op}(A)\)
ALPHA specifies \(\alpha\)
A Matrix \(A\)
LDA Specifies first dimension of \(\mathrm{op}(A)\)
X Vector \(x\)
INCX Specifies the increment for the elements of \(x\)
BETA Specifies \(\beta\)
Y Vector \(y\)
INCY Specifies the increment for the elements of \(y\)
References ASSERT.
Referenced by linearize().
formatted_string()
template<typename... Args> std::string formatted_string (const std::string & fmt, Args... args)
Format a string like printf.
Given a formatting string and arguments this returns the corresponding string. Similar to printf but using std::strings.
get() [1/4]
template<class Tag , class... Tags> constexpr const Tag::type & tuples::get (const TaggedTuple< Tags... > & t) inline noexcept
Retrieve the element of Tag in the TaggedTuple.
References Parallel::value.
Referenced by Parallel::get_parallel_component(), and Parallel::Main< Metavariables >::Main().
get() [2/4]
template<class Tag , class... Tags> constexpr Tag::type & tuples::get (TaggedTuple< Tags... > & t) inline noexcept
Retrieve the element of Tag in the TaggedTuple.
References Parallel::value.
get() [3/4]
template<class Tag , class... Tags> constexpr const Tag::type && tuples::get (const TaggedTuple< Tags... > && t) inline noexcept
Retrieve the element of Tag in the TaggedTuple.
References Parallel::value.
get() [4/4]
template<class Tag , class... Tags> constexpr Tag::type && tuples::get (TaggedTuple< Tags... > && t) inline noexcept
Retrieve the element of Tag in the TaggedTuple.
References db::apply(), TUPLES_LIB_CONSTEXPR_CXX_14, and Parallel::value.
info_from_build()
std::string info_from_build ()
Information about the version, date, host, git commit, and link time.
The information returned by this function is invaluable for identifying the version of the code used in a simulation, as well as which host, the date the code was compiled, and the time of linkage.
References spectre_version().
Referenced by Informer::print_startup_info().
keys_of() [1/2]
template<typename K , typename V , typename H > std::string keys_of (const std::unordered_map< K, V, H > & m) inline
Construct a string containing the keys of a std::unordered_map.
keys_of() [2/2]
template<typename K , typename V , typename C > std::string keys_of (const std::map< K, V, C > & m) inline
Construct a string containing the keys of a std::map.
magnitude() [1/4]
template<typename T > T magnitude (const std::array< T, 1 > & a) inline noexcept
Euclidean magnitude of the elements of the array.
Details
If T is a container the magnitude is computed separately for each element of the container.
Requires: If T is a container, T must have following mathematical operators: abs(), sqrt(), and element-wise addition and multiplication. In addition, each T in the array must have the same size.
magnitude() [2/4]
template<> double magnitude (const std::array< double, 1 > & a) inline noexcept
Euclidean magnitude of the elements of the array.
Details
If T is a container the magnitude is computed separately for each element of the container.
Requires: If T is a container, T must have following mathematical operators: abs(), sqrt(), and element-wise addition and multiplication. In addition, each T in the array must have the same size.
magnitude() [3/4]
template<typename T > T magnitude (const std::array< T, 2 > & a) inline noexcept
Euclidean magnitude of the elements of the array.
Details
If T is a container the magnitude is computed separately for each element of the container.
Requires: If T is a container, T must have following mathematical operators: abs(), sqrt(), and element-wise addition and multiplication. In addition, each T in the array must have the same size.
magnitude() [4/4]
template<typename T > T magnitude (const std::array< T, 3 > & a) inline noexcept
Euclidean magnitude of the elements of the array.
Details
If T is a container the magnitude is computed separately for each element of the container.
Requires: If T is a container, T must have following mathematical operators: abs(), sqrt(), and element-wise addition and multiplication. In addition, each T in the array must have the same size.
make_array() [1/3]
template<std::size_t size, typename T > constexpr std::array<std::decay_t<T>, size> make_array (T && value) noexcept
Helper class to initialize a std::array.
Template Parameters
size the length of the array
References make_array(), SPECTRE_ALWAYS_INLINE, and Parallel::value.
make_array() [2/3]
template<typename T , typename... V, Requires<(sizeof...(V) > 0> constexpr std::array<typename std::decay_t<T>, sizeof...(V) + 1> make_array (T && t, V &&... values) noexcept
Helper function to initialize a std::array with varying number of arguments.
References tmpl2::flat_all_v, and cpp17::is_same_v.
make_array() [3/3]
template<typename T , size_t size, typename Seq > constexpr std::array<T, size> make_array (Seq && seq) noexcept
Create an std::array<T, size> from the first size values of seq
Requires: Seq has a begin function
Template Parameters
T the type held by the array
size the size of the created array
References CASSERT.
make_deferred()
template<typename Fp , typename... Args> Deferred<Rt1> make_deferred (Fp f, Args &&... args)
Create a deferred function call object.
If creating a Deferred with a function object the call operator of the function object must be marked const currently. Since the function object will only be evaluated once there currently seems to be no reason to allow mutating call operators.
Example
The examples below use the following functions:
struct func {
  double operator()() const { return 8.2; }
};
double dummy() { return 6.7; }
struct func2 {
  double operator()(const double& t) const { return t; }
};
double lazy_function(const double t) { return 10.0 * t; }
To create a Deferred using a function object use:
  auto def = make_deferred(func{});
  CHECK(8.2 == def.get());
or using a regular function:
  auto def2 = make_deferred(dummy);
  CHECK(6.7 == def2.get());
It is also possible to pass Deferred objects to a deferred function call:
  auto def2 = make_deferred(func2{}, 6.82);
  auto def3 = make_deferred(lazy_function, def2);
  CHECK(68.2 == def3.get());
  CHECK(6.82 == def2.get());
in which case the first function will be evaluated just before the second function is evaluated.
Returns: Deferred object that will lazily evaluate the function
Referenced by Deferred< Rt >::mutate().
make_overloader()
template<class... Fs> OVERLOADER_CONSTEXPR Overloader<Fs...> make_overloader (Fs... fs)
Create Overloader<Fs...>, see Overloader for details.
Referenced by apply_visitor_helper(), create_from_yaml< T >::create(), Parallel::get(), AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::get_terminate(), Parallel::Main< Metavariables >::Main(), and tuples::operator<<().
narrow()
template<class T , class U > T gsl::narrow (U u)
A checked version of narrow_cast() that ERRORs if the cast changed the value.
References ERROR, gsl::narrow_cast(), and Parallel::value.
narrow_cast()
template<class T , class U > constexpr T gsl::narrow_cast (U && u) noexcept
Cast u to a type T where the cast may result in narrowing.
Referenced by dgemm_< true >(), and gsl::narrow().
number_of_digits()
template<typename T > T number_of_digits (const T number)
Returns the number of digits in an integer number.
References tt::is_integer_v.
operator"" _st()
constexpr size_t operator"" _st (const unsigned long long n) inline
Defines the _st size_t suffix.
operator<<() [1/12]
template<typename T > std::ostream& operator<< (std::ostream & os, const std::list< T > & v) inline
Output the items of a std::list.
operator<<() [2/12]
template<typename T > std::ostream& operator<< (std::ostream & os, const std::vector< T > & v) inline
Output the items of a std::vector.
operator<<() [3/12]
template<typename T > std::ostream& operator<< (std::ostream & os, const std::deque< T > & v) inline
Output the items of a std::deque.
operator<<() [4/12]
template<typename T , size_t N> std::ostream& operator<< (std::ostream & os, const std::array< T, N > & a) inline
Output the items of a std::array.
operator<<() [5/12]
template<typename... Args> std::ostream& operator<< (std::ostream & os, const std::tuple< Args... > & t) inline
Stream operator for tuples.
operator<<() [6/12]
template<typename K , typename V , typename H > std::ostream& operator<< (std::ostream & os, const std::unordered_map< K, V, H > & m) inline
Output all the key, value pairs of a std::unordered_map.
operator<<() [7/12]
template<typename K , typename V , typename C > std::ostream& operator<< (std::ostream & os, const std::map< K, V, C > & m) inline
Output all the key, value pairs of a std::map.
operator<<() [8/12]
template<typename T > std::ostream& operator<< (std::ostream & os, const std::unordered_set< T > & v) inline
Output the items of a std::unordered_set.
operator<<() [9/12]
template<typename T , typename C > std::ostream& operator<< (std::ostream & os, const std::set< T, C > & v) inline
Output the items of a std::set.
operator<<() [10/12]
template<typename T , Requires< tt::is_streamable< std::ostream, T >::value > > std::ostream& operator<< (std::ostream & os, const std::unique_ptr< T > & t) inline
Stream operator for std::unique_ptr.
References Parallel::value.
operator<<() [11/12]
template<typename T , Requires< tt::is_streamable< std::ostream, T >::value > > std::ostream& operator<< (std::ostream & os, const std::shared_ptr< T > & t) inline
Stream operator for std::shared_ptr.
operator<<() [12/12]
template<typename T , typename U > std::ostream& operator<< (std::ostream & os, const std::pair< T, U > & t) inline
Stream operator for std::pair.
simplest_fraction_in_interval()
template<typename Fraction , typename T1 , typename T2 > Fraction simplest_fraction_in_interval (const T1 & end1, const T2 & end2) noexcept
Find the fraction in the supplied interval with the smallest denominator.
The endpoints are considered to be in the interval. The order of the arguments is not significant. The answer is unique as long as the interval has length less than 1; for longer intervals, an integer in the range will be returned.
References ContinuedFractionSummer< Fraction >::insert(), and ContinuedFractionSummer< Fraction >::value().
spectre_major_version()
int spectre_major_version ()
Returns major version.
spectre_minor_version()
int spectre_minor_version ()
Returns minor version.
spectre_patch_version()
int spectre_patch_version ()
Returns patch version.
spectre_version()
std::string spectre_version ()
Retrieve a string containing the current version of SpECTRE.
Referenced by info_from_build().
swallow()
template<typename... Ts> constexpr void swallow (Ts && ...) noexcept
Allows zero-cost unordered expansion of a parameter.
Details
Expands a parameter pack, typically useful for runtime evaluation via a Callable such as a lambda, function, or function object. For example, an unordered transform of a std::tuple can be implemented as:
namespace {
template <typename... Elements, size_t... Is>
void transform(const std::tuple<Elements...>& tupull,
               std::tuple<Elements...>& out_tupull,
               std::index_sequence<Is...> /*meta*/) {
  const auto func = [](const auto& in, auto& out) {
    out = in * static_cast<decltype(in)>(2);
    return 0;
  };
  swallow(func(std::get<Is>(tupull), std::get<Is>(out_tupull))...);
}
}  // namespace
SPECTRE_TEST_CASE("Unit.Utilities.swallow", "[Utilities][Unit]") {
  std::tuple<int, double, float> my_tupull = std::make_tuple(3, 2.7, 8.2);
  std::tuple<int, double, float> my_tupull_output;
  transform(my_tupull, my_tupull_output, std::make_index_sequence<3>{});
  CHECK(std::get<0>(my_tupull_output) == 6);
  CHECK(std::get<1>(my_tupull_output) == 5.4);
  CHECK(std::get<2>(my_tupull_output) == 16.4f);
}
See also
tuple_fold tuple_counted_fold tuple_transform std::tuple
Referenced by tuples::TaggedTuple< InboxTagsPack... >::operator=(), and tuples::TaggedTuple< InboxTagsPack... >::swap().
tuple_counted_fold()
template<bool ReverseIteration = false, typename... Elements, typename N_aryOp , typename... Args> constexpr void tuple_counted_fold (const std::tuple< Elements... > & tuple, N_aryOp && op, Args &&... args) inline noexcept
Perform a fold over a std::tuple.
Details
Iterates over the elements in a std::tuple tuple from left to right (left fold) calling op(element, args...) on each element in tuple. A right fold can be done by explicitly setting the first template parameter to true. Folds are easily implemented using tuple_fold by updating one of the args... at each iteration. If you need the index of the current element you can use the tuple_counted_fold variant. tuple_counted_fold passes the current index as the second argument to the Callable op. That is, op(element, index, args...).
Example
The sum of a std::tuple of Arithmetics can be computed in several ways. First, you can use a lambda:
    const auto my_tupull = std::make_tuple(2, 7, -3.8, 20.9);
    double sum_value = 0.0;
    tuple_fold(my_tupull,
               [](const auto& element, double& state) { state += element; },
               sum_value);
    CHECK(sum_value == approx(26.1));
You'll notice that state is taken by reference and mutated.
You can do the same thing with a struct defined as
template <typename T>
struct tuple_fold_plus {
  T value = 0.0;
  template <typename S>
  void operator()(const S& element) {
    value += element;
  }
};
and then using an instance of the struct
    const auto my_tupull = std::make_tuple(2, 7, -3.8, 20.9);
    tuple_fold_plus<double> sum_value{};
    tuple_fold(my_tupull, sum_value);
    CHECK(sum_value.value == approx(26.1));
Note
You are not able to pass a function pointer to tuple_fold or tuple_counted_fold because you cannot pass a pointer to a function template, only a function.
See also
swallow tuple_transform tuple_fold tuple_counted_fold std::tuple
tuple_fold()
template<bool ReverseIteration = false, typename... Elements, typename N_aryOp , typename... Args> constexpr void tuple_fold (const std::tuple< Elements... > & tuple, N_aryOp && op, Args &&... args) inline noexcept
Perform a fold over a std::tuple.
Details
Iterates over the elements in a std::tuple tuple from left to right (left fold) calling op(element, args...) on each element in tuple. A right fold can be done by explicitly setting the first template parameter to true. Folds are easily implemented using tuple_fold by updating one of the args... at each iteration. If you need the index of the current element you can use the tuple_counted_fold variant. tuple_counted_fold passes the current index as the second argument to the Callable op. That is, op(element, index, args...).
Example
The sum of a std::tuple of Arithmetics can be computed in several ways. First, you can use a lambda:
    const auto my_tupull = std::make_tuple(2, 7, -3.8, 20.9);
    double sum_value = 0.0;
    tuple_fold(my_tupull,
               [](const auto& element, double& state) { state += element; },
               sum_value);
    CHECK(sum_value == approx(26.1));
You'll notice that state is taken by reference and mutated.
You can do the same thing with a struct defined as
template <typename T>
struct tuple_fold_plus {
  T value = 0.0;
  template <typename S>
  void operator()(const S& element) {
    value += element;
  }
};
and then using an instance of the struct
    const auto my_tupull = std::make_tuple(2, 7, -3.8, 20.9);
    tuple_fold_plus<double> sum_value{};
    tuple_fold(my_tupull, sum_value);
    CHECK(sum_value.value == approx(26.1));
Note
You are not able to pass a function pointer to tuple_fold or tuple_counted_fold because you cannot pass a pointer to a function template, only a function.
See also
swallow tuple_transform tuple_fold tuple_counted_fold std::tuple
Referenced by CoordinateMap< SourceFrame, TargetFrame, Maps >::call_impl().
tuple_transform()
template<bool ReverseIteration = false, typename... Elements, typename N_aryOp , typename... Args> constexpr void tuple_transform (const std::tuple< Elements... > & tuple, N_aryOp && op, Args &&... args) inline noexcept
Perform a transform over a std::tuple.
Details
Iterates over the elements in a std::tuple tuple from left to right calling op.operator()(element, index, args...) on each element in tuple. A right-to-left transform can be done by explicitly setting the first template parameter to true. The second argument of the invokable will be a deduced std::integral_constant<size_t, value>, from which the current index can be extracted by using decltype(index)::value. For a function object the decltype(index) can be replaced by the deduced type of index. For example,
struct negate {
  template <typename T, typename Index, typename S>
  void operator()(const T& element, Index /*index*/,
                  S& second_tuple_element) const noexcept {
    std::get<Index::value>(second_tuple_element) = -element;
  }
};
Using tuple_transform with a generic lambda goes as follows,
  const auto my_tupull = std::make_tuple(2, 7, -3.8, 20.9);
  std::decay_t<decltype(my_tupull)> out_tupull;
  tuple_transform(my_tupull,
                  [](const auto& element, auto index, auto& out_tuple) {
                    constexpr size_t index_v = decltype(index)::value;
                    std::get<index_v>(out_tuple) = -element;
                  },
                  out_tupull);
  CHECK(std::get<0>(out_tupull) == -2);
  CHECK(std::get<1>(out_tupull) == -7);
  CHECK(std::get<2>(out_tupull) == 3.8);
  CHECK(std::get<3>(out_tupull) == -20.9);
See also
swallow tuple_fold tuple_counted_fold std::tuple
Referenced by CoordinateMap< SourceFrame, TargetFrame, Maps >::inv_jacobian_impl(), and CoordinateMap< SourceFrame, TargetFrame, Maps >::jacobian_impl().
Variable Documentation
flat_all_v
template<bool... Bs> constexpr bool tmpl2::flat_all_v = flat_all<Bs...>::value
A non-short-circuiting logical AND between bools 'B"".
Useful when arbitrarily large parameter packs need to be evaluated, since cpp17::conjunction and cpp17::disjunction use recursion
Referenced by make_array().
flat_any_v
template<bool... Bs> constexpr bool tmpl2::flat_any_v = flat_any<Bs...>::value
A non-short-circuiting logical OR between bools 'B"".
Useful when arbitrarily large parameter packs need to be evaluated, since cpp17::conjunction and cpp17::disjunction use recursion