SpECTRE: Computational Domain
Computational Domain
The building blocks used to describe the computational domain.
Classes
class Block< VolumeDim, TargetFrame >
A Block<VolumeDim> is a region of a VolumeDim-dimensional computational domain that defines the root node of a tree which is used to construct the Elements that cover a region of the computational domain.
class BlockNeighbor< VolumeDim >
Information about the neighbor of a Block in a particular direction.
class Direction< VolumeDim >
A particular Side along a particular coordinate Axis.
class Domain< VolumeDim, TargetFrame >
A wrapper around a vector of Blocks that represent the computational domain.
struct PairOfFaces
Each member in PairOfFaces holds the global corner ids of a block face. PairOfFaces is used in setting up periodic boundary conditions by identifying the two faces with each other.
class Element< VolumeDim >
A spectral element with knowledge of its neighbors.
class ElementId< VolumeDim >
An ElementId uniquely labels a Element. It is constructed from the BlockId of the Block to which the Element belongs and the VolumeDim SegementIds that label the segments of the Block that the Element covers.
class Neighbors< VolumeDim >
Information about the neighbors of an Element in a particular direction.
class SegmentId
A SegmentId labels a segment of the interval [-1,1]. A SegmentId is used to (partially) identify an Element. The segment is the interval [-1 + 2*(N/D), -1 + 2*(N+1)/D] where N = index_ and D = 2 ^ refinement_level_.
struct Tags::Element< VolumeDim >
The Element associated with the DataBox.
struct Tags::Extents< VolumeDim >
The extents of DataVectors in the DataBox.
struct Tags::ElementMap< VolumeDim >
The coordinate map from logical to grid coordinate.
struct Tags::UnnormalizedGridNormal< VolumeDim >
The unnormalized grid normal one form on each side.
Enumerations
enum Side { Side::Lower, Side::Upper }
A label for the side of a manifold.
Functions
template<typename SourceFrame , typename TargetFrame , typename... Maps>
constexpr CoordinateMap< SourceFrame, TargetFrame, std::decay_t< Maps >... > make_coordinate_map (Maps &&... maps)
Creates a CoordinateMap of maps...
template<typename SourceFrame , typename TargetFrame , typename... Maps>
std::unique_ptr< CoordinateMapBase< SourceFrame, TargetFrame, CoordinateMap< SourceFrame, TargetFrame, std::decay_t< Maps >... >::dim > > make_coordinate_map_base (Maps &&... maps) noexcept
Creates a std::unique_ptr<CoordinateMapBase> of maps...
template<size_t VolumeDim, typename TargetFrame >
Element< VolumeDim > create_initial_element (const ElementId< VolumeDim > &element_id, const Block< VolumeDim, TargetFrame > &block) noexcept
Creates an initial element of a Block.
template<size_t VolumeDim>
void set_internal_boundaries (const std::vector< std::array< size_t, two_to_the(VolumeDim)>> &corners_of_all_blocks, gsl::not_null< std::vector< std::unordered_map< Direction< VolumeDim >, BlockNeighbor< VolumeDim >>> *> neighbors_of_all_blocks)
Sets up the BlockNeighbors using the corner numbering scheme to deduce the correct neighbors and orientations. Does not set up periodic boundary conditions.
template<size_t VolumeDim>
void set_periodic_boundaries (const std::vector< PairOfFaces > &identifications, const std::vector< std::array< size_t, two_to_the(VolumeDim)>> &corners_of_all_blocks, gsl::not_null< std::vector< std::unordered_map< Direction< VolumeDim >, BlockNeighbor< VolumeDim >>> *> neighbors_of_all_blocks)
Sets up additional BlockNeighbors corresponding to any periodic boundary condtions provided by the user. These are stored in identifications.
template<size_t VolumeDim>
tnsr::i< DataVector, VolumeDim, Frame::Grid > unnormalized_grid_normal (const Index< VolumeDim - 1 > &interface_extents, const CoordinateMapBase< Frame::Logical, Frame::Grid, VolumeDim > &map, const Direction< VolumeDim > &direction) noexcept
Compute the outward grid normal on a face of an Element.
template<size_t VolumeDim>
std::vector< ElementId< VolumeDim > > initial_element_ids (const std::vector< std::array< size_t, VolumeDim >> &initial_refinement_levels) noexcept
Create the ElementIds of the initial computational domain.
template<size_t VolumeDim>
tnsr::I< DataVector, VolumeDim, Frame::Logical > logical_coordinates (const Index< VolumeDim > &extents)
Compute the Legendre-Gauss-Lobatto coordinates in an Element.
template<size_t VolumeDim>
tnsr::I< DataVector, VolumeDim, Frame::Logical > interface_logical_coordinates (const Index< VolumeDim - 1 > &extents, const Direction< VolumeDim > &direction)
Compute the logical coordinates on a face of an Element.
Detailed Description
The building blocks used to describe the computational domain.
Description
The VolumeDim-dimensional computational Domain is constructed from a set of non-overlapping Blocks. Each Block is a distorted VolumeDim-dimensional hyperrcube Each codimension-1 boundary of a Block is either part of the external boundary of the computational domain, or is identical to a boundary of one other Block. Each Block is subdivided into one or more Elements that may be changed dynamically if AMR is enabled.
Enumeration Type Documentation
Side
enum Side strong
A label for the side of a manifold.
Lower and Upper are with respect to the logical coordinate whose axis is normal to the side, i.e. beyond the Upper (Lower) side, the logical coordinate is increasing (decreasing).
Enumerator
Lower
Upper
Function Documentation
create_initial_element()
template<size_t VolumeDim, typename TargetFrame > Element<VolumeDim> create_initial_element (const ElementId< VolumeDim > & element_id, const Block< VolumeDim, TargetFrame > & block) noexcept
Creates an initial element of a Block.
References gsl::at().
initial_element_ids()
template<size_t VolumeDim> std::vector<ElementId<VolumeDim> > initial_element_ids (const std::vector< std::array< size_t, VolumeDim >> & initial_refinement_levels) noexcept
Create the ElementIds of the initial computational domain.
interface_logical_coordinates()
template<size_t VolumeDim> tnsr::I<DataVector, VolumeDim, Frame::Logical> interface_logical_coordinates (const Index< VolumeDim - 1 > & extents, const Direction< VolumeDim > & direction)
Compute the logical coordinates on a face of an Element.
Returns: logical-frame vector holding coordinates
Example
  const Index<2> extents_3d_zbdry(Index<2>(5, 3));
  const auto x_3d_lb_zeta = map_3d(interface_logical_coordinates(
      extents_3d_zbdry, Direction<3>::lower_zeta()));
References gsl::at(), Basis::lgl::collocation_points(), Direction< VolumeDim >::dimension(), interface_logical_coordinates(), logical_coordinates(), Lower, Index< Dim >::product(), and Direction< VolumeDim >::side().
Referenced by interface_logical_coordinates(), and unnormalized_grid_normal().
logical_coordinates()
template<size_t VolumeDim> tnsr::I<DataVector, VolumeDim, Frame::Logical> logical_coordinates (const Index< VolumeDim > & extents)
Compute the Legendre-Gauss-Lobatto coordinates in an Element.
Returns: logical-frame vector holding coordinates
Example
  const Index<3> extents_3d(Index<3>(5, 3, 2));
  const CoordinateMaps::AffineMap x_map{-1.0, 1.0, -3.0, 7.0};
  const CoordinateMaps::AffineMap y_map{-1.0, 1.0, -13.0, 47.0};
  const CoordinateMaps::AffineMap z_map{-1.0, 1.0, -32.0, 74.0};
  const auto map_3d = make_coordinate_map<Frame::Logical, Frame::Grid>(
      AffineMap3d{x_map, y_map, z_map});
  const auto x_3d = map_3d(logical_coordinates(extents_3d));
References Basis::lgl::collocation_points(), and Index< Dim >::product().
Referenced by CkRegisterMainModule(), and interface_logical_coordinates().
make_coordinate_map()
template<typename SourceFrame , typename TargetFrame , typename... Maps> constexpr CoordinateMap<SourceFrame, TargetFrame, std::decay_t<Maps>...> make_coordinate_map (Maps &&... maps)
Creates a CoordinateMap of maps...
References CoordinateMap< SourceFrame, TargetFrame, Maps >::dim.
make_coordinate_map_base()
template<typename SourceFrame , typename TargetFrame , typename... Maps> std::unique_ptr<CoordinateMapBase< SourceFrame, TargetFrame, CoordinateMap<SourceFrame, TargetFrame, std::decay_t<Maps>...>::dim> > make_coordinate_map_base (Maps &&... maps) noexcept
Creates a std::unique_ptr<CoordinateMapBase> of maps...
set_internal_boundaries()
template<size_t VolumeDim> void set_internal_boundaries (const std::vector< std::array< size_t, two_to_the(VolumeDim)>> & corners_of_all_blocks, gsl::not_null< std::vector< std::unordered_map< Direction< VolumeDim >, BlockNeighbor< VolumeDim >>> *> neighbors_of_all_blocks)
Sets up the BlockNeighbors using the corner numbering scheme to deduce the correct neighbors and orientations. Does not set up periodic boundary conditions.
References two_to_the().
Referenced by set_periodic_boundaries().
set_periodic_boundaries()
template<size_t VolumeDim> void set_periodic_boundaries (const std::vector< PairOfFaces > & identifications, const std::vector< std::array< size_t, two_to_the(VolumeDim)>> & corners_of_all_blocks, gsl::not_null< std::vector< std::unordered_map< Direction< VolumeDim >, BlockNeighbor< VolumeDim >>> *> neighbors_of_all_blocks)
Sets up additional BlockNeighbors corresponding to any periodic boundary condtions provided by the user. These are stored in identifications.
References ASSERT, set_internal_boundaries(), and set_periodic_boundaries().
Referenced by set_periodic_boundaries().
unnormalized_grid_normal()
template<size_t VolumeDim> tnsr::i<DataVector, VolumeDim, Frame::Grid> unnormalized_grid_normal (const Index< VolumeDim - 1 > & interface_extents, const CoordinateMapBase< Frame::Logical, Frame::Grid, VolumeDim > & map, const Direction< VolumeDim > & direction) noexcept
Compute the outward grid normal on a face of an Element.
Returns: outward grid-frame one-form holding the normal
Details
Computes the grid-frame normal by taking the logical-frame unit one-form in the given Direction and mapping it to the grid frame with the given map.
Example
  const Index<0> extents_0d;
  const auto map_1d = make_coordinate_map<Frame::Logical, Frame::Grid>(
      CoordinateMaps::AffineMap(-1.0, 1.0, -3.0, 7.0));
  const auto normal_1d_lower =
      unnormalized_grid_normal(extents_0d, map_1d, Direction<1>::lower_xi());
References interface_logical_coordinates().