SpECTRE: src/Numerical/Interpolation/LagrangePolynomial.hpp File Reference
LagrangePolynomial.hpp File Reference
Defines functions lagrange_polynomial.
#include <iterator>
#include "ErrorHandling/Assert.hpp"
Functions
template<typename Iterator >
double lagrange_polynomial (const Iterator &index_point, double x, const Iterator &control_points_begin, const Iterator &control_points_end)
Evaluate the jth Lagrange interpolating polynomial with the given control points where j is the index of index_point.
template<typename Iterator >
double lagrange_polynomial (size_t j, double x, const Iterator &control_points_begin, const Iterator &control_points_end)
Evaluate the jth (zero-indexed) Lagrange interpolating polynomial with the given control points.
Detailed Description
Defines functions lagrange_polynomial.
Function Documentation
lagrange_polynomial() [1/2]
template<typename Iterator > double lagrange_polynomial (const Iterator & index_point, double x, const Iterator & control_points_begin, const Iterator & control_points_end)
Evaluate the jth Lagrange interpolating polynomial with the given control points where j is the index of index_point.
References ASSERT.
Referenced by TimeSteppers::AdamsBashforthN::compute_boundary_delta(), and lagrange_polynomial().
lagrange_polynomial() [2/2]
template<typename Iterator > double lagrange_polynomial (size_t j, double x, const Iterator & control_points_begin, const Iterator & control_points_end)
Evaluate the jth (zero-indexed) Lagrange interpolating polynomial with the given control points.
References ASSERT, and lagrange_polynomial().