SpECTRE: src/Utilities/MakeVector.hpp File Reference
MakeVector.hpp File Reference
#include <vector>
#include "Utilities/TMPL.hpp"
#include "Utilities/TypeTraits.hpp"
Functions
template<class ValueType = void, class Arg1 , class... Args>
auto make_vector (Arg1 &&arg_1, Args &&... remaining_args)
Constructs a std::vector containing arguments passed in.
template<class T >
std::vector< T > make_vector ()
Function Documentation
make_vector() [1/2]
template<class ValueType = void, class Arg1 , class... Args> auto make_vector (Arg1 && arg_1, Args &&... remaining_args)
Constructs a std::vector containing arguments passed in.
This is useful as it allows in-place construction of a vector of non-copyable objects.
Example
  auto vector = make_vector(3.2, 4.3, 5.4, 6.5, 7.8);
  CHECK(vector == (std::vector<double>{{3.2, 4.3, 5.4, 6.5, 7.8}}));
  auto vector_non_copyable = make_vector(NonCopyable{}, NonCopyable{});
  CHECK(vector_non_copyable.size() == 2);
  auto vector_empty = make_vector<int>();
  CHECK(vector_empty.empty());
  auto vector_size_one = make_vector(3);
  CHECK(vector_size_one == std::vector<int>{3});
  auto vector_explicit_type = make_vector<double>(1, 2, 3);
  CHECK(vector_explicit_type == (std::vector<double>{1.,2.,3.}));
Referenced by DomainCreators::Interval::create_domain(), DomainCreators::Rectangle::create_domain(), and DomainCreators::Brick::create_domain().
make_vector() [2/2]
template<class T > std::vector<T> make_vector ()