SpECTRE: h5 Namespace Reference
h5 Namespace Reference
HDF5
Contains functions and classes for manipulating HDF5 files.
Classes
class Dat
Represents a multicolumn dat file inside an HDF5 file.
class H5File
Opens an HDF5 file for access and allows manipulation of data.
class Header
Writes header info about the build, git commit, branch, etc.
class Object
Abstract base class representing an object in an HDF5 file.
class Version
Used to store the version of the file.
Enumerations
enum AccessType { AccessType::ReadWrite, AccessType::ReadOnly }
Set the access type to the H5File.
Functions
void write_time (hid_t group_id, double time)
Write a "Time" attribute to the group.
template<size_t Dim>
void write_data (hid_t group_id, const DataVector &data, const Index< Dim > &extents, const std::string &name="scalar")
Write a DataVector named name to the group group_id
template<size_t Dim>
void write_extents (hid_t group_id, const Index< Dim > &extents, const std::string &name="Extents")
Write the extents as an attribute named name to the group group_id.
void write_connectivity (hid_t group_id, const std::vector< int > &connectivity)
Write the connectivity into the group in the H5 file.
std::vector< std::string > get_group_names (hid_t file_id, const std::string &group_name)
Get the names of all the groups in a group.
std::vector< std::string > get_attribute_names (hid_t file_id, const std::string &group_name)
Get the names of all the attributes in a group.
bool contains_attribute (hid_t file_id, const std::string &group_name, const std::string &attribute_name)
Check if an attribute is in a group.
double get_time (hid_t file_id, const std::string &group_name, const std::string &attr_name="Time")
Get the "Time" attribute from a group.
DataVector read_data (hid_t group_id, const std::string &dataset_name)
Read a DataVector from a dataset in a group.
template<size_t Dim>
Index< Dim > read_extents (hid_t group_id, const std::string &extents_name="Extents")
Read the HDF5 attribute representing extents from a group.
template void write_data< 1 > (const hid_t group_id, const DataVector &data, const Index< 1 > &extents, const std::string &name)
template void write_data< 2 > (const hid_t group_id, const DataVector &data, const Index< 2 > &extents, const std::string &name)
template void write_data< 3 > (const hid_t group_id, const DataVector &data, const Index< 3 > &extents, const std::string &name)
template void write_extents< 1 > (const hid_t group_id, const Index< 1 > &extents, const std::string &name)
template void write_extents< 2 > (const hid_t group_id, const Index< 2 > &extents, const std::string &name)
template void write_extents< 3 > (const hid_t group_id, const Index< 3 > &extents, const std::string &name)
template Index< 1 > read_extents< 1 > (const hid_t group_id, const std::string &extents_name)
template Index< 2 > read_extents< 2 > (const hid_t group_id, const std::string &extents_name)
template Index< 3 > read_extents< 3 > (const hid_t group_id, const std::string &extents_name)
template<typename T >
hid_t h5_type ()
Returns the HDF5 datatype for the corresponding type T
Detailed Description
Contains functions and classes for manipulating HDF5 files.
Wraps many underlying C H5 routines making them easier to use and easier to manipulate H5 files.
Function Documentation
read_extents< 1 >()
template Index<1> h5::read_extents< 1 > (const hid_t group_id, const std::string & extents_name)
Referenced by read_extents().
read_extents< 2 >()
template Index<2> h5::read_extents< 2 > (const hid_t group_id, const std::string & extents_name)
Referenced by read_extents().
read_extents< 3 >()
template Index<3> h5::read_extents< 3 > (const hid_t group_id, const std::string & extents_name)
Referenced by read_extents().
write_data< 1 >()
template void h5::write_data< 1 > (const hid_t group_id, const DataVector & data, const Index< 1 > & extents, const std::string & name)
Referenced by read_extents().
write_data< 2 >()
template void h5::write_data< 2 > (const hid_t group_id, const DataVector & data, const Index< 2 > & extents, const std::string & name)
Referenced by read_extents().
write_data< 3 >()
template void h5::write_data< 3 > (const hid_t group_id, const DataVector & data, const Index< 3 > & extents, const std::string & name)
Referenced by read_extents().
write_extents< 1 >()
template void h5::write_extents< 1 > (const hid_t group_id, const Index< 1 > & extents, const std::string & name)
Referenced by read_extents().
write_extents< 2 >()
template void h5::write_extents< 2 > (const hid_t group_id, const Index< 2 > & extents, const std::string & name)
Referenced by read_extents().
write_extents< 3 >()
template void h5::write_extents< 3 > (const hid_t group_id, const Index< 3 > & extents, const std::string & name)
Referenced by read_extents().