SpECTRE: Parallel Namespace Reference
Parallel Namespace Reference
Contains functions that forward to Charm++ parallel functions.
Classes
struct ArrayIndex
The array index used for indexing Chare Arrays, mostly an implementation detail.
class ConstGlobalCache
A Charm++ chare that caches constant data once per Charm++ node.
struct has_pup_member
Check if T has a pup member function.
struct is_array_proxy
Check if T is a Charm++ proxy for an array chare.
struct is_bound_array
Check if T is a ParallelComponent for a Charm++ bound array.
struct is_bound_array< T, cpp17::void_t< typename T::bind_to > >
struct is_chare_proxy
Check if T is a Charm++ proxy for a chare.
struct is_group_proxy
Check if T is a Charm++ proxy for a group chare.
struct is_node_group_proxy
Check if T is a Charm++ proxy for a node group chare.
struct is_pupable
Check if type T has operator| defined for Charm++ serialization.
class Main
The main function of a Charm++ executable.
struct ReductionData
Used for reducing heterogeneous collection of types in a single reduction call.
Typedefs
using type = std::integral_constant< bool, value >
using ArrayIndex1D = ArrayIndex< CkIndex1D >
using ArrayIndex2D = ArrayIndex< CkIndex2D >
using ArrayIndex3D = ArrayIndex< CkIndex3D >
using ArrayIndex4D = ArrayIndex< CkIndex4D >
using ArrayIndex5D = ArrayIndex< CkIndex5D >
using ArrayIndex6D = ArrayIndex< CkIndex6D >
Functions
void abort (const std::string &message)
Abort the program with an error message.
void lock (const gsl::not_null< CmiNodeLock *> node_lock) noexcept
Lock a converse CmiNodeLock.
bool try_lock (const gsl::not_null< CmiNodeLock *> node_lock) noexcept
Returns true if the lock was successfully acquired and false if the lock is already acquired by another processor.
void unlock (const gsl::not_null< CmiNodeLock *> node_lock) noexcept
Unlock a converse CmiNodeLock.
void exit ()
Exit the program normally. This should only be called once over all processors.
int number_of_procs ()
Number of processing elements.
int my_proc ()
Index of my processing element.
int number_of_nodes ()
Number of nodes.
int my_node ()
Index of my node.
int procs_on_node (const int node_index)
Number of processing elements on the given node.
int my_local_rank ()
The local index of my processing element on my node. This is in the interval 0, ..., procs_on_node(my_node()) - 1.
int first_proc_on_node (const int node_index)
Index of first processing element on the given node.
int node_of (const int proc_index)
Index of the node for the given processing element.
int local_rank_of (const int proc_index)
The local index for the given processing element on its node.
double wall_time ()
The current wall time in seconds.
template<typename... Args>
void printf (const std::string &format, Args &&... args)
Print an atomic message to stdout with C printf usage.
template<size_t Index, class... Us>
auto get (ReductionData< Us... > &reduction_data) noexcept -> decltype(std::get< Index >(reduction_data.data))
Retrieve the Indexth element from a ReductionData<Ts...>, similar to std::get for std::tuples.
template<class SenderParallelComponent , class TargetParallelComponent , class Action , class Metavariables , class ArrayIndex , class ReductionType , Requires< not Parallel_detail::is_custom_reduction_type_v< ReductionType >> = nullptr>
void contribute_to_reduction (const ConstGlobalCache< Metavariables > &cache, const ArrayIndex &array_index, CkReduction::reducerType reducer, const ReductionType &reduction_data) noexcept
Perform a reduction from the current ParallelComponent to the TargetParallelComponent, performing the Action upon receiving the reduction.
template<class... Ts>
CkReductionMsg * new_reduction_msg (ReductionData< Ts... > &reduction_data) noexcept
Convert a ReductionData to a CkReductionMsg. Used in custom reducers.
template<typename ParallelComponentTag , typename Metavariables >
Parallel::proxy_from_parallel_component< ParallelComponentTag > & get_parallel_component (ConstGlobalCache< Metavariables > &cache) noexcept
Access the Charm++ proxy associated with a ParallelComponent.
template<typename ParallelComponentTag , typename Metavariables >
const Parallel::proxy_from_parallel_component< ParallelComponentTag > & get_parallel_component (const ConstGlobalCache< Metavariables > &cache) noexcept
Access the Charm++ proxy associated with a ParallelComponent.
template<typename ConstGlobalCacheTag , typename Metavariables >
const ConstGlobalCache_detail::type_for_get< typename ConstGlobalCacheTag::type >::type & get (const ConstGlobalCache< Metavariables > &cache) noexcept
Access data in the cache.
Variables
static constexpr bool value = decltype(test_callable<TT, TArgs...>(0))::value
template<typename T >
using has_pup_member_t = typename has_pup_member< T >::type
template<typename T >
constexpr bool has_pup_member_v = has_pup_member<T>::value
template<typename T >
using is_pupable_t = typename is_pupable< T >::type
template<typename T >
constexpr bool is_pupable_v = is_pupable<T>::value
Detailed Description
Contains functions that forward to Charm++ parallel functions.
Typedef Documentation
ArrayIndex1D
using Parallel::ArrayIndex1D = typedef ArrayIndex<CkIndex1D>
ArrayIndex2D
using Parallel::ArrayIndex2D = typedef ArrayIndex<CkIndex2D>
ArrayIndex3D
using Parallel::ArrayIndex3D = typedef ArrayIndex<CkIndex3D>
ArrayIndex4D
using Parallel::ArrayIndex4D = typedef ArrayIndex<CkIndex4D>
ArrayIndex5D
using Parallel::ArrayIndex5D = typedef ArrayIndex<CkIndex5D>
ArrayIndex6D
using Parallel::ArrayIndex6D = typedef ArrayIndex<CkIndex6D>
has_pup_member_t
template<typename T > using Parallel::has_pup_member_t = typedef typename has_pup_member<T>::type
See also
has_pup_member
is_pupable_t
template<typename T > using Parallel::is_pupable_t = typedef typename is_pupable<T>::type
See also
is_pupable
type
using Parallel::type = typedef std::integral_constant<bool, value>
Variable Documentation
has_pup_member_v
template<typename T > constexpr bool Parallel::has_pup_member_v = has_pup_member<T>::value
See also
has_pup_member
is_pupable_v
template<typename T > constexpr bool Parallel::is_pupable_v = is_pupable<T>::value
See also
is_pupable
value
constexpr bool Parallel::value = decltype(test_callable<TT, TArgs...>(0))::value static
Referenced by MakeWithValueImpls::MakeWithValueImpl< Variables< TagList >, DataVector >::apply(), MakeWithValueImpls::MakeWithValueImpl< Variables< TagList >, Tensor< DataVector, Structure... > >::apply(), MakeWithValueImpls::MakeWithValueImpl< Variables< TagListOut >, Variables< TagListIn > >::apply(), MakeWithValueImpls::MakeWithValueImpl< Tensor< DataVector, Structure... >, DataVector >::apply(), MakeWithValueImpls::MakeWithValueImpl< DataVector, Tensor< DataVector, Structure... > >::apply(), MakeWithValueImpls::MakeWithValueImpl< Tensor< DataVector, StructureOut... >, Tensor< DataVector, StructureIn... > >::apply(), MakeWithValueImpls::MakeWithValueImpl< Tensor< double, Structure... >, double >::apply(), MakeWithValueImpls::MakeWithValueImpl< double, Tensor< double, Structure... > >::apply(), MakeWithValueImpls::MakeWithValueImpl< Tensor< double, StructureOut... >, Tensor< double, StructureIn... > >::apply(), MakeWithValueImpls::MakeWithValueImpl< R, T >::apply(), apply_visitor_helper(), TimeStepper::compute_boundary_delta(), TimeSteppers::AdamsBashforthN::compute_boundary_delta(), TensorExpressions::contract(), cube(), ElementIndex< VolumeDim >::ElementIndex(), TensorExpressions::evaluate(), Tensor< X, Symm, IndexList< Indices... > >::get(), tuples::get(), db::get_tag_name(), AlgorithmImpl< ParallelComponent, ChareType, Metavariables, tmpl::list< ActionsPack... >, tmpl::list< InboxTagsPack... >, ArrayIndex, InitialDataBox >::get_terminate(), Options< option_list >::help(), CoordinateMap< SourceFrame, TargetFrame, Maps >::inv_jacobian_impl(), CoordinateMap< SourceFrame, TargetFrame, Maps >::jacobian_impl(), magnitude(), Parallel::Main< Metavariables >::Main(), make_array(), make_array_from_list(), min_by_magnitude(), gsl::narrow(), Tensor< X, Symm, IndexList< Indices... > >::operator()(), operator+(), operator-(), operator<<(), tuples::TaggedTuple< InboxTagsPack... >::operator=(), tuples::operator>=(), TensorExpression< Derived, DataType, Symm, IndexList, ArgsList< Args... > >::operator~(), Options< option_list >::Options(), blaze::DivideScalarByVector< ST >::simdEnabled(), blaze::AddScalar< ST >::simdEnabled(), blaze::SubScalarRhs< ST >::simdEnabled(), blaze::SubScalarLhs< ST >::simdEnabled(), tuples::TaggedTuple< InboxTagsPack... >::TaggedTuple(), and Time::Time().