SpECTRE: src/Utilities/Spherepack.hpp File Reference
Spherepack.hpp File Reference
Provides a C++ interface to the Fortran SPHEREPACK library.
Functions
void shagsi_ (const int &, const int &, double *, const int &, double *, const int &, double *, const int &, gsl::not_null< int *>)
void shags_ (const int &, const int &, const int &, const int &, const int &, const int &, const int &, const int &, const double *, const int &, const int &, double *, double *, const int &, const int &, const int &, const int &, const double *, const int &, double *, const int &, gsl::not_null< int *>)
void shsgsi_ (const int &, const int &, double *, const int &, double *, const int &, double *, const int &, gsl::not_null< int *>)
void shsgs_ (const int &, const int &, const int &, const int &, const int &, const int &, const int &, const int &, double *, const int &, const int &, const double *, const double *, const int &, const int &, const int &, const int &, const double *, const int &, double *, const int &, gsl::not_null< int *>)
void vhagsi_ (const int &, const int &, double *, const int &, double *, const int &, gsl::not_null< int *>)
void vhags_ (const int &, const int &, const int &, const int &, const int &, const int &, const int &, const int &, const double *, const double *, const int &, const int &, double *, double *, double *, double *, const int &, const int &, const double *, const int &, double *, const int &, gsl::not_null< int *>)
void vhsgsi_ (const int &, const int &, double *, const int &, double *, const int &, gsl::not_null< int *>)
void vhsgs_ (const int &, const int &, const int &, const int &, const int &, const int &, const int &, const int &, double *, double *, const int &, const int &, const double *, const double *, const double *, const double *, const int &, const int &, const double *, const int &, double *, const int &, gsl::not_null< int *>)
void slapgs_ (const int &, const int &, const int &, const int &, const int &, const int &, const int &, const int &, double *, const int &, const int &, const double *, const double *, const int &, const int &, const double *, const int &, double *, const int &, gsl::not_null< int *>)
void gradgs_ (const int &, const int &, const int &, const int &, const int &, const int &, const int &, const int &, double *, double *, const int &, const int &, const double *, const double *, const int &, const int &, const double *, const int &, double *, const int &, gsl::not_null< int *>)
void divgs_ (const int &, const int &, const int &, const int &, const int &, const int &, const int &, const int &, double *, const int &, const int &, const double *, const double *, const int &, const int &, const double *, const int &, double *, const int &, gsl::not_null< int *>)
void vrtgs_ (const int &, const int &, const int &, const int &, const int &, const int &, const int &, const int &, double *, const int &, const int &, const double *, const double *, const int &, const int &, const double *, const int &, double *, const int &, gsl::not_null< int *>)
void vtsgsi_ (const int &, const int &, double *, const int &, double *, const int &, double *, const int &, gsl::not_null< int *>)
void vtsgs_ (const int &, const int &, const int &, const int &, const int &, const int &, const int &, const int &, double *, double *, const int &, const int &, const double *, const double *, const double *, const double *, const int &, const int &, const double *, const int &, double *, const int &, gsl::not_null< int *>)
void alfk_ (const int &, const int &, double *)
void lfin_ (const int &, const double *, const int &, const int &, const int &, double *, const int &, double *)
void gaqd_ (const int &, double *, double *, double *, const int &, gsl::not_null< int *>)
Detailed Description
Provides a C++ interface to the Fortran SPHEREPACK library.
Function Documentation
alfk_()
void alfk_ (const int & , const int & , double *)
divgs_()
void divgs_ (const int & , const int & , const int & , const int & , const int & , const int & , const int & , const int & , double * , const int & , const int & , const double * , const double * , const int & , const int & , const double * , const int & , double * , const int & , gsl::not_null< int *>)
gaqd_()
void gaqd_ (const int & , double * , double * , double * , const int & , gsl::not_null< int *>)
Referenced by YlmSpherepack::interpolate_from_coefs(), and YlmSpherepack::theta_points().
gradgs_()
void gradgs_ (const int & , const int & , const int & , const int & , const int & , const int & , const int & , const int & , double * , double * , const int & , const int & , const double * , const double * , const int & , const int & , const double * , const int & , double * , const int & , gsl::not_null< int *>)
Referenced by YlmSpherepack::spec_to_phys_all_offsets().
lfin_()
void lfin_ (const int & , const double * , const int & , const int & , const int & , double * , const int & , double *)
shags_()
void shags_ (const int & , const int & , const int & , const int & , const int & , const int & , const int & , const int & , const double * , const int & , const int & , double * , double * , const int & , const int & , const int & , const int & , const double * , const int & , double * , const int & , gsl::not_null< int *>)
Referenced by YlmSpherepack::YlmSpherepack().
shagsi_()
void shagsi_ (const int & , const int & , double * , const int & , double * , const int & , double * , const int & , gsl::not_null< int *>)
Referenced by YlmSpherepack::interpolate_from_coefs().
shsgs_()
void shsgs_ (const int & , const int & , const int & , const int & , const int & , const int & , const int & , const int & , double * , const int & , const int & , const double * , const double * , const int & , const int & , const int & , const int & , const double * , const int & , double * , const int & , gsl::not_null< int *>)
Referenced by YlmSpherepack::YlmSpherepack().
shsgsi_()
void shsgsi_ (const int & , const int & , double * , const int & , double * , const int & , double * , const int & , gsl::not_null< int *>)
Referenced by YlmSpherepack::interpolate_from_coefs().
slapgs_()
void slapgs_ (const int & , const int & , const int & , const int & , const int & , const int & , const int & , const int & , double * , const int & , const int & , const double * , const double * , const int & , const int & , const double * , const int & , double * , const int & , gsl::not_null< int *>)
Referenced by YlmSpherepack::gradient_from_coefs_all_offsets().
vhags_()
void vhags_ (const int & , const int & , const int & , const int & , const int & , const int & , const int & , const int & , const double * , const double * , const int & , const int & , double * , double * , double * , double * , const int & , const int & , const double * , const int & , double * , const int & , gsl::not_null< int *>)
vhagsi_()
void vhagsi_ (const int & , const int & , double * , const int & , double * , const int & , gsl::not_null< int *>)
vhsgs_()
void vhsgs_ (const int & , const int & , const int & , const int & , const int & , const int & , const int & , const int & , double * , double * , const int & , const int & , const double * , const double * , const double * , const double * , const int & , const int & , const double * , const int & , double * , const int & , gsl::not_null< int *>)
vhsgsi_()
void vhsgsi_ (const int & , const int & , double * , const int & , double * , const int & , gsl::not_null< int *>)
Referenced by YlmSpherepack::interpolate_from_coefs().
vrtgs_()
void vrtgs_ (const int & , const int & , const int & , const int & , const int & , const int & , const int & , const int & , double * , const int & , const int & , const double * , const double * , const int & , const int & , const double * , const int & , double * , const int & , gsl::not_null< int *>)
vtsgs_()
void vtsgs_ (const int & , const int & , const int & , const int & , const int & , const int & , const int & , const int & , double * , double * , const int & , const int & , const double * , const double * , const double * , const double * , const int & , const int & , const double * , const int & , double * , const int & , gsl::not_null< int *>)
vtsgsi_()
void vtsgsi_ (const int & , const int & , double * , const int & , double * , const int & , double * , const int & , gsl::not_null< int *>)