SpECTRE: create_from_yaml< T > Struct Template Reference
create_from_yaml< T > Struct Template Reference
Option Parsing
Used by the parser to create an object. The default action is to parse options using T::options. This struct may be specialized to change that behavior for specific types.
#include <Options.hpp>
Static Public Member Functions
static T create (const Option &options)
Detailed Description
template<typename T>
struct create_from_yaml< T >
Used by the parser to create an object. The default action is to parse options using T::options. This struct may be specialized to change that behavior for specific types.
Do not call create directly. Use Option::parse_as instead.
Member Function Documentation
create()
template<typename T > T create_from_yaml< T >::create (const Option & options) static
References OptionContext::append(), Option::context(), db::create(), make_overloader(), Options< OptionList >::parse(), Option::parse_as(), and OptionContext::top_level.
The documentation for this struct was generated from the following files:
src/Options/Options.hpp
src/Options/ParseOptions.hpp