SpECTRE: MakeWithValueImpls::MakeWithValueImpl< R, T > Struct Template Reference
MakeWithValueImpls::MakeWithValueImpl< R, T > Struct Template Reference
#include <MakeWithValue.hpp>
Public Member Functions
template<>
DataVector apply (const DataVector &input, const double value)
Returns a DataVector the same size as input, with each element equal to value.
template<>
double apply (const double &, const double value)
Returns a double initialized to value (input is ignored)
Static Public Member Functions
static R apply (const T &input, double value)
Member Function Documentation
apply() [1/3]
template<typename R , typename T > static R MakeWithValueImpls::MakeWithValueImpl< R, T >::apply (const T & input, double value) static
Referenced by make_with_value().
apply() [2/3]
template<> double MakeWithValueImpls::MakeWithValueImpl< double, double >::apply (const double & , const double value)
Returns a double initialized to value (input is ignored)
References Parallel::value.
apply() [3/3]
template<> DataVector MakeWithValueImpls::MakeWithValueImpl< DataVector, DataVector >::apply (const DataVector & input, const double value)
Returns a DataVector the same size as input, with each element equal to value.
References db::apply(), pow(), DataVector::size(), SPECTRE_ALWAYS_INLINE, and Parallel::value.
The documentation for this struct was generated from the following file:
src/DataStructures/MakeWithValue.hpp