SpECTRE: Actions::SendDataForFluxes< Receiver > Struct Template Reference
Actions::SendDataForFluxes< Receiver > Struct Template Reference
Actions | Discontinuous Galerkin
Compute local boundary data needed for fluxes and send it to neighbors.
#include <FluxCommunication.hpp>
Static Public Member Functions
template<typename DbTags , typename... InboxTags, typename Metavariables , typename ArrayIndex , typename ActionList >
static auto apply (db::DataBox< DbTags > &box, tuples::TaggedTuple< InboxTags... > &, Parallel::ConstGlobalCache< Metavariables > &cache, const ArrayIndex &, const ActionList) noexcept
Detailed Description
template<typename Receiver>
struct Actions::SendDataForFluxes< Receiver >
Compute local boundary data needed for fluxes and send it to neighbors.
Note
The data is oriented for the receiver, but the receiver is responsible for projection, etc.
Uses:
ConstGlobalCache: Receiver
DataBox: system::variables_tag, Tags::Element<volume_dim>, Tags::Extents<volume_dim>, Tags::TimeId
DataBox changes:
Adds: Tags::HistoryBoundaryVariables<Direction<volume_dim>, system::variables_tag>
Removes: nothing
Modifies: nothing
Template Parameters
Receiver the parallel_component to send data to
Member Function Documentation
apply()
template<typename Receiver > template<typename DbTags , typename... InboxTags, typename Metavariables , typename ArrayIndex , typename ActionList > static auto Actions::SendDataForFluxes< Receiver >::apply (db::DataBox< DbTags > & box, tuples::TaggedTuple< InboxTags... > & , Parallel::ConstGlobalCache< Metavariables > & cache, const ArrayIndex & , const ActionList) inline static noexcept
References gsl::at(), db::create_from(), data_on_slice(), Lower, and orient_variables_on_slice().
The documentation for this struct was generated from the following file:
src/Numerical/DiscontinuousGalerkin/Actions/FluxCommunication.hpp